"""
Exchange-Specific Field Mappings for Trading Data

Defines field name mappings from exchange-specific formats to unified format.
"""

from typing import Dict, List, Any
from exchanges.exchange_types import ExchangeType


# Order field mappings
ORDER_FIELD_MAPPINGS = {
    ExchangeType.BINANCE: {
        'order_id': ['orderId', 'order_id'],
        'client_order_id': ['clientOrderId', 'client_order_id', 'newClientOrderId'],
        'symbol': ['symbol'],
        'side': ['side'],
        'order_type': ['type', 'orderType'],
        'status': ['status'],
        'quantity': ['origQty', 'orig_quantity', 'quantity'],
        'executed_quantity': ['executedQty', 'executed_quantity'],
        'remaining_quantity': ['cummulativeQuoteQty', 'cummulative_quote_qty'],
        'price': ['price'],
        'executed_price_avg': ['avgPrice', 'avg_price', 'averagePrice'],
        'stop_price': ['stopPrice', 'stop_price'],
        'time_in_force': ['timeInForce', 'time_in_force'],
        'timestamp': ['time', 'timestamp', 'createTime', 'create_time'],
        'update_time': ['updateTime', 'update_time'],
        'fee': ['commission', 'fee'],
        'fee_currency': ['commissionAsset', 'commission_asset', 'feeCurrency'],
    },
    ExchangeType.OKX: {
        'order_id': ['ordId', 'order_id'],
        'client_order_id': ['clOrdId', 'client_order_id'],
        'symbol': ['instId', 'symbol', 'inst_id'],
        'side': ['side'],
        'order_type': ['ordType', 'order_type'],
        'status': ['state'],
        'quantity': ['sz', 'size', 'quantity'],
        'executed_quantity': ['accFillSz', 'acc_fill_sz', 'filled_quantity'],
        'remaining_quantity': ['sz', 'size'],
        'price': ['px', 'price'],
        'executed_price_avg': ['avgPx', 'avg_px', 'avg_price'],
        'stop_price': ['slTriggerPx', 'sl_trigger_px', 'stop_price'],
        'time_in_force': ['tdMode', 'td_mode', 'time_in_force'],
        'timestamp': ['cTime', 'c_time', 'timestamp', 'ts'],
        'update_time': ['uTime', 'u_time', 'update_time'],
        'fee': ['fee', 'commission'],
        'fee_currency': ['feeCcy', 'fee_ccy', 'fee_currency'],
    },
    ExchangeType.BINGX: {
        'order_id': ['orderId', 'order_id'],
        'client_order_id': ['clientOrderId', 'client_order_id'],
        'symbol': ['symbol', 'symbolName'],
        'side': ['side'],
        'order_type': ['type', 'orderType'],
        'status': ['status'],
        'quantity': ['origQty', 'orig_quantity', 'quantity'],
        'executed_quantity': ['executedQty', 'executed_quantity'],
        'remaining_quantity': ['origQty', 'executedQty'],  # Will be calculated
        'price': ['price'],
        'executed_price_avg': ['avgPrice', 'avg_price'],
        'stop_price': ['stopPrice', 'stop_price'],
        'time_in_force': ['timeInForce', 'time_in_force'],
        'timestamp': ['time', 'timestamp', 'createTime'],
        'update_time': ['updateTime', 'update_time'],
        'fee': ['commission', 'fee'],
        'fee_currency': ['commissionAsset', 'commission_asset'],
    },
    ExchangeType.MEXC: {
        'order_id': ['orderId', 'order_id'],
        'client_order_id': ['clientOrderId', 'client_order_id'],
        'symbol': ['symbol'],
        'side': ['side'],
        'order_type': ['type', 'orderType'],
        'status': ['status'],
        'quantity': ['origQty', 'orig_quantity', 'quantity'],
        'executed_quantity': ['executedQty', 'executed_quantity'],
        'remaining_quantity': ['origQty'],
        'price': ['price'],
        'executed_price_avg': ['avgPrice', 'avg_price'],
        'stop_price': ['stopPrice', 'stop_price'],
        'time_in_force': ['timeInForce', 'time_in_force'],
        'timestamp': ['time', 'timestamp'],
        'update_time': ['updateTime', 'update_time'],
        'fee': ['commission', 'fee'],
        'fee_currency': ['commissionAsset', 'commission_asset'],
    },
    ExchangeType.GATEIO: {
        'order_id': ['id', 'order_id'],
        'client_order_id': ['text', 'client_order_id'],
        'symbol': ['currency_pair', 'symbol'],
        'side': ['side'],
        'order_type': ['type', 'order_type'],
        'status': ['status'],
        'quantity': ['amount', 'quantity'],
        'executed_quantity': ['filled_total', 'filled_quantity'],
        'remaining_quantity': ['left', 'remaining'],
        'price': ['price'],
        'executed_price_avg': ['average_price', 'avg_price'],
        'stop_price': ['stop_price'],
        'time_in_force': ['time_in_force'],
        'timestamp': ['create_time', 'timestamp'],
        'update_time': ['update_time'],
        'fee': ['fee', 'trading_fee'],
        'fee_currency': ['fee_currency'],
    },
    ExchangeType.PHEMEX: {
        'order_id': ['orderID', 'order_id'],
        'client_order_id': ['clOrdID', 'client_order_id'],
        'symbol': ['symbol'],
        'side': ['side'],
        'order_type': ['ordType', 'order_type'],
        'status': ['ordStatus', 'order_status'],
        'quantity': ['orderQty', 'order_qty', 'quantity'],
        'executed_quantity': ['cumQty', 'cum_qty', 'filled_quantity'],
        'remaining_quantity': ['leavesQty', 'leaves_qty'],
        'price': ['price'],
        'executed_price_avg': ['avgPx', 'avg_price'],
        'stop_price': ['stopPx', 'stop_price'],
        'time_in_force': ['timeInForce', 'time_in_force'],
        'timestamp': ['transactTime', 'transact_time', 'timestamp'],
        'update_time': ['updateTime', 'update_time'],
        'fee': ['commission', 'fee'],
        'fee_currency': ['commCurrency', 'comm_currency'],
    },
}

# Position field mappings
POSITION_FIELD_MAPPINGS = {
    ExchangeType.BINANCE: {
        'symbol': ['symbol'],
        'side': ['positionSide', 'position_side', 'side'],
        'size': ['positionAmt', 'position_amt', 'size'],
        'entry_price': ['entryPrice', 'entry_price'],
        'mark_price': ['markPrice', 'mark_price'],
        'liquidation_price': ['liquidationPrice', 'liquidation_price'],
        'unrealized_pnl': ['unRealizedProfit', 'unrealized_profit', 'unRealizedPnl'],
        'realized_pnl': ['realizedProfit', 'realized_profit'],
        'leverage': ['leverage'],
        'margin': ['isolatedMargin', 'isolated_margin', 'margin'],
        'isolated_margin': ['isolatedMargin', 'isolated_margin'],
        'margin_mode': ['marginType', 'margin_type', 'marginMode'],
        'position_mode': ['hedgeMode', 'hedge_mode'],
        'timestamp': ['updateTime', 'update_time', 'timestamp'],
    },
    ExchangeType.OKX: {
        'symbol': ['instId', 'inst_id', 'symbol'],
        'side': ['posSide', 'pos_side', 'side'],
        'size': ['pos', 'position', 'size'],
        'entry_price': ['avgPx', 'avg_px', 'entry_price'],
        'mark_price': ['markPx', 'mark_px', 'mark_price'],
        'liquidation_price': ['liqPx', 'liq_px', 'liquidation_price'],
        'unrealized_pnl': ['upl', 'unrealized_pnl', 'unrealizedPnl'],
        'realized_pnl': ['realizedPnl', 'realized_pnl'],
        'leverage': ['lever', 'leverage'],
        'margin': ['margin', 'imr'],
        'isolated_margin': ['imr', 'isolated_margin'],
        'margin_mode': ['mgnMode', 'mgn_mode', 'margin_mode'],
        'position_mode': ['posMode', 'pos_mode'],
        'timestamp': ['uTime', 'u_time', 'timestamp'],
    },
    ExchangeType.BINGX: {
        'symbol': ['symbol', 'symbolName'],
        'side': ['positionSide', 'side'],
        'size': ['positionAmt', 'size'],
        'entry_price': ['entryPrice', 'entry_price'],
        'mark_price': ['markPrice', 'mark_price'],
        'liquidation_price': ['liquidationPrice', 'liquidation_price'],
        'unrealized_pnl': ['unrealizedProfit', 'unrealized_pnl'],
        'realized_pnl': ['realizedProfit'],
        'leverage': ['leverage'],
        'margin': ['margin', 'isolatedMargin'],
        'margin_mode': ['marginType'],
        'timestamp': ['updateTime', 'timestamp'],
    },
    ExchangeType.MEXC: {
        'symbol': ['symbol'],
        'side': ['positionSide', 'side'],
        'size': ['positionAmt', 'size'],
        'entry_price': ['entryPrice', 'entry_price'],
        'mark_price': ['markPrice'],
        'liquidation_price': ['liquidationPrice'],
        'unrealized_pnl': ['unrealizedProfit'],
        'leverage': ['leverage'],
        'margin': ['margin'],
        'timestamp': ['updateTime'],
    },
    ExchangeType.GATEIO: {
        'symbol': ['contract', 'symbol'],
        'side': ['mode', 'side'],
        'size': ['size'],
        'entry_price': ['entry_price'],
        'mark_price': ['mark_price'],
        'unrealized_pnl': ['unrealized_pnl'],
        'leverage': ['leverage'],
        'margin': ['margin'],
        'timestamp': ['update_time'],
    },
    ExchangeType.PHEMEX: {
        'symbol': ['symbol'],
        'side': ['side'],
        'size': ['size'],
        'entry_price': ['entryPrice'],
        'mark_price': ['markPrice'],
        'unrealized_pnl': ['unrealisedPnl'],
        'leverage': ['leverage'],
        'timestamp': ['updated'],
    },
}

# Balance field mappings
BALANCE_FIELD_MAPPINGS = {
    ExchangeType.BINANCE: {
        'currency': ['asset', 'currency'],
        'free': ['free', 'available'],
        'used': ['locked', 'used'],
        'total': ['free', 'locked'],  # Will be calculated
        'available_balance': ['available'],
        'frozen_balance': ['frozen', 'locked'],
        'account_type': ['accountType', 'account_type'],
        'timestamp': ['updateTime', 'update_time', 'timestamp'],
    },
    ExchangeType.OKX: {
        'currency': ['ccy', 'currency'],
        'free': ['avail', 'available', 'free'],
        'used': ['frozen', 'used', 'locked'],
        'total': ['eq', 'equity', 'bal'],
        'available_balance': ['availBal', 'avail_bal'],
        'frozen_balance': ['frozenBal', 'frozen_bal'],
        'account_type': ['acctType', 'acct_type'],
        'timestamp': ['uTime', 'u_time', 'timestamp'],
    },
    ExchangeType.BINGX: {
        'currency': ['asset', 'currency'],
        'free': ['free', 'available'],
        'used': ['locked', 'used'],
        'total': ['total'],
        'account_type': ['accountType'],
        'timestamp': ['updateTime'],
    },
    ExchangeType.MEXC: {
        'currency': ['asset', 'currency'],
        'free': ['free'],
        'used': ['locked'],
        'total': ['total'],
        'timestamp': ['updateTime'],
    },
    ExchangeType.GATEIO: {
        'currency': ['currency'],
        'free': ['available', 'free'],
        'used': ['locked', 'used'],
        'total': ['total'],
        'timestamp': ['timestamp'],
    },
    ExchangeType.PHEMEX: {
        'currency': ['currency'],
        'free': ['availableEv', 'available'],
        'used': ['lockedEv', 'locked'],
        'total': ['totalEv', 'total'],
        'timestamp': ['updated'],
    },
}

# Trade field mappings
TRADE_FIELD_MAPPINGS = {
    ExchangeType.BINANCE: {
        'trade_id': ['id', 'tradeId', 'trade_id'],
        'order_id': ['orderId', 'order_id'],
        'symbol': ['symbol'],
        'side': ['side'],
        'price': ['price'],
        'quantity': ['qty', 'quantity'],
        'fee': ['commission', 'fee'],
        'fee_currency': ['commissionAsset', 'commission_asset'],
        'is_maker': ['isMaker', 'is_maker'],
        'is_buyer': ['isBuyer', 'is_buyer'],
        'timestamp': ['time', 'timestamp'],
    },
    ExchangeType.OKX: {
        'trade_id': ['tradeId', 'trade_id'],
        'order_id': ['ordId', 'order_id'],
        'symbol': ['instId', 'symbol'],
        'side': ['side'],
        'price': ['px', 'price'],
        'quantity': ['sz', 'size'],
        'fee': ['fee'],
        'fee_currency': ['feeCcy', 'fee_currency'],
        'is_maker': ['side'],
        'timestamp': ['ts', 'timestamp'],
    },
    ExchangeType.BINGX: {
        'trade_id': ['id', 'tradeId'],
        'order_id': ['orderId'],
        'symbol': ['symbol'],
        'side': ['side'],
        'price': ['price'],
        'quantity': ['qty', 'quantity'],
        'fee': ['commission'],
        'fee_currency': ['commissionAsset'],
        'timestamp': ['time'],
    },
    ExchangeType.MEXC: {
        'trade_id': ['id', 'tradeId'],
        'order_id': ['orderId'],
        'symbol': ['symbol'],
        'side': ['side'],
        'price': ['price'],
        'quantity': ['qty'],
        'fee': ['commission'],
        'timestamp': ['time'],
    },
    ExchangeType.GATEIO: {
        'trade_id': ['id', 'trade_id'],
        'order_id': ['order_id'],
        'symbol': ['currency_pair', 'symbol'],
        'side': ['side'],
        'price': ['price'],
        'quantity': ['amount'],
        'fee': ['fee'],
        'fee_currency': ['fee_currency'],
        'timestamp': ['create_time'],
    },
    ExchangeType.PHEMEX: {
        'trade_id': ['execID', 'exec_id'],
        'order_id': ['orderID', 'order_id'],
        'symbol': ['symbol'],
        'side': ['side'],
        'price': ['lastPx', 'price'],
        'quantity': ['lastQty', 'quantity'],
        'fee': ['commission'],
        'timestamp': ['transactTime'],
    },
}