#!/usr/bin/env python3
"""
Support/Resistance Feature Extraction - Code Location Guide

This script shows exactly where in the code the SR feature extraction happens.
"""

def show_sr_code_locations():
    """Show the exact code locations for SR feature extraction"""
    
    print("🎯 SUPPORT/RESISTANCE FEATURE EXTRACTION - CODE LOCATIONS")
    print("="*70)
    
    print("\n📁 FILE: /workspace/src/training/steps/market_analysis/hmm_clustering/step03_hmm_regime_discovery.py")
    print("="*70)
    
    print("\n🔧 1. MAIN FEATURE CREATION ENTRY POINT:")
    print("   Method: EnhancedFeatureEngineer.create_comprehensive_features()")
    print("   Location: Line 226-235")
    print("   Code:")
    print("   ```python")
    print("   def create_comprehensive_features(self, df: pd.DataFrame) -> pd.DataFrame:")
    print("       self.logger.info('🔧 Creating comprehensive feature set (100+ features)...')")
    print("       features = pd.DataFrame()")
    print("       # ... initialization ...")
    print("       # Support/Resistance features")
    print("       self._add_sr_features(features, df)  # <-- SR EXTRACTION CALLED HERE")
    print("   ```")
    
    print("\n🎯 2. SR FEATURE EXTRACTION METHOD:")
    print("   Method: EnhancedFeatureEngineer._add_sr_features()")
    print("   Location: Lines 411-432")
    print("   Code:")
    print("   ```python")
    print("   def _add_sr_features(self, features: pd.DataFrame, df: pd.DataFrame) -> None:")
    print("       '''Add support/resistance features'''")
    print("       # Pivot points")
    print("       features['pivot_point'] = (df['high'] + df['low'] + df['close']) / 3")
    print("       features['support_1'] = 2 * features['pivot_point'] - df['high']")
    print("       features['resistance_1'] = 2 * features['pivot_point'] - df['low']")
    print("       features['support_2'] = features['pivot_point'] - (df['high'] - df['low'])")
    print("       features['resistance_2'] = features['pivot_point'] + (df['high'] - df['low'])")
    print("       ")
    print("       # Distance to S/R levels")
    print("       features['distance_to_support'] = (df['close'] - features['support_1']) / df['close']")
    print("       features['distance_to_resistance'] = (features['resistance_1'] - df['close']) / df['close']")
    print("       ")
    print("       # S/R strength")
    print("       features['sr_strength'] = self._calculate_sr_strength(df)")
    print("       ")
    print("       # Swing highs and lows")
    print("       for window in [10, 20, 50]:")
    print("           features[f'swing_high_{window}'] = df['high'].rolling(window, center=True).max()")
    print("           features[f'swing_low_{window}'] = df['low'].rolling(window, center=True).min()")
    print("           features[f'distance_to_swing_high_{window}'] = (features[f'swing_high_{window}'] - df['close']) / df['close']")
    print("           features[f'distance_to_swing_low_{window}'] = (df['close'] - features[f'swing_low_{window}']) / df['close']")
    print("   ```")
    
    print("\n💪 3. SR STRENGTH CALCULATION METHOD:")
    print("   Method: EnhancedFeatureEngineer._calculate_sr_strength()")
    print("   Location: Lines 737-746")
    print("   Code:")
    print("   ```python")
    print("   def _calculate_sr_strength(self, df: pd.DataFrame, window: int = 20) -> pd.Series:")
    print("       '''Calculate support/resistance strength'''")
    print("       high_swing = df['high'].rolling(window, center=True).max()")
    print("       low_swing = df['low'].rolling(window, center=True).min()")
    print("       current_price = df['close']")
    print("       ")
    print("       high_strength = (high_swing - current_price) / high_swing")
    print("       low_strength = (current_price - low_swing) / low_swing")
    print("       ")
    print("       return (high_strength + low_strength) / 2")
    print("   ```")
    
    print("\n🔗 4. SR INTERACTION FEATURES:")
    print("   Method: EnhancedFeatureEngineer._add_cross_category_interactions()")
    print("   Location: Lines 618-623")
    print("   Code:")
    print("   ```python")
    print("   # Support/Resistance-Volatility interactions")
    print("   sr_cols = [col for col in features.columns if any(x in col for x in ['support', 'resistance', 'swing'])][:3]")
    print("   for sr_col in sr_cols:")
    print("       for vol_col in volatility_cols:")
    print("           if sr_col in features.columns and vol_col in features.columns:")
    print("               features[f'{sr_col}_{vol_col}_interaction'] = features[sr_col] * features[vol_col]")
    print("   ```")
    
    print("\n📊 5. FEATURE COUNTING:")
    print("   Method: EnhancedFeatureEngineer.create_comprehensive_features()")
    print("   Location: Lines 277-283")
    print("   Code:")
    print("   ```python")
    print("   feature_counts = {")
    print("       'sr_features': len([col for col in features.columns if any(sr in col for sr in ['support', 'resistance', 'pivot', 'swing'])]),")
    print("       # ... other categories ...")
    print("   }")
    print("   ```")
    
    print("\n🚀 6. CALL FLOW:")
    print("   ==============")
    print("   1. HMMRegimeDiscoveryStep._create_enhanced_features() [Line 776]")
    print("      ↓")
    print("   2. EnhancedFeatureEngineer.create_comprehensive_features() [Line 226]")
    print("      ↓")
    print("   3. EnhancedFeatureEngineer._add_sr_features() [Line 262]")
    print("      ↓")
    print("   4. EnhancedFeatureEngineer._calculate_sr_strength() [Line 425]")
    print("      ↓")
    print("   5. EnhancedFeatureEngineer._add_cross_category_interactions() [Line 618]")
    print("      ↓")
    print("   6. Feature counting and logging [Lines 277-283]")
    
    print("\n📈 7. FEATURES CREATED:")
    print("   ====================")
    print("   Base SR Features (20 total):")
    print("   - pivot_point: 1 feature")
    print("   - support_1, support_2, resistance_1, resistance_2: 4 features")
    print("   - distance_to_support, distance_to_resistance: 2 features")
    print("   - sr_strength: 1 feature")
    print("   - swing_high_10, swing_high_20, swing_high_50: 3 features")
    print("   - swing_low_10, swing_low_20, swing_low_50: 3 features")
    print("   - distance_to_swing_high_10/20/50: 3 features")
    print("   - distance_to_swing_low_10/20/50: 3 features")
    print("   ")
    print("   SR Interaction Features (27 total):")
    print("   - SR-Volatility interactions: 9 features")
    print("   - SR-Momentum interactions: 9 features")
    print("   - SR-Volume interactions: 9 features")
    print("   ")
    print("   TOTAL SR-RELATED FEATURES: 47")
    
    print("\n🎯 8. INTEGRATION POINTS:")
    print("   ======================")
    print("   - Called from: HMMRegimeDiscoveryStep._create_enhanced_features()")
    print("   - Used by: HMM parameter optimization")
    print("   - Used by: Feature importance analysis")
    print("   - Used by: Regime interpretation")
    print("   - Logged in: Feature count analysis")
    
    print("\n💡 9. KEY INSIGHTS:")
    print("   ================")
    print("   - SR features are created in the EnhancedFeatureEngineer class")
    print("   - They are part of the comprehensive feature set (391 total features)")
    print("   - SR features are created early in the feature engineering pipeline")
    print("   - They interact with volatility, momentum, and volume features")
    print("   - The strength calculation uses a 20-period rolling window by default")
    print("   - Swing analysis uses multiple timeframes (10, 20, 50 periods)")
    
    print("\n🔍 10. DEBUGGING TIPS:")
    print("   ===================")
    print("   - Check line 262: self._add_sr_features(features, df)")
    print("   - Check line 425: features['sr_strength'] = self._calculate_sr_strength(df)")
    print("   - Check line 618: SR-Volatility interactions")
    print("   - Check line 283: SR feature counting")
    print("   - Look for 'sr_features' in feature_counts dictionary")

if __name__ == "__main__":
    show_sr_code_locations()