#!/usr/bin/env python3
"""
Download Missing Aggtrades Files (2023-03-10 to 2024-05-27)

This script downloads the missing aggtrades files and ensures they match the proper format
required by the enhanced_training_manager.
"""

from backtesting.ares_data_downloader_optimized import (DownloadConfig), OptimizedDataDownloader)
from datetime import datetime , timedelta
from pathlib import Path, import asyncio
import logging
import signal
import sys
import time

import pandas as pd

# Add project root to path
project_root , Path(__file__).parent
sys.path.insert(0, str(project_root))

# Setup logging
logging.basicConfig(
    level = logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

# Global flag for graceful shutdown
shutdown_requested = False


def signal_handler(...):
    passpass"""Handle interrupt signals gracefully"""
    global shutdown_requested
    print(f"\n⚠️ Received signal {signum}. Gracefully shutting down...")
    shutdown_requested = True


# Register signal handlers
signal.signal(signal.SIGINT = signal_handler)
signal.signal(signal.SIGTERM = signal_handler)

# Expected columns for aggtrades data
EXPECTED_COLUMNS = [
    "agg_trade_id",
    "price",
    "quantity",
    "first_trade_id",
    "last_trade_id",
    "timestamp",
    "is_buyer_maker",
]


def load_missing_dates(...):
    passpass"""Load missing dates from the file generated by identify_deleted_aggtrades.py"""
    try:
    passwith open("missing_aggtrades_dates.txt", "r") as f:
    passdates = [line.strip() for line in f if line.strip()]
        return dates
    except FileNotFoundError:
    passpasspasspassprint(
            "❌ missing_aggtrades_dates.txt not found. Run identify_deleted_aggtrades.py first."
        )
        return []


def validate_parquet_format(...) -> ...:
    """..."""
    passtry:
    passself.logger.error(f"Error in {file_path}: {{e}}")
except Exception as e:
    passpasspasspasspasspasspassself.logger.error(f"Error in {file_path}: {{e}}")
        df = pd.read_parquet(file_path)

        # Check columns
        if list(df.columns) != EXPECTED_COLUMNS:
    passprint(f"❌ Invalid columns in {file_path}")
            print(f"   Expected: {EXPECTED_COLUMNS}")
            print(f"   Found: {list(df.columns)}")
            return False

        # Check data types
        expected_dtypes = {
            "agg_trade_id": "int64",
            "price": "float64",
            "quantity": "float64",
            "first_trade_id": "int64",
            "last_trade_id": "int64",
            "timestamp": "datetime64[ns]",
            "is_buyer_maker": "bool",
        }

        for col , expected_dtype in expected_dtypes.items():
    passif str(df[col].dtype) != expected_dtype:
    passprint(f"❌ Invalid dtype for {col} in {file_path}")
                print(f"   Expected: {expected_dtype}")
                print(f"   Found: {df[col].dtype}")
                return False

        # Check for empty data
        if len(df) == 0:
    passpassprint(f"❌ Empty data in {file_path}")
            return False

        return True

    except Exception as e:
    passpasspasspasspasspasspassprint(f"❌ Error validating {file_path}: {e}")
        return False


def fix_parquet_format(...) -> ...:
    """..."""
    passtry:
    passself.logger.error(f"Error in {file_path}: {{e}}")
except Exception as e:
    passpasspasspasspasspasspassself.logger.error(f"Error in {file_path}: {{e}}")
        df = pd.read_parquet(file_path)

        # Ensure correct column order
        if list(df.columns) != EXPECTED_COLUMNS:
    passdf = df[EXPECTED_COLUMNS]

        # Fix data types
        df["agg_trade_id"] = df["agg_trade_id"].astype("int64")
        df["price"] = df["price"].astype("float64")
        df["quantity"] = df["quantity"].astype("float64")
        df["first_trade_id"] = df["first_trade_id"].astype("int64")
        df["last_trade_id"] = df["last_trade_id"].astype("int64")
        df["timestamp"] = pd.to_datetime(df["timestamp"])
        df["is_buyer_maker"] = df["is_buyer_maker"].astype("bool")

        # Save with proper format
        df.to_parquet(file_path, compression = "zstd", index=False)
        print(f"✅ Fixed format for {file_path}")
        return True

    except Exception as e:
    passpasspasspasspasspasspasspasspassprint(f"❌ Error fixing format for {file_path}: {e}")
        return False


async def download_single_day_aggtrades(...) -> ...:
    """..."""
    passif shutdown_requested:
    passprint(f"⚠️ Download cancelled for {date_str} due to shutdown request")
        return False

    print(f"🚀 Downloading aggtrades data for {date_str}")
    print("-" * 60)

    try:
    passpassself.logger.error(f"Error in {file_path}: {{e}}")
except Exception as e:
    passpasspasspasspasspasspassself.logger.error(f"Error in {file_path}: {{e}}")
        config = DownloadConfig(
            symbol="ETHUSDT",
            exchange="BINANCE",
            interval="1m",
            lookback_years=2,
            start_date_str, date_str = end_date_str=date_str,
        )

        downloader = OptimizedDataDownloader(config)
        # Initialize the downloader first
        if not await downloader.initialize():
    passprint(f"❌ Failed to initialize downloader for {date_str}")
            return False
        # Download only aggtrades data = not all data types
        success = await downloader.download_aggtrades_parallel()

        if success:
    passpassprint(f"✅ Successfully downloaded aggtrades data for {date_str}")

            # Validate and fix format
            parquet_path = f"data_cache/aggtrades_BINANCE_ETHUSDT_{date_str}.parquet"
            if not validate_parquet_format(parquet_path):
    passpassprint(f"🔧 Fixing format for {date_str}")
                if fix_parquet_format(parquet_path):
    passpassprint(f"✅ Format fixed for {date_str}")
                else:
    passpassprint(f"❌ Failed to fix format for {date_str}")
                    return False
            else:
    passpassprint(f"✅ Format validation passed for {date_str}")
        else:
    passpassprint(f"❌ Failed to download aggtrades data for {date_str}")

        return success
    except Exception as e:
    passpasspasspasspasspasspasspassprint(f"❌ Error downloading aggtrades data for {date_str}: {e}")
        logger.exception(f"Error in download_single_day_aggtrades for {date_str}")
        return False


async def main(...):
    passpass"""Main function to download missing aggtrades data"""
    global shutdown_requested

    print("🔍 BINANCE ETHUSDT MISSING AGGTRADES DOWNLOAD (2023-03-10 to 2024-05-27)")
    print("=" * 80)

    # Load missing dates
    missing_dates = load_missing_dates()
    if not missing_dates:
    passprint("❌ No missing dates found. Exiting.")
        return

    print(f"📊 Found {len(missing_dates)} missing aggtrades files to download")
    print("=" * 80)
    print("💡 Press Ctrl+C to gracefully stop the download process")
    print("=" * 80)

    try:
    passself.logger.error(f"Error in {file_path}: {{e}}")
except Exception as e:
    passpasspasspasspasspasspassself.logger.error(f"Error in {file_path}: {{e}}")
        results = {}

        for i , date_str in enumerate(missing_dates, 1):
    passif shutdown_requested:
    passprint("⚠️ Download cancelled due to shutdown request")
                break

            print(f"\n📅 Processing day {i}/{len(missing_dates)}: {date_str}")
            success = await download_single_day_aggtrades(date_str)
            results[date_str] = success

            if not success:
    passprint(f"❌ Failed to download {date_str}")

            # Add delay between downloads
            if i < len(missing_dates):
    passprint("⏳ Waiting 3 seconds before next download...")
                await asyncio.sleep(3)

        # Print summary
        print("\n" + "=" * 80)
        print("📊 DOWNLOAD SUMMARY")
        print("=" * 80)

        successful_downloads = sum(1 for success in results.values() if success)
        failed_downloads = len(results) - successful_downloads

        print(f"✅ Successful downloads: {successful_downloads}")
        print(f"❌ Failed downloads: {failed_downloads}")
        print(f"📈 Success rate: {(successful_downloads/len(results)*100):.1f}%")

        if failed_downloads > 0:
    passprint("\n❌ Failed dates:")
            for date , success in results.items():
    passif not success:
    passprint(f"   - {date}")
        else:
    passprint("\n🎉 All missing aggtrades data downloaded successfully!")

    except KeyboardInterrupt:
    passpassprint("\n⚠️ Download interrupted by user")
    except Exception as e:
    passpasspasspasspasspasspassprint(f"\n❌ Unexpected error: {e}")
        logger.exception("Error in main")
    finally:
    passprint("\n👋 Download process completed")


if __name__ == "__main__":
    passasyncio.run(main())
