"""
Consensus Indicator System

This module provides a consensus-based system that only uses trading indicators
generated by multiple ML models, ensuring higher reliability and interpretability.

Key Features:
- Multi-model consensus validation
- Agreement threshold enforcement
- Confidence-weighted consensus
- Model reliability scoring
- Consensus stability monitoring
- Real-time consensus generation
"""

import numpy as np
import pandas as pd
import warnings
from typing import Any, Dict, List, Optional, Union, Tuple, Callable
import logging
import time
from datetime import datetime, timedelta
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
import json

# Core imports
from .ml_candle_pattern_indicators import MLIndicatorGenerator, IndicatorType, ModelType
from .model_comparison_pipeline import ModelComparisonPipeline, ConsensusMethod, ConsensusConfig
from .interpretability_analysis import InterpretabilityAnalyzer, InterpretabilityConfig

logger = logging.getLogger(__name__)


class ConsensusValidationMethod(Enum):
    """Methods for validating consensus indicators."""
    AGREEMENT_THRESHOLD = "agreement_threshold"
    CONFIDENCE_WEIGHTED = "confidence_weighted"
    PERFORMANCE_WEIGHTED = "performance_weighted"
    STABILITY_CHECK = "stability_check"
    CROSS_VALIDATION = "cross_validation"


class ConsensusReliabilityLevel(Enum):
    """Reliability levels for consensus indicators."""
    HIGH = "high"      # 3+ models agree with high confidence
    MEDIUM = "medium"  # 2+ models agree with medium confidence
    LOW = "low"        # 2+ models agree with low confidence
    UNRELIABLE = "unreliable"  # Insufficient agreement


@dataclass
class ConsensusSystemConfig:
    """Configuration for the consensus indicator system."""
    # Consensus requirements
    min_models_required: int = 2
    min_agreement_threshold: float = 0.6
    min_confidence_threshold: float = 0.7
    enable_reliability_scoring: bool = True
    
    # Validation methods
    validation_methods: List[ConsensusValidationMethod] = None
    enable_stability_monitoring: bool = True
    stability_window: int = 20
    stability_threshold: float = 0.8
    
    # Consensus generation
    consensus_method: ConsensusMethod = ConsensusMethod.CONFIDENCE_WEIGHTED
    enable_adaptive_thresholds: bool = True
    threshold_update_frequency: int = 100
    
    # Quality control
    enable_quality_control: bool = True
    max_indicator_volatility: float = 0.5
    min_consensus_strength: float = 0.3
    
    # Interpretability
    enable_consensus_interpretability: bool = True
    interpretability_config: Optional[InterpretabilityConfig] = None
    
    def __post_init__(self):
        if self.validation_methods is None:
            self.validation_methods = [
                ConsensusValidationMethod.AGREEMENT_THRESHOLD,
                ConsensusValidationMethod.CONFIDENCE_WEIGHTED,
                ConsensusValidationMethod.STABILITY_CHECK
            ]
        
        if self.interpretability_config is None:
            self.interpretability_config = InterpretabilityConfig(
                enable_consensus_analysis=True,
                consensus_threshold=self.min_agreement_threshold
            )


class ConsensusIndicatorSystem:
    """
    Consensus-based indicator system that only uses indicators generated by multiple models.
    
    This system ensures that trading indicators are only generated when multiple ML models
    agree, providing higher reliability and reducing false signals.
    """
    
    def __init__(self, config: Optional[ConsensusSystemConfig] = None):
        self.config = config or ConsensusSystemConfig()
        self.comparison_pipeline = None
        self.interpretability_analyzer = None
        self.consensus_indicators = {}
        self.model_reliability_scores = {}
        self.consensus_history = []
        self.quality_metrics = {}
        
        # Initialize components
        self._initialize_components()
        
        logger.info("🤝 Consensus Indicator System initialized")
    
    def _initialize_components(self):
        """Initialize system components."""
        # Initialize comparison pipeline
        consensus_config = ConsensusConfig(
            consensus_method=self.config.consensus_method,
            min_agreement_threshold=self.config.min_agreement_threshold,
            min_models_required=self.config.min_models_required,
            enable_interpretability=self.config.enable_consensus_interpretability
        )
        self.comparison_pipeline = ModelComparisonPipeline(consensus_config)
        
        # Initialize interpretability analyzer
        if self.config.enable_consensus_interpretability:
            self.interpretability_analyzer = InterpretabilityAnalyzer(self.config.interpretability_config)
        
        logger.info("✅ System components initialized")
    
    def train_consensus_system(self, data: pd.DataFrame, 
                             target_column: str = 'future_return',
                             symbol: str = 'BTCUSDT',
                             model_types: List[ModelType] = None) -> Dict[str, Any]:
        """
        Train the consensus system with multiple models.
        
        Args:
            data: Historical OHLCV data
            target_column: Target variable column name
            symbol: Trading symbol
            model_types: List of model types to train
            
        Returns:
            Training results with consensus analysis
        """
        if model_types is None:
            model_types = [ModelType.LIGHTGBM, ModelType.RANDOM_FOREST]
        
        logger.info(f"🔧 Training consensus system for {symbol} with {len(model_types)} models")
        start_time = time.time()
        
        # Train and compare models
        comparison_results = self.comparison_pipeline.train_and_compare_models(
            data, target_column, symbol, model_types
        )
        
        # Generate consensus indicators
        consensus_results = self._generate_consensus_indicators(data)
        
        # Analyze interpretability if enabled
        interpretability_results = {}
        if self.config.enable_consensus_interpretability and self.interpretability_analyzer:
            interpretability_results = self.interpretability_analyzer.analyze_consensus_interpretability(
                self.comparison_pipeline
            )
        
        # Calculate model reliability scores
        reliability_scores = self._calculate_model_reliability_scores(comparison_results)
        
        # Validate consensus quality
        quality_validation = self._validate_consensus_quality(consensus_results, data)
        
        # Compile training results
        training_results = {
            'symbol': symbol,
            'start_time': start_time,
            'end_time': time.time(),
            'total_time': time.time() - start_time,
            'comparison_results': comparison_results,
            'consensus_results': consensus_results,
            'interpretability_results': interpretability_results,
            'reliability_scores': reliability_scores,
            'quality_validation': quality_validation,
            'success': True
        }
        
        # Store consensus history
        self.consensus_history.append(training_results)
        
        logger.info(f"🎉 Consensus system training completed in {training_results['total_time']:.2f} seconds")
        return training_results
    
    def _generate_consensus_indicators(self, data: pd.DataFrame) -> Dict[str, Any]:
        """Generate consensus indicators from trained models."""
        if len(self.comparison_pipeline.models) < self.config.min_models_required:
            return {'error': f'Insufficient models for consensus (need {self.config.min_models_required})'}
        
        logger.info("🤝 Generating consensus indicators...")
        
        consensus_results = {
            'consensus_method': self.config.consensus_method.value,
            'models_used': [],
            'consensus_indicators': {},
            'reliability_levels': {},
            'agreement_scores': {},
            'confidence_scores': {}
        }
        
        # Collect indicators from all successful models
        model_indicators = {}
        model_confidences = {}
        model_performances = {}
        
        for model_name, model_result in self.comparison_pipeline.models.items():
            if model_result['success']:
                model_indicators[model_name] = model_result['indicators']
                model_confidences[model_name] = model_result['confidence']
                model_performances[model_name] = model_result['performance']
                consensus_results['models_used'].append(model_name)
        
        if len(model_indicators) < self.config.min_models_required:
            return {'error': 'Insufficient successful models for consensus'}
        
        # Generate consensus indicators
        consensus_indicators = self._create_consensus_indicators(
            model_indicators, model_confidences, model_performances
        )
        
        # Calculate reliability levels
        reliability_levels = self._calculate_reliability_levels(
            consensus_indicators, model_indicators, model_confidences
        )
        
        # Calculate agreement and confidence scores
        agreement_scores = self._calculate_agreement_scores(model_indicators)
        confidence_scores = self._calculate_consensus_confidence(consensus_indicators, model_indicators)
        
        # Apply quality control
        if self.config.enable_quality_control:
            consensus_indicators = self._apply_quality_control(consensus_indicators, data)
        
        consensus_results['consensus_indicators'] = consensus_indicators
        consensus_results['reliability_levels'] = reliability_levels
        consensus_results['agreement_scores'] = agreement_scores
        consensus_results['confidence_scores'] = confidence_scores
        
        # Store consensus indicators
        self.consensus_indicators = consensus_indicators
        
        logger.info(f"✅ Consensus indicators generated using {len(consensus_results['models_used'])} models")
        return consensus_results
    
    def _create_consensus_indicators(self, model_indicators: Dict[str, pd.Series], 
                                   model_confidences: Dict[str, float],
                                   model_performances: Dict[str, Dict[str, float]]) -> pd.Series:
        """Create consensus indicators based on the configured method."""
        if self.config.consensus_method == ConsensusMethod.MAJORITY_VOTE:
            return self._majority_vote_consensus(model_indicators)
        elif self.config.consensus_method == ConsensusMethod.CONFIDENCE_WEIGHTED:
            return self._confidence_weighted_consensus(model_indicators, model_confidences)
        elif self.config.consensus_method == ConsensusMethod.PERFORMANCE_WEIGHTED:
            return self._performance_weighted_consensus(model_indicators, model_performances)
        elif self.config.consensus_method == ConsensusMethod.AGREEMENT_THRESHOLD:
            return self._agreement_threshold_consensus(model_indicators)
        else:
            return self._confidence_weighted_consensus(model_indicators, model_confidences)
    
    def _majority_vote_consensus(self, model_indicators: Dict[str, pd.Series]) -> pd.Series:
        """Generate consensus using majority vote."""
        # Convert to binary signals
        binary_signals = {}
        for model_name, indicators in model_indicators.items():
            binary_signals[model_name] = np.where(indicators > 0.5, 1, 0)
        
        # Calculate majority vote
        signal_matrix = np.array(list(binary_signals.values()))
        majority_votes = np.mean(signal_matrix, axis=0)
        
        # Convert back to continuous indicators
        consensus_indicators = pd.Series(majority_votes, index=model_indicators[list(model_indicators.keys())[0]].index)
        
        return consensus_indicators
    
    def _confidence_weighted_consensus(self, model_indicators: Dict[str, pd.Series], 
                                     model_confidences: Dict[str, float]) -> pd.Series:
        """Generate consensus using confidence-weighted average."""
        # Normalize confidences
        total_confidence = sum(model_confidences.values())
        if total_confidence == 0:
            return self._majority_vote_consensus(model_indicators)
        
        # Calculate confidence-weighted average
        weighted_sum = None
        for model_name, indicators in model_indicators.items():
            weight = model_confidences[model_name] / total_confidence
            if weighted_sum is None:
                weighted_sum = indicators * weight
            else:
                weighted_sum += indicators * weight
        
        return weighted_sum
    
    def _performance_weighted_consensus(self, model_indicators: Dict[str, pd.Series], 
                                      model_performances: Dict[str, Dict[str, float]]) -> pd.Series:
        """Generate consensus using performance-weighted average."""
        # Calculate performance weights based on F1 scores
        performance_weights = {}
        for model_name, performance in model_performances.items():
            f1_score = performance.get('f1_score', 0)
            performance_weights[model_name] = max(f1_score, 0.1)  # Minimum weight
        
        total_weight = sum(performance_weights.values())
        if total_weight == 0:
            return self._majority_vote_consensus(model_indicators)
        
        # Calculate performance-weighted average
        weighted_sum = None
        for model_name, indicators in model_indicators.items():
            weight = performance_weights[model_name] / total_weight
            if weighted_sum is None:
                weighted_sum = indicators * weight
            else:
                weighted_sum += indicators * weight
        
        return weighted_sum
    
    def _agreement_threshold_consensus(self, model_indicators: Dict[str, pd.Series]) -> pd.Series:
        """Generate consensus only when models agree above threshold."""
        # Convert to binary signals
        binary_signals = {}
        for model_name, indicators in model_indicators.items():
            binary_signals[model_name] = np.where(indicators > 0.5, 1, 0)
        
        # Calculate agreement for each time point
        signal_matrix = np.array(list(binary_signals.values()))
        agreement_rates = np.mean(signal_matrix, axis=0)
        
        # Only use consensus when agreement is above threshold
        consensus_signals = np.where(
            agreement_rates >= self.config.min_agreement_threshold,
            agreement_rates,
            0.5  # Neutral when no agreement
        )
        
        consensus_indicators = pd.Series(consensus_signals, 
                                       index=model_indicators[list(model_indicators.keys())[0]].index)
        
        return consensus_indicators
    
    def _calculate_reliability_levels(self, consensus_indicators: pd.Series, 
                                    model_indicators: Dict[str, pd.Series],
                                    model_confidences: Dict[str, float]) -> pd.Series:
        """Calculate reliability levels for consensus indicators."""
        reliability_levels = []
        
        for i in range(len(consensus_indicators)):
            # Count models that agree with consensus
            consensus_value = consensus_indicators.iloc[i]
            agreeing_models = 0
            total_confidence = 0
            
            for model_name, indicators in model_indicators.items():
                model_value = indicators.iloc[i]
                model_confidence = model_confidences[model_name]
                
                # Check if model agrees (within threshold)
                if abs(model_value - consensus_value) <= 0.2:  # 20% tolerance
                    agreeing_models += 1
                    total_confidence += model_confidence
            
            # Determine reliability level
            if agreeing_models >= 3 and total_confidence >= 2.0:
                reliability_level = ConsensusReliabilityLevel.HIGH
            elif agreeing_models >= 2 and total_confidence >= 1.0:
                reliability_level = ConsensusReliabilityLevel.MEDIUM
            elif agreeing_models >= 2:
                reliability_level = ConsensusReliabilityLevel.LOW
            else:
                reliability_level = ConsensusReliabilityLevel.UNRELIABLE
            
            reliability_levels.append(reliability_level.value)
        
        return pd.Series(reliability_levels, index=consensus_indicators.index)
    
    def _calculate_agreement_scores(self, model_indicators: Dict[str, pd.Series]) -> Dict[str, float]:
        """Calculate agreement scores between models."""
        agreement_scores = {}
        model_names = list(model_indicators.keys())
        
        for i, model1 in enumerate(model_names):
            for j, model2 in enumerate(model_names):
                if i < j:  # Avoid duplicate pairs
                    indicators1 = model_indicators[model1]
                    indicators2 = model_indicators[model2]
                    
                    # Calculate correlation as agreement measure
                    correlation = indicators1.corr(indicators2)
                    agreement_scores[f"{model1}_vs_{model2}"] = correlation
        
        return agreement_scores
    
    def _calculate_consensus_confidence(self, consensus_indicators: pd.Series, 
                                      model_indicators: Dict[str, pd.Series]) -> pd.Series:
        """Calculate confidence scores for consensus indicators."""
        # Confidence based on agreement between models
        model_array = np.array(list(model_indicators.values()))
        model_std = np.std(model_array, axis=0)
        
        # Higher agreement (lower std) = higher confidence
        confidence = 1.0 / (1.0 + model_std)
        
        return pd.Series(confidence, index=consensus_indicators.index)
    
    def _apply_quality_control(self, consensus_indicators: pd.Series, data: pd.DataFrame) -> pd.Series:
        """Apply quality control to consensus indicators."""
        # Check for excessive volatility
        indicator_volatility = consensus_indicators.rolling(10).std()
        high_volatility_mask = indicator_volatility > self.config.max_indicator_volatility
        
        # Check for weak consensus
        weak_consensus_mask = np.abs(consensus_indicators - 0.5) < self.config.min_consensus_strength
        
        # Apply quality control
        quality_controlled = consensus_indicators.copy()
        quality_controlled[high_volatility_mask] = 0.5  # Neutral for high volatility
        quality_controlled[weak_consensus_mask] = 0.5   # Neutral for weak consensus
        
        return quality_controlled
    
    def _calculate_model_reliability_scores(self, comparison_results: Dict[str, Any]) -> Dict[str, float]:
        """Calculate reliability scores for each model."""
        reliability_scores = {}
        
        for model_name, model_result in comparison_results.get('model_results', {}).items():
            if model_result.get('success', False):
                performance = model_result.get('performance', {})
                confidence = model_result.get('confidence', 0)
                
                # Calculate reliability score
                f1_score = performance.get('f1_score', 0)
                accuracy = performance.get('accuracy', 0)
                consistency = performance.get('consistency', 0)
                
                reliability_score = (f1_score * 0.4 + accuracy * 0.3 + 
                                   consistency * 0.2 + confidence * 0.1)
                
                reliability_scores[model_name] = reliability_score
        
        # Store reliability scores
        self.model_reliability_scores = reliability_scores
        
        return reliability_scores
    
    def _validate_consensus_quality(self, consensus_results: Dict[str, Any], 
                                  data: pd.DataFrame) -> Dict[str, Any]:
        """Validate the quality of consensus indicators."""
        quality_validation = {
            'consensus_strength': 0.0,
            'model_agreement': 0.0,
            'indicator_stability': 0.0,
            'quality_score': 0.0,
            'validation_passed': False
        }
        
        try:
            consensus_indicators = consensus_results.get('consensus_indicators')
            if consensus_indicators is None:
                return quality_validation
            
            # Calculate consensus strength (how far from neutral)
            consensus_strength = np.mean(np.abs(consensus_indicators - 0.5))
            quality_validation['consensus_strength'] = consensus_strength
            
            # Calculate model agreement
            agreement_scores = consensus_results.get('agreement_scores', {})
            if agreement_scores:
                avg_agreement = np.mean(list(agreement_scores.values()))
                quality_validation['model_agreement'] = avg_agreement
            
            # Calculate indicator stability
            if len(consensus_indicators) > 10:
                rolling_std = consensus_indicators.rolling(10).std()
                stability = 1.0 - np.mean(rolling_std)  # Higher stability = lower std
                quality_validation['indicator_stability'] = stability
            
            # Calculate overall quality score
            quality_score = (
                consensus_strength * 0.4 +
                quality_validation['model_agreement'] * 0.3 +
                quality_validation['indicator_stability'] * 0.3
            )
            quality_validation['quality_score'] = quality_score
            
            # Check if validation passes
            quality_validation['validation_passed'] = (
                consensus_strength >= 0.1 and
                quality_validation['model_agreement'] >= 0.3 and
                quality_validation['indicator_stability'] >= 0.5
            )
            
        except Exception as e:
            logger.warning(f"Quality validation failed: {e}")
            quality_validation['error'] = str(e)
        
        return quality_validation
    
    def generate_consensus_indicators(self, data: pd.DataFrame) -> Dict[str, Any]:
        """
        Generate consensus indicators for new data.
        
        Args:
            data: New OHLCV data for indicator generation
            
        Returns:
            Consensus indicators with reliability information
        """
        if not self.consensus_indicators:
            return {'error': 'Consensus system not trained'}
        
        logger.info("🔮 Generating consensus indicators for new data")
        
        # Generate indicators from all models
        model_indicators = {}
        for model_name, model_result in self.comparison_pipeline.models.items():
            if model_result['success']:
                generator = model_result['generator']
                indicators = generator._generate_feature(data)
                model_indicators[model_name] = indicators
        
        if len(model_indicators) < self.config.min_models_required:
            return {'error': f'Insufficient models for consensus (need {self.config.min_models_required})'}
        
        # Generate consensus indicators
        consensus_indicators = self._create_consensus_indicators(
            model_indicators, 
            self.model_reliability_scores,  # Use as confidences
            self.model_reliability_scores   # Use as performances
        )
        
        # Calculate reliability levels
        reliability_levels = self._calculate_reliability_levels(
            consensus_indicators, model_indicators, self.model_reliability_scores
        )
        
        # Apply quality control
        if self.config.enable_quality_control:
            consensus_indicators = self._apply_quality_control(consensus_indicators, data)
        
        # Calculate agreement scores
        agreement_scores = self._calculate_agreement_scores(model_indicators)
        
        # Calculate confidence scores
        confidence_scores = self._calculate_consensus_confidence(consensus_indicators, model_indicators)
        
        return {
            'consensus_indicators': consensus_indicators,
            'reliability_levels': reliability_levels,
            'agreement_scores': agreement_scores,
            'confidence_scores': confidence_scores,
            'models_used': list(model_indicators.keys()),
            'consensus_method': self.config.consensus_method.value
        }
    
    def get_consensus_summary(self) -> Dict[str, Any]:
        """Get summary of the consensus system."""
        summary = {
            'total_models': len(self.comparison_pipeline.models),
            'successful_models': len([m for m in self.comparison_pipeline.models.values() if m['success']]),
            'consensus_method': self.config.consensus_method.value,
            'min_models_required': self.config.min_models_required,
            'min_agreement_threshold': self.config.min_agreement_threshold,
            'model_reliability_scores': self.model_reliability_scores,
            'consensus_history_count': len(self.consensus_history),
            'quality_metrics': self.quality_metrics
        }
        
        return summary
    
    def save_consensus_system(self, save_path: str):
        """Save the consensus system to disk."""
        save_dir = Path(save_path)
        save_dir.mkdir(parents=True, exist_ok=True)
        
        # Save system configuration
        config_path = save_dir / 'consensus_config.json'
        with open(config_path, 'w') as f:
            json.dump(self.config.__dict__, f, default=str, indent=2)
        
        # Save consensus history
        history_path = save_dir / 'consensus_history.json'
        with open(history_path, 'w') as f:
            json.dump(self.consensus_history, f, default=str, indent=2)
        
        # Save model reliability scores
        reliability_path = save_dir / 'model_reliability.json'
        with open(reliability_path, 'w') as f:
            json.dump(self.model_reliability_scores, f, indent=2)
        
        logger.info(f"💾 Consensus system saved to {save_path}")


def create_consensus_system(config: Optional[ConsensusSystemConfig] = None) -> ConsensusIndicatorSystem:
    """Create a consensus indicator system with specified configuration."""
    return ConsensusIndicatorSystem(config)


def test_consensus_system():
    """Test function for the consensus indicator system."""
    print("🧪 Testing Consensus Indicator System...")
    
    # Create sample data
    np.random.seed(42)
    n_samples = 1000
    
    # Generate realistic OHLCV data
    base_price = 100.0
    returns = np.random.normal(0, 0.02, n_samples)
    prices = base_price * np.exp(np.cumsum(returns))
    
    data = pd.DataFrame({
        'open': prices * (1 + np.random.normal(0, 0.005, n_samples)),
        'high': prices * (1 + np.abs(np.random.normal(0, 0.01, n_samples))),
        'low': prices * (1 - np.abs(np.random.normal(0, 0.01, n_samples))),
        'close': prices,
        'volume': np.random.lognormal(10, 1, n_samples)
    }, index=pd.date_range('2020-01-01', periods=n_samples, freq='1min'))
    
    # Ensure OHLC constraints
    data['high'] = np.maximum(data['high'], np.maximum(data['open'], data['close']))
    data['low'] = np.minimum(data['low'], np.minimum(data['open'], data['close']))
    
    # Create consensus system
    config = ConsensusSystemConfig(
        min_models_required=2,
        min_agreement_threshold=0.6,
        enable_quality_control=True,
        enable_consensus_interpretability=True
    )
    system = create_consensus_system(config)
    
    # Train consensus system
    print("🔧 Training consensus system...")
    training_results = system.train_consensus_system(
        data, 
        symbol='BTCUSDT',
        model_types=[ModelType.LIGHTGBM, ModelType.RANDOM_FOREST]
    )
    
    # Display training results
    print("\n📊 Consensus System Training Results:")
    print(f"   Training time: {training_results['total_time']:.2f} seconds")
    print(f"   Models trained: {len(training_results['comparison_results']['model_results'])}")
    
    if 'consensus_results' in training_results:
        consensus_results = training_results['consensus_results']
        print(f"   Consensus method: {consensus_results.get('consensus_method', 'N/A')}")
        print(f"   Models used: {len(consensus_results.get('models_used', []))}")
        
        if 'consensus_indicators' in consensus_results:
            indicators = consensus_results['consensus_indicators']
            print(f"   Consensus indicators generated: {len(indicators)}")
            print(f"   Mean: {indicators.mean():.4f}")
            print(f"   Std: {indicators.std():.4f}")
    
    # Generate consensus indicators for new data
    print("\n🔮 Generating consensus indicators for new data...")
    new_data = data.iloc[-100:]  # Use last 100 samples as new data
    consensus_indicators = system.generate_consensus_indicators(new_data)
    
    if 'error' not in consensus_indicators:
        print(f"   Consensus indicators: {len(consensus_indicators['consensus_indicators'])}")
        print(f"   Models used: {len(consensus_indicators['models_used'])}")
        print(f"   Reliability levels: {consensus_indicators['reliability_levels'].value_counts().to_dict()}")
    else:
        print(f"   Error: {consensus_indicators['error']}")
    
    # Get system summary
    summary = system.get_consensus_summary()
    print(f"\n📈 System Summary:")
    print(f"   Total models: {summary['total_models']}")
    print(f"   Successful models: {summary['successful_models']}")
    print(f"   Consensus method: {summary['consensus_method']}")
    print(f"   Min models required: {summary['min_models_required']}")
    
    print("\n🎉 Consensus Indicator System test completed successfully!")
    return system, training_results


if __name__ == "__main__":
    test_consensus_system()