"""
Trading ML Integration - Connects SR quality prediction to trading ML models.

This module shows how the enhanced SR quality data from weight optimization
is used to train ML models for actual trading decisions.
"""

import pandas as pd
import numpy as np
from typing import Dict, List, Any, Tuple, Optional, Union
from dataclasses import dataclass, field
from datetime import datetime, timedelta
import logging
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression, Ridge, ElasticNet
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split, TimeSeriesSplit, cross_val_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import joblib
import warnings
warnings.filterwarnings('ignore')

from ..logger import system_logger
from .sr_backtesting_engine import SRBacktestingEngine, BacktestResult, SRLevel
from .predictive_sr_engine import PredictiveSREngine, SRPrediction

@dataclass
class TradingMLConfig:
    """Configuration for trading ML models."""
    # Model types
    classification_model: str = 'random_forest'  # 'random_forest', 'logistic_regression', 'gradient_boosting'
    regression_model: str = 'ridge'  # 'ridge', 'elastic_net', 'random_forest'
    
    # Feature engineering
    include_sr_quality: bool = True
    include_momentum: bool = True
    include_volatility: bool = True
    include_volume: bool = True
    include_market_regime: bool = True
    
    # Trading parameters
    quality_threshold: float = 0.7  # Minimum SR quality for trading
    confidence_threshold: float = 0.8  # Minimum confidence for trading
    prediction_horizon: int = 30  # Days ahead to predict
    
    # Model training
    test_size: float = 0.2
    random_state: int = 42
    cross_validation_folds: int = 5

@dataclass
class TradingSignal:
    """Trading signal generated by ML models."""
    symbol: str
    signal_type: str  # 'buy', 'sell', 'hold'
    confidence: float
    sr_quality: float
    momentum_score: float
    volatility_score: float
    volume_score: float
    market_regime: str
    prediction_horizon: int
    expected_return: float
    risk_score: float
    timestamp: datetime

class TradingMLIntegration:
    """Integrates SR quality prediction with trading ML models."""
    
    def __init__(self, config: Optional[TradingMLConfig] = None):
        self.config = config or TradingMLConfig()
        self.logger = system_logger.getChild('TradingMLIntegration')
        
        # Core components
        self.predictive_engine: Optional[PredictiveSREngine] = None
        self.backtesting_engine: Optional[SRBacktestingEngine] = None
        
        # ML Models
        self.classification_model: Optional[Any] = None
        self.regression_model: Optional[Any] = None
        self.feature_scaler: Optional[StandardScaler] = None
        self.label_encoder: Optional[LabelEncoder] = None
        
        # Training data
        self.training_data: pd.DataFrame = pd.DataFrame()
        self.feature_importance: Dict[str, float] = {}
        self.model_performance: Dict[str, float] = {}
        
        # Trading signals
        self.trading_signals: List[TradingSignal] = []
        
    def prepare_enhanced_training_data(self, market_data: pd.DataFrame, 
                                     sr_levels: List[SRLevel],
                                     historical_performance: pd.DataFrame) -> pd.DataFrame:
        """Prepare enhanced training data with SR quality predictions."""
        try:
            self.logger.info(f"Preparing enhanced training data with {len(sr_levels)} SR levels")
            
            # Step 1: Get SR quality predictions
            if not self.predictive_engine:
                from .predictive_sr_engine import get_predictive_sr_engine, PredictiveConfig
                predictive_config = PredictiveConfig(
                    model_type='ensemble',
                    include_market_context=True,
                    include_volatility_features=True,
                    include_volume_features=True
                )
                self.predictive_engine = get_predictive_sr_engine(predictive_config)
                
                # Train the predictive engine
                training_result = self.predictive_engine.train_predictive_model(
                    market_data, sr_levels, optimize_weights=True
                )
                
                if training_result.get('status') != 'success':
                    raise ValueError("Failed to train predictive engine")
            
            # Step 2: Get SR quality predictions for each level
            sr_quality_predictions = []
            for sr_level in sr_levels:
                try:
                    prediction = self.predictive_engine.predict_sr_quality(
                        sr_level, market_data, self.config.prediction_horizon
                    )
                    sr_quality_predictions.append({
                        'symbol': sr_level.symbol,
                        'price': sr_level.price,
                        'level_type': sr_level.level_type,
                        'sr_quality': prediction.predicted_quality,
                        'sr_confidence': prediction.confidence,
                        'key_factors': prediction.key_factors,
                        'market_context': prediction.market_context
                    })
                except Exception as e:
                    self.logger.warning(f"Failed to predict quality for {sr_level.price}: {e}")
                    continue
            
            # Step 3: Create enhanced training dataset
            enhanced_data = []
            
            for i, row in historical_performance.iterrows():
                # Find corresponding SR quality prediction
                sr_quality_data = None
                for sr_pred in sr_quality_predictions:
                    if (sr_pred['symbol'] == row.get('symbol', '') and 
                        abs(sr_pred['price'] - row.get('price', 0)) < 0.01):
                        sr_quality_data = sr_pred
                        break
                
                if sr_quality_data is None:
                    continue  # Skip if no SR quality data
                
                # Extract market features
                market_features = self._extract_market_features(row, market_data)
                
                # Create enhanced training sample
                enhanced_sample = {
                    # Target variables (what we want to predict)
                    'future_return': row.get('future_return', 0.0),
                    'trade_success': 1 if row.get('future_return', 0) > 0 else 0,
                    'risk_level': row.get('risk_level', 0.0),
                    
                    # Enhanced SR features (from weight optimization)
                    'sr_quality': sr_quality_data['sr_quality'],
                    'sr_confidence': sr_quality_data['sr_confidence'],
                    'sr_level_type': sr_quality_data['level_type'],
                    
                    # Market context features
                    'momentum_score': market_features.get('momentum_score', 0.0),
                    'volatility_score': market_features.get('volatility_score', 0.0),
                    'volume_score': market_features.get('volume_score', 0.0),
                    'market_regime': market_features.get('market_regime', 'neutral'),
                    
                    # Combined features
                    'sr_momentum_interaction': sr_quality_data['sr_quality'] * market_features.get('momentum_score', 0.0),
                    'sr_volatility_interaction': sr_quality_data['sr_quality'] * market_features.get('volatility_score', 0.0),
                    'sr_volume_interaction': sr_quality_data['sr_quality'] * market_features.get('volume_score', 0.0),
                    
                    # Time features
                    'time_of_day': row.get('time_of_day', 12),
                    'day_of_week': row.get('day_of_week', 0),
                    'month': row.get('month', 1),
                    
                    # Additional context
                    'symbol': row.get('symbol', ''),
                    'timestamp': row.get('timestamp', datetime.now())
                }
                
                enhanced_data.append(enhanced_sample)
            
            # Convert to DataFrame
            enhanced_df = pd.DataFrame(enhanced_data)
            
            self.logger.info(f"Created enhanced training dataset with {len(enhanced_df)} samples")
            self.logger.info(f"Features: {list(enhanced_df.columns)}")
            
            return enhanced_df
            
        except Exception as e:
            self.logger.error(f"Failed to prepare enhanced training data: {e}")
            return pd.DataFrame()
    
    def _extract_market_features(self, row: pd.Series, market_data: pd.DataFrame) -> Dict[str, Any]:
        """Extract market features for a given row."""
        try:
            timestamp = row.get('timestamp', datetime.now())
            
            # Find corresponding market data
            market_row = market_data[market_data['date'] <= timestamp].iloc[-1] if len(market_data) > 0 else None
            
            if market_row is None:
                return {
                    'momentum_score': 0.0,
                    'volatility_score': 0.0,
                    'volume_score': 0.0,
                    'market_regime': 'neutral'
                }
            
            # Calculate momentum score
            momentum_score = self._calculate_momentum_score(market_data, timestamp)
            
            # Calculate volatility score
            volatility_score = self._calculate_volatility_score(market_data, timestamp)
            
            # Calculate volume score
            volume_score = self._calculate_volume_score(market_data, timestamp)
            
            # Determine market regime
            market_regime = self._determine_market_regime(momentum_score, volatility_score, volume_score)
            
            return {
                'momentum_score': momentum_score,
                'volatility_score': volatility_score,
                'volume_score': volume_score,
                'market_regime': market_regime
            }
            
        except Exception as e:
            self.logger.warning(f"Market feature extraction failed: {e}")
            return {
                'momentum_score': 0.0,
                'volatility_score': 0.0,
                'volume_score': 0.0,
                'market_regime': 'neutral'
            }
    
    def _calculate_momentum_score(self, market_data: pd.DataFrame, timestamp: datetime) -> float:
        """Calculate momentum score."""
        try:
            # Get recent data
            recent_data = market_data[market_data['date'] <= timestamp].tail(20)
            
            if len(recent_data) < 10:
                return 0.0
            
            # Calculate price momentum
            price_change = (recent_data['close'].iloc[-1] / recent_data['close'].iloc[0] - 1) * 100
            
            # Calculate moving average momentum
            sma_short = recent_data['close'].rolling(5).mean()
            sma_long = recent_data['close'].rolling(15).mean()
            ma_momentum = (sma_short.iloc[-1] / sma_long.iloc[-1] - 1) * 100
            
            # Combine momentum indicators
            momentum_score = (price_change + ma_momentum) / 2
            
            # Normalize to 0-1 range
            return np.clip(momentum_score / 10, -1, 1)  # Assume 10% is max momentum
            
        except Exception as e:
            self.logger.warning(f"Momentum calculation failed: {e}")
            return 0.0
    
    def _calculate_volatility_score(self, market_data: pd.DataFrame, timestamp: datetime) -> float:
        """Calculate volatility score."""
        try:
            # Get recent data
            recent_data = market_data[market_data['date'] <= timestamp].tail(20)
            
            if len(recent_data) < 10:
                return 0.0
            
            # Calculate returns
            returns = recent_data['close'].pct_change().dropna()
            
            # Calculate volatility
            volatility = returns.std() * np.sqrt(252)  # Annualized
            
            # Normalize to 0-1 range (assume 50% is max volatility)
            volatility_score = np.clip(volatility / 0.5, 0, 1)
            
            return volatility_score
            
        except Exception as e:
            self.logger.warning(f"Volatility calculation failed: {e}")
            return 0.0
    
    def _calculate_volume_score(self, market_data: pd.DataFrame, timestamp: datetime) -> float:
        """Calculate volume score."""
        try:
            # Get recent data
            recent_data = market_data[market_data['date'] <= timestamp].tail(20)
            
            if len(recent_data) < 10 or 'volume' not in recent_data.columns:
                return 0.0
            
            # Calculate volume trend
            recent_volume = recent_data['volume'].tail(5).mean()
            historical_volume = recent_data['volume'].mean()
            
            volume_ratio = recent_volume / historical_volume if historical_volume > 0 else 1.0
            
            # Normalize to 0-1 range
            volume_score = np.clip(volume_ratio, 0, 2) / 2  # Assume 2x is max volume
            
            return volume_score
            
        except Exception as e:
            self.logger.warning(f"Volume calculation failed: {e}")
            return 0.0
    
    def _determine_market_regime(self, momentum: float, volatility: float, volume: float) -> str:
        """Determine market regime based on features."""
        try:
            if momentum > 0.3 and volatility < 0.3:
                return 'bull_low_vol'
            elif momentum > 0.3 and volatility > 0.7:
                return 'bull_high_vol'
            elif momentum < -0.3 and volatility < 0.3:
                return 'bear_low_vol'
            elif momentum < -0.3 and volatility > 0.7:
                return 'bear_high_vol'
            elif volatility > 0.7:
                return 'high_volatility'
            elif volume > 1.5:
                return 'high_volume'
            else:
                return 'neutral'
                
        except Exception as e:
            self.logger.warning(f"Market regime determination failed: {e}")
            return 'neutral'
    
    def train_trading_models(self, enhanced_data: pd.DataFrame) -> Dict[str, Any]:
        """Train ML models for trading decisions using enhanced data."""
        try:
            if len(enhanced_data) == 0:
                return {'status': 'no_data'}
            
            self.logger.info(f"Training trading models with {len(enhanced_data)} enhanced samples")
            
            # Prepare features and targets
            feature_columns = [
                'sr_quality', 'sr_confidence', 'momentum_score', 'volatility_score', 
                'volume_score', 'sr_momentum_interaction', 'sr_volatility_interaction', 
                'sr_volume_interaction', 'time_of_day', 'day_of_week', 'month'
            ]
            
            # Add market regime as encoded feature
            if 'market_regime' in enhanced_data.columns:
                self.label_encoder = LabelEncoder()
                enhanced_data['market_regime_encoded'] = self.label_encoder.fit_transform(enhanced_data['market_regime'])
                feature_columns.append('market_regime_encoded')
            
            X = enhanced_data[feature_columns].fillna(0)
            y_classification = enhanced_data['trade_success']
            y_regression = enhanced_data['future_return']
            
            # Scale features
            self.feature_scaler = StandardScaler()
            X_scaled = self.feature_scaler.fit_transform(X)
            
            # Split data
            X_train, X_test, y_train_class, y_test_class = train_test_split(
                X_scaled, y_classification, test_size=self.config.test_size, 
                random_state=self.config.random_state, stratify=y_classification
            )
            
            _, _, y_train_reg, y_test_reg = train_test_split(
                X_scaled, y_regression, test_size=self.config.test_size, 
                random_state=self.config.random_state
            )
            
            # Train classification model
            classification_result = self._train_classification_model(X_train, y_train_class, X_test, y_test_class)
            
            # Train regression model
            regression_result = self._train_regression_model(X_train, y_train_reg, X_test, y_test_reg)
            
            # Store training data
            self.training_data = enhanced_data
            
            # Calculate feature importance
            self._calculate_feature_importance(X.columns)
            
            training_result = {
                'status': 'success',
                'training_samples': len(enhanced_data),
                'classification_performance': classification_result,
                'regression_performance': regression_result,
                'feature_importance': self.feature_importance
            }
            
            self.logger.info(f"Trading models trained successfully")
            self.logger.info(f"Classification accuracy: {classification_result.get('accuracy', 0.0):.3f}")
            self.logger.info(f"Regression R²: {regression_result.get('r2_score', 0.0):.3f}")
            
            return training_result
            
        except Exception as e:
            self.logger.error(f"Trading model training failed: {e}")
            return {'status': 'failed', 'error': str(e)}
    
    def _train_classification_model(self, X_train: np.ndarray, y_train: np.ndarray, 
                                  X_test: np.ndarray, y_test: np.ndarray) -> Dict[str, float]:
        """Train classification model for trade success prediction."""
        try:
            if self.config.classification_model == 'random_forest':
                model = RandomForestClassifier(
                    n_estimators=100,
                    max_depth=10,
                    random_state=self.config.random_state
                )
            elif self.config.classification_model == 'logistic_regression':
                model = LogisticRegression(
                    random_state=self.config.random_state,
                    max_iter=1000
                )
            elif self.config.classification_model == 'gradient_boosting':
                model = GradientBoostingClassifier(
                    n_estimators=100,
                    learning_rate=0.1,
                    random_state=self.config.random_state
                )
            else:
                model = RandomForestClassifier(random_state=self.config.random_state)
            
            # Train model
            model.fit(X_train, y_train)
            self.classification_model = model
            
            # Make predictions
            y_pred = model.predict(X_test)
            y_pred_proba = model.predict_proba(X_test)[:, 1]
            
            # Calculate metrics
            accuracy = accuracy_score(y_test, y_pred)
            precision = precision_score(y_test, y_pred)
            recall = recall_score(y_test, y_pred)
            f1 = f1_score(y_test, y_pred)
            roc_auc = roc_auc_score(y_test, y_pred_proba)
            
            # Cross-validation
            cv_scores = cross_val_score(model, X_train, y_train, cv=self.config.cross_validation_folds)
            
            return {
                'accuracy': accuracy,
                'precision': precision,
                'recall': recall,
                'f1_score': f1,
                'roc_auc': roc_auc,
                'cv_mean': cv_scores.mean(),
                'cv_std': cv_scores.std()
            }
            
        except Exception as e:
            self.logger.error(f"Classification model training failed: {e}")
            return {}
    
    def _train_regression_model(self, X_train: np.ndarray, y_train: np.ndarray, 
                              X_test: np.ndarray, y_test: np.ndarray) -> Dict[str, float]:
        """Train regression model for return prediction."""
        try:
            if self.config.regression_model == 'ridge':
                model = Ridge(alpha=1.0)
            elif self.config.regression_model == 'elastic_net':
                model = ElasticNet(alpha=0.1, l1_ratio=0.5)
            elif self.config.regression_model == 'random_forest':
                model = RandomForestRegressor(
                    n_estimators=100,
                    max_depth=10,
                    random_state=self.config.random_state
                )
            else:
                model = Ridge(alpha=1.0)
            
            # Train model
            model.fit(X_train, y_train)
            self.regression_model = model
            
            # Make predictions
            y_pred = model.predict(X_test)
            
            # Calculate metrics
            from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
            r2 = r2_score(y_test, y_pred)
            mse = mean_squared_error(y_test, y_pred)
            mae = mean_absolute_error(y_test, y_pred)
            
            # Cross-validation
            cv_scores = cross_val_score(model, X_train, y_train, cv=self.config.cross_validation_folds)
            
            return {
                'r2_score': r2,
                'mse': mse,
                'mae': mae,
                'cv_mean': cv_scores.mean(),
                'cv_std': cv_scores.std()
            }
            
        except Exception as e:
            self.logger.error(f"Regression model training failed: {e}")
            return {}
    
    def _calculate_feature_importance(self, feature_names: List[str]) -> None:
        """Calculate feature importance from trained models."""
        try:
            importance_dict = {}
            
            # Classification model importance
            if self.classification_model and hasattr(self.classification_model, 'feature_importances_'):
                class_importance = self.classification_model.feature_importances_
                for i, feature in enumerate(feature_names):
                    if i < len(class_importance):
                        importance_dict[f"{feature}_classification"] = class_importance[i]
            
            # Regression model importance
            if self.regression_model and hasattr(self.regression_model, 'feature_importances_'):
                reg_importance = self.regression_model.feature_importances_
                for i, feature in enumerate(feature_names):
                    if i < len(reg_importance):
                        importance_dict[f"{feature}_regression"] = reg_importance[i]
            
            self.feature_importance = importance_dict
            
        except Exception as e:
            self.logger.warning(f"Feature importance calculation failed: {e}")
    
    def generate_trading_signals(self, current_market_data: pd.DataFrame, 
                               current_sr_levels: List[SRLevel]) -> List[TradingSignal]:
        """Generate trading signals using trained models."""
        try:
            if self.classification_model is None or self.regression_model is None:
                raise ValueError("Models not trained. Call train_trading_models first.")
            
            signals = []
            
            for sr_level in current_sr_levels:
                try:
                    # Get SR quality prediction
                    if self.predictive_engine:
                        sr_prediction = self.predictive_engine.predict_sr_quality(
                            sr_level, current_market_data, self.config.prediction_horizon
                        )
                        sr_quality = sr_prediction.predicted_quality
                        sr_confidence = sr_prediction.confidence
                    else:
                        sr_quality = 0.5  # Default
                        sr_confidence = 0.5
                    
                    # Skip if quality/confidence too low
                    if (sr_quality < self.config.quality_threshold or 
                        sr_confidence < self.config.confidence_threshold):
                        continue
                    
                    # Extract market features
                    market_features = self._extract_current_market_features(current_market_data)
                    
                    # Prepare feature vector
                    features = np.array([
                        sr_quality,
                        sr_confidence,
                        market_features['momentum_score'],
                        market_features['volatility_score'],
                        market_features['volume_score'],
                        sr_quality * market_features['momentum_score'],
                        sr_quality * market_features['volatility_score'],
                        sr_quality * market_features['volume_score'],
                        datetime.now().hour,
                        datetime.now().weekday(),
                        datetime.now().month,
                        self.label_encoder.transform([market_features['market_regime']])[0] if self.label_encoder else 0
                    ]).reshape(1, -1)
                    
                    # Scale features
                    features_scaled = self.feature_scaler.transform(features)
                    
                    # Make predictions
                    trade_success_prob = self.classification_model.predict_proba(features_scaled)[0, 1]
                    expected_return = self.regression_model.predict(features_scaled)[0]
                    
                    # Determine signal type
                    if trade_success_prob > 0.7 and expected_return > 0.02:
                        signal_type = 'buy'
                    elif trade_success_prob > 0.7 and expected_return < -0.02:
                        signal_type = 'sell'
                    else:
                        signal_type = 'hold'
                    
                    # Create trading signal
                    signal = TradingSignal(
                        symbol=sr_level.symbol,
                        signal_type=signal_type,
                        confidence=trade_success_prob,
                        sr_quality=sr_quality,
                        momentum_score=market_features['momentum_score'],
                        volatility_score=market_features['volatility_score'],
                        volume_score=market_features['volume_score'],
                        market_regime=market_features['market_regime'],
                        prediction_horizon=self.config.prediction_horizon,
                        expected_return=expected_return,
                        risk_score=1.0 - sr_confidence,
                        timestamp=datetime.now()
                    )
                    
                    signals.append(signal)
                    
                except Exception as e:
                    self.logger.warning(f"Failed to generate signal for {sr_level.price}: {e}")
                    continue
            
            # Sort by confidence
            signals.sort(key=lambda x: x.confidence, reverse=True)
            
            self.trading_signals = signals
            self.logger.info(f"Generated {len(signals)} trading signals")
            
            return signals
            
        except Exception as e:
            self.logger.error(f"Trading signal generation failed: {e}")
            return []
    
    def _extract_current_market_features(self, market_data: pd.DataFrame) -> Dict[str, Any]:
        """Extract current market features."""
        try:
            if len(market_data) == 0:
                return {
                    'momentum_score': 0.0,
                    'volatility_score': 0.0,
                    'volume_score': 0.0,
                    'market_regime': 'neutral'
                }
            
            # Use most recent data
            recent_data = market_data.tail(20)
            
            # Calculate features
            momentum_score = self._calculate_momentum_score(market_data, datetime.now())
            volatility_score = self._calculate_volatility_score(market_data, datetime.now())
            volume_score = self._calculate_volume_score(market_data, datetime.now())
            market_regime = self._determine_market_regime(momentum_score, volatility_score, volume_score)
            
            return {
                'momentum_score': momentum_score,
                'volatility_score': volatility_score,
                'volume_score': volume_score,
                'market_regime': market_regime
            }
            
        except Exception as e:
            self.logger.warning(f"Current market feature extraction failed: {e}")
            return {
                'momentum_score': 0.0,
                'volatility_score': 0.0,
                'volume_score': 0.0,
                'market_regime': 'neutral'
            }
    
    def get_trading_summary(self) -> Dict[str, Any]:
        """Get summary of trading model performance and signals."""
        return {
            'total_signals': len(self.trading_signals),
            'buy_signals': len([s for s in self.trading_signals if s.signal_type == 'buy']),
            'sell_signals': len([s for s in self.trading_signals if s.signal_type == 'sell']),
            'hold_signals': len([s for s in self.trading_signals if s.signal_type == 'hold']),
            'avg_confidence': np.mean([s.confidence for s in self.trading_signals]) if self.trading_signals else 0.0,
            'avg_expected_return': np.mean([s.expected_return for s in self.trading_signals]) if self.trading_signals else 0.0,
            'feature_importance': self.feature_importance,
            'model_performance': self.model_performance
        }

def get_trading_ml_integration(config: Optional[TradingMLConfig] = None) -> TradingMLIntegration:
    """Get a trading ML integration instance."""
    return TradingMLIntegration(config)