"""Causal soft cluster/path residual utilities.

This module contains the representation pieces used by the long-only
conditional path experiment.  It deliberately does not fit a production
model: cluster discovery and feature selection are performed by the runner on
the training partition of each chronological fold.

The representation is built from frozen signed path/family contributions.  A
row's membership in a cluster is the absolute contribution mass assigned to
that cluster, normalised by the represented mass.  The residual target for a
cluster is therefore ``membership * (realised_net - base_anchor)``.  This is a
soft, economically interpretable target rather than a raw leaf-ID feature.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Mapping, Sequence

import numpy as np
import pandas as pd


EPS = 1e-12


@dataclass(frozen=True)
class ClusterContract:
    """Fold-local, serialisable cluster membership contract."""

    cluster_id: str
    family_fields: tuple[str, ...]
    family_indices: tuple[int, ...]
    centroid_distance: float

    def to_dict(self) -> dict[str, object]:
        return {
            "cluster_id": self.cluster_id,
            "family_fields": list(self.family_fields),
            "family_indices": list(self.family_indices),
            "centroid_distance": float(self.centroid_distance),
        }


def select_oof_path_rows(
    path_frame: pd.DataFrame,
    *,
    allowed_partitions: Sequence[str] = ("test",),
    fold_priority: Sequence[str] = (),
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Select one inference-valid path row per candidate/timestamp.

    Structural sidecars often contain the same candidate under several
    transport folds.  A date heuristic cannot tell whether a contribution was
    generated by a model that saw the row during fitting.  The default is
    deliberately strict: only rows explicitly marked ``meta_partition=test``
    are eligible.  Callers may pass a narrower, predeclared partition set for
    a different contract, but never silently fall back to ``meta_train``.

    Returns the selected rows and an audit containing source counts, collision
    counts, and the rejected non-OOF population.  Selection is deterministic;
    ``fold_priority`` is used before lexical fold order when multiple allowed
    test rows remain for the same candidate/timestamp.
    """

    required = {"candidate_id", "__ts__", "fold", "meta_partition"}
    missing = sorted(required.difference(path_frame.columns))
    if missing:
        raise KeyError(f"path lineage frame missing columns: {missing}")
    allowed = {str(x) for x in allowed_partitions}
    x = path_frame.copy()
    x["__ts__"] = pd.to_datetime(x["__ts__"], utc=True, errors="raise")
    x["meta_partition"] = x["meta_partition"].astype("string")
    x["fold"] = x["fold"].astype("string")
    x["__fold_priority__"] = x["fold"].map(
        {str(name): -i for i, name in enumerate(fold_priority)}
    ).fillna(0).astype(int)
    eligible = x[x["meta_partition"].isin(allowed)].copy()
    key = ["candidate_id", "__ts__"]
    eligible = eligible.sort_values(
        key + ["__fold_priority__", "fold"],
        ascending=[True, True, False, True],
        kind="stable",
    )
    collision = eligible.duplicated(key, keep=False)
    selected = eligible.drop_duplicates(key, keep="first").drop(columns=["__fold_priority__"])
    counts = x.groupby("meta_partition", dropna=False, observed=True).size().rename("rows").reset_index()
    counts["eligible"] = counts["meta_partition"].isin(allowed)
    counts["collision_rows"] = 0
    if collision.any():
        collision_counts = (
            eligible.loc[collision]
            .groupby("meta_partition", dropna=False, observed=True)
            .size()
            .rename("collision_rows")
            .reset_index()
        )
        counts = counts.drop(columns=["collision_rows"]).merge(
            collision_counts, on="meta_partition", how="left"
        )
        counts["collision_rows"] = counts["collision_rows"].fillna(0).astype(int)
    audit = pd.DataFrame(
        [
            {
                "source_partition": str(row.meta_partition),
                "rows": int(row.rows),
                "eligible": bool(row.eligible),
                "collision_rows": int(row.collision_rows),
                "selected_rows": int(
                    (selected["meta_partition"] == row.meta_partition).sum()
                ),
            }
            for row in counts.itertuples(index=False)
        ]
    )
    audit = pd.concat(
        [
            audit,
            pd.DataFrame(
                [
                    {
                        "source_partition": "__summary__",
                        "rows": int(len(x)),
                        "eligible": True,
                        "collision_rows": int(collision.sum()),
                        "selected_rows": int(len(selected)),
                    }
                ]
            ),
        ],
        ignore_index=True,
    )
    return selected.reset_index(drop=True), audit


def _finite_matrix(values: pd.DataFrame | np.ndarray) -> np.ndarray:
    x = values.to_numpy(float) if isinstance(values, pd.DataFrame) else np.asarray(values, dtype=float)
    x = np.nan_to_num(x, nan=0.0, posinf=0.0, neginf=0.0)
    return x


def discover_family_clusters(
    train_abs_share: pd.DataFrame,
    train_signed: pd.DataFrame,
    *,
    k_values: Sequence[int] = (3, 4, 5, 6, 7),
    seed: int = 20260807,
) -> tuple[list[ClusterContract], pd.DataFrame]:
    """Discover clusters of path families using train-only co-activation.

    Families are represented by their row-wise activation profile and signed
    contribution profile.  The profiles are standardised per family, then a
    small KMeans/silhouette screen chooses K.  No realised outcome is read.
    The returned audit keeps the silhouette and candidate K values for review.
    """

    from sklearn.cluster import KMeans
    from sklearn.metrics import silhouette_score

    fields = list(map(str, train_abs_share.columns))
    if not fields or list(train_signed.columns) != fields:
        raise ValueError("absolute and signed family matrices must have identical ordered columns")
    abs_x = _finite_matrix(train_abs_share)
    signed_x = _finite_matrix(train_signed)
    # Each family is a point.  Downsample rows only for the geometry fit so
    # that the representation remains cheap on multi-million-row stores.
    if abs_x.shape[0] > 100_000:
        idx = np.linspace(0, abs_x.shape[0] - 1, 100_000, dtype=int)
        abs_x, signed_x = abs_x[idx], signed_x[idx]
    family_points = np.concatenate([abs_x.T, signed_x.T], axis=1)
    family_points -= family_points.mean(axis=1, keepdims=True)
    scale = family_points.std(axis=1, keepdims=True)
    family_points /= np.maximum(scale, 1e-6)
    candidates: list[tuple[float, int, np.ndarray, np.ndarray]] = []
    for k in sorted(set(int(v) for v in k_values)):
        if k < 2 or k >= len(fields):
            continue
        model = KMeans(n_clusters=k, random_state=seed + k, n_init=20, algorithm="lloyd")
        labels = model.fit_predict(family_points)
        if len(np.unique(labels)) < 2:
            continue
        score = float(silhouette_score(family_points, labels, metric="euclidean"))
        candidates.append((score, k, labels, model.cluster_centers_))
    if not candidates:
        raise ValueError("family cluster discovery found no valid K")
    # Prefer the smallest K within a tiny tolerance of the best geometry.  It
    # gives the conditional layer stable support without hiding the selected K.
    best_score = max(row[0] for row in candidates)
    score, k, labels, centroids = sorted(
        candidates, key=lambda row: (row[0] >= best_score - 0.01, row[0], -row[1]), reverse=True
    )[0]
    # The sorting above prefers a compact model among near-ties explicitly.
    near = [row for row in candidates if row[0] >= best_score - 0.01]
    score, k, labels, centroids = max(near, key=lambda row: (row[0], -row[1]))
    contracts: list[ClusterContract] = []
    for cluster_idx in range(k):
        members = np.flatnonzero(labels == cluster_idx)
        if len(members) == 0:
            continue
        centre_distance = float(np.mean(np.linalg.norm(family_points[members] - centroids[cluster_idx], axis=1)))
        contracts.append(
            ClusterContract(
                cluster_id=f"cluster_{len(contracts):02d}",
                family_fields=tuple(fields[i] for i in members),
                family_indices=tuple(int(i) for i in members),
                centroid_distance=centre_distance,
            )
        )
    audit = pd.DataFrame(
        [{"k": int(row[1]), "silhouette": float(row[0]), "selected": bool(row[1] == k)} for row in candidates]
    ).sort_values(["selected", "silhouette", "k"], ascending=[False, False, True], kind="stable")
    return contracts, audit.reset_index(drop=True)


def materialize_cluster_features(
    frame: pd.DataFrame,
    contracts: Sequence[ClusterContract],
    *,
    family_fields: Sequence[str],
) -> pd.DataFrame:
    """Materialise soft cluster/path memberships and trust features."""

    fields = list(map(str, family_fields))
    signed = _finite_matrix(frame[fields])
    abs_names = [f"family_abs_share__{f}" for f in fields]
    abs_share = _finite_matrix(frame[abs_names])
    conf_names = [f"family_confidence_share__{f}" for f in fields]
    confidence = _finite_matrix(frame[conf_names]) if all(c in frame for c in conf_names) else np.zeros_like(abs_share)
    represented = np.clip(abs_share.sum(axis=1), 0.0, 1.0)
    out: dict[str, np.ndarray] = {
        "cluster_path_represented_mass": represented.astype("float32"),
        "cluster_path_unassigned_mass": (1.0 - represented).clip(0.0, 1.0).astype("float32"),
        "cluster_path_assignment_quality": pd.to_numeric(
            frame.get("family_assignment_quality", pd.Series(0.0, index=frame.index)), errors="coerce"
        ).fillna(0.0).to_numpy("float32"),
        "cluster_path_low_confidence_mass": pd.to_numeric(
            frame.get("family_low_confidence_mass", pd.Series(0.0, index=frame.index)), errors="coerce"
        ).fillna(0.0).to_numpy("float32"),
    }
    memberships: list[np.ndarray] = []
    for contract in contracts:
        idx = np.asarray(contract.family_indices, dtype=int)
        cluster_abs = abs_share[:, idx].sum(axis=1)
        cluster_signed = signed[:, idx].sum(axis=1)
        cluster_conf = confidence[:, idx].sum(axis=1)
        membership = np.divide(cluster_abs, np.maximum(represented, EPS), out=np.zeros(len(frame), dtype=float), where=represented > EPS)
        memberships.append(membership)
        prefix = f"cluster__{contract.cluster_id}__"
        out[prefix + "membership"] = membership.astype("float32")
        out[prefix + "abs_contribution"] = cluster_abs.astype("float32")
        out[prefix + "signed_contribution"] = cluster_signed.astype("float32")
        out[prefix + "confidence_share"] = cluster_conf.astype("float32")
        out[prefix + "active"] = (cluster_abs > EPS).astype("float32")
        out[prefix + "direction"] = np.sign(cluster_signed).astype("float32")
    if memberships:
        m = np.column_stack(memberships)
        p = m / np.maximum(m.sum(axis=1, keepdims=True), EPS)
        out["cluster_path_entropy"] = (-(p * np.log(np.maximum(p, EPS))).sum(axis=1)).astype("float32")
        order = np.sort(m, axis=1)
        out["cluster_path_top2_margin"] = (order[:, -1] - order[:, -2] if m.shape[1] > 1 else order[:, -1]).astype("float32")
        out["cluster_path_top_cluster"] = np.argmax(m, axis=1).astype("int16")
    return pd.DataFrame(out, index=frame.index)


def _quantile_bin(values: np.ndarray, bins: int = 10) -> np.ndarray:
    x = np.asarray(values, dtype=float)
    finite = np.isfinite(x)
    out = np.full(len(x), -1, dtype=np.int16)
    if finite.sum() < max(30, bins * 3):
        return out
    edges = np.unique(np.nanquantile(x[finite], np.linspace(0.0, 1.0, bins + 1)))
    if len(edges) < 3:
        return out
    out[finite] = np.clip(np.digitize(x[finite], edges[1:-1], right=False), 0, len(edges) - 2)
    return out


def weighted_mutual_information(x_bin: np.ndarray, y_bin: np.ndarray, weights: np.ndarray) -> float:
    """Compute MI from a weighted contingency table."""

    x = np.asarray(x_bin, dtype=int)
    y = np.asarray(y_bin, dtype=int)
    w = np.asarray(weights, dtype=float)
    valid = (x >= 0) & (y >= 0) & np.isfinite(w) & (w > 0)
    if valid.sum() < 50:
        return float("nan")
    x, y, w = x[valid], y[valid], w[valid]
    nx, ny = int(x.max()) + 1, int(y.max()) + 1
    table = np.zeros((nx, ny), dtype=float)
    np.add.at(table, (x, y), w)
    total = table.sum()
    if total <= 0:
        return float("nan")
    pxy = table / total
    px = pxy.sum(axis=1, keepdims=True)
    py = pxy.sum(axis=0, keepdims=True)
    nz = pxy > 0
    return float(np.sum(pxy[nz] * np.log(np.maximum(pxy[nz] / (px @ py)[nz], EPS))))


def conditional_mi_scores(
    frame: pd.DataFrame,
    fields: Iterable[str],
    target: np.ndarray,
    membership: np.ndarray,
    *,
    bins: int = 10,
) -> pd.DataFrame:
    """Rank meta fields by a soft active-vs-inactive CMI proxy.

    The score is the positive active-state MI plus a small contrast term over
    inactive rows.  All fields are supplied before this function is called;
    this function only performs the fold-local selection.
    """

    ybin = _quantile_bin(np.asarray(target, dtype=float), bins=bins)
    active_w = np.clip(np.asarray(membership, dtype=float), 0.0, 1.0)
    inactive_w = 1.0 - active_w
    rows: list[dict[str, object]] = []
    for field in fields:
        if field not in frame:
            continue
        x = pd.to_numeric(frame[field], errors="coerce").to_numpy(float)
        if np.isfinite(x).sum() < 100 or np.nanstd(x) <= 1e-10:
            continue
        xbin = _quantile_bin(x, bins=bins)
        active = weighted_mutual_information(xbin, ybin, active_w)
        inactive = weighted_mutual_information(xbin, ybin, inactive_w)
        if not np.isfinite(active):
            continue
        contrast = float(active - inactive) if np.isfinite(inactive) else float(active)
        rows.append({
            "feature": str(field),
            "active_mi": float(active),
            "inactive_mi": float(inactive) if np.isfinite(inactive) else np.nan,
            "cmi_proxy": float(active + 0.25 * contrast),
            "coverage": float(np.isfinite(x).mean()),
            "nunique": int(pd.Series(x).nunique(dropna=True)),
        })
    return pd.DataFrame(rows).sort_values(["cmi_proxy", "active_mi", "feature"], ascending=[False, False, True], kind="stable").reset_index(drop=True) if rows else pd.DataFrame(columns=["feature", "active_mi", "inactive_mi", "cmi_proxy", "coverage", "nunique"])


def soft_cluster_residual_target(
    residual_bps: np.ndarray, membership: np.ndarray
) -> np.ndarray:
    """Return the per-row residual target for one soft cluster."""

    return (np.asarray(residual_bps, dtype=float) * np.clip(np.asarray(membership, dtype=float), 0.0, 1.0)).astype("float32")


def cluster_condition_economics(
    frame: pd.DataFrame,
    cluster_features: pd.DataFrame,
    *,
    cluster_ids: Sequence[str],
    context_fields: Sequence[str],
    residual_column: str = "residual_bps",
    net_column: str = "net_bps",
    train_frame: pd.DataFrame | None = None,
    bins: int = 5,
) -> pd.DataFrame:
    """Measure held-out economic conditions for each soft cluster.

    Quantile edges are fit on ``train_frame`` when supplied and then applied to
    ``frame``.  This prevents the condition report from using held-out feature
    distribution information.  The output is diagnostic only: it reports
    membership-weighted residual/net means, support, and active-vs-inactive
    deltas for every selected context field and bin.
    """

    if bins < 2:
        raise ValueError("bins must be at least two")
    if len(frame) != len(cluster_features):
        raise ValueError("frame and cluster_features must have equal row counts")
    current = frame.reset_index(drop=True)
    cf = cluster_features.reset_index(drop=True)
    source = current if train_frame is None else train_frame
    rows: list[dict[str, object]] = []
    residual = pd.to_numeric(current.get(residual_column), errors="coerce").to_numpy(float)
    net = pd.to_numeric(current.get(net_column), errors="coerce").to_numpy(float)
    for cluster_id in map(str, cluster_ids):
        membership_name = f"cluster__{cluster_id}__membership"
        if membership_name not in cf:
            continue
        membership = pd.to_numeric(cf[membership_name], errors="coerce").fillna(0.0).to_numpy(float)
        active = membership > 0.10
        for field in map(str, context_fields):
            if field not in current or field not in source:
                continue
            train_values = pd.to_numeric(source[field], errors="coerce").to_numpy(float)
            values = pd.to_numeric(current[field], errors="coerce").to_numpy(float)
            finite_train = train_values[np.isfinite(train_values)]
            finite_values = np.isfinite(values)
            if len(finite_train) < max(30, bins * 5) or np.nanstd(finite_train) <= 1e-10:
                continue
            edges = np.unique(np.nanquantile(finite_train, np.linspace(0.0, 1.0, bins + 1)))
            if len(edges) < 3:
                continue
            groups = np.full(len(values), -1, dtype=np.int16)
            groups[finite_values] = np.clip(np.digitize(values[finite_values], edges[1:-1]), 0, len(edges) - 2)
            overall_active_mass = float(np.sum(membership[active]))
            overall_active_residual = float(np.sum(membership * residual) / max(np.sum(membership), EPS))
            overall_active_net = float(np.sum(membership * net) / max(np.sum(membership), EPS))
            for bin_id in range(len(edges) - 1):
                mask = groups == bin_id
                if int(mask.sum()) < 20:
                    continue
                weighted_mass = float(np.sum(membership[mask]))
                if weighted_mass <= EPS:
                    continue
                active_mask = mask & active
                inactive_mask = mask & ~active
                active_resid = float(np.nanmean(residual[active_mask])) if active_mask.any() else np.nan
                inactive_resid = float(np.nanmean(residual[inactive_mask])) if inactive_mask.any() else np.nan
                active_net = float(np.nanmean(net[active_mask])) if active_mask.any() else np.nan
                inactive_net = float(np.nanmean(net[inactive_mask])) if inactive_mask.any() else np.nan
                rows.append(
                    {
                        "cluster_id": cluster_id,
                        "feature": field,
                        "bin": int(bin_id),
                        "bin_low": float(edges[bin_id]),
                        "bin_high": float(edges[bin_id + 1]),
                        "rows": int(mask.sum()),
                        "active_rows": int(active_mask.sum()),
                        "membership_mass": weighted_mass,
                        "active_share": float(active_mask.mean()),
                        "weighted_residual_bps": float(np.sum(membership[mask] * residual[mask]) / weighted_mass),
                        "weighted_net_bps": float(np.sum(membership[mask] * net[mask]) / weighted_mass),
                        "active_mean_residual_bps": active_resid,
                        "inactive_mean_residual_bps": inactive_resid,
                        "active_minus_inactive_residual_bps": float(active_resid - inactive_resid) if np.isfinite(active_resid) and np.isfinite(inactive_resid) else np.nan,
                        "active_mean_net_bps": active_net,
                        "inactive_mean_net_bps": inactive_net,
                        "active_minus_inactive_net_bps": float(active_net - inactive_net) if np.isfinite(active_net) and np.isfinite(inactive_net) else np.nan,
                        "overall_weighted_residual_bps": overall_active_residual,
                        "overall_weighted_net_bps": overall_active_net,
                        "overall_active_mass": overall_active_mass,
                    }
                )
    return pd.DataFrame(rows)


__all__ = [
    "ClusterContract",
    "cluster_condition_economics",
    "conditional_mi_scores",
    "discover_family_clusters",
    "materialize_cluster_features",
    "select_oof_path_rows",
    "soft_cluster_residual_target",
    "weighted_mutual_information",
]
