"""Inference-aligned walk-forward backtest over unseen holdout periods.

This module provides a lightweight offline evaluator that replays trade
candidates using:

1. walk-forward unseen test windows from ``periods_symbols_management``;
2. per-mode candidate masks used by live inference;
3. OOF score + limit-offset predictions generated by the position sizer stack;
4. inference OCO exit-policy logic (same code-path as ``run_inference.py``);
5. position sizing mapping modes (linear / concave / convex);
6. portfolio constraints and strategy acceptance filtering.

The evaluator reports metrics for top-k rank buckets (10/20/30/40%).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, Optional, Set, Tuple

import numpy as np
import pandas as pd

from extreme_price_movements.inference.candidate_selector import (
    _build_mask_for_mode,
    _up_down_zones,
)
from extreme_price_movements.inference.run_inference import _evaluate_oco_policy
from extreme_price_movements.periods_symbols_management import (
    EventSchema,
    SlicePlanner,
    SlicePlannerConfig,
)
from extreme_price_movements.portfolio_manager import PortfolioManager
from extreme_price_movements.position_sizer_v2 import _apply_sizing_mode
from extreme_price_movements.simple_position_sizer import (
    load_calibration_curves,
    calibrate_score,
)
from extreme_price_movements.utils import tprint


@dataclass(frozen=True)
class InferenceBacktestConfig:
    fee_round_trip_pct: float = 0.3
    top_fracs: tuple[float, ...] = (0.10, 0.20, 0.30, 0.40)
    annual_days: int = 365
    sizing_mode: str = "linear"
    base_position_size: float = 1.0
    default_limit_offset_bps: float = 0.0
    rank_col: str = "trading_score_oof"
    limit_offset_col: str = "limit_offset_oof"
    side_col: str = "side"
    regime_col: str = "regime_kind"
    strategy_col: str = "strategy"


class _BacktestPolicyExecutor:
    """Minimal executor adapter for ``_evaluate_oco_policy`` replay."""

    def __init__(self, strategy_params: Dict[str, Dict[str, Any]]) -> None:
        self._strategy_params = strategy_params
        self.closed = False
        self.exit_price = np.nan
        self.exit_reason = ""
        self._latest_state: Dict[str, Any] = {}

    def get_bucket_params(self, bucket_key: str) -> Dict[str, Any]:
        return dict(self._strategy_params.get(bucket_key, {}))

    def close_position(self, symbol: str, price: float, reason: str) -> None:
        _ = symbol
        self.closed = True
        self.exit_price = float(price)
        self.exit_reason = str(reason)

    def update_position_policy_state(self, symbol: str, **kwargs: Any) -> None:
        _ = symbol
        self._latest_state.update(kwargs)


def _build_unseen_mask(
    events: pd.DataFrame,
    planner_cfg: Optional[SlicePlannerConfig],
) -> np.ndarray:
    if "event_id" not in events.columns:
        raise ValueError("events must include 'event_id' to align unseen mask")
    if events["event_id"].isna().any():
        raise ValueError(
            "events contains null event_id values; cannot align unseen mask"
        )
    if events["event_id"].duplicated().any():
        raise ValueError(
            "events must have unique event_id values for unseen mask mapping"
        )

    events_minimal = events[["event_id", "symbol", "t0", "t1"]].copy()
    events_minimal["t0"] = pd.to_datetime(events_minimal["t0"], utc=True)
    events_minimal["t1"] = pd.to_datetime(events_minimal["t1"], utc=True)

    cfg = planner_cfg or SlicePlannerConfig.robust_defaults(schema=EventSchema())
    bundle = SlicePlanner(cfg).build(events_minimal)
    clean_events = bundle["events"]
    plans = bundle["consumer_plans"]["backtest_eval"]

    unseen_event_ids: set[Any] = set()
    for p in plans:
        idx = np.asarray(p.predict_idx, dtype=np.int64)
        if idx.size:
            ev_ids = clean_events.iloc[idx]["event_id"].tolist()
            unseen_event_ids.update(ev_ids)

    return events["event_id"].isin(unseen_event_ids).to_numpy(dtype=bool)


def _mode_for_row(side: str, regime_kind: str) -> str:
    side_l = str(side).lower()
    rg = str(regime_kind).lower()
    if side_l in {"long", "buy", "1", "up"}:
        return "price_up_tf" if rg == "tf" else "price_up_mr"
    return "price_down_tf" if rg == "tf" else "price_down_mr"


def _build_mask_lookup(
    panel: Dict[str, pd.DataFrame],
    feats: Dict[str, pd.DataFrame],
    mask_params_by_mode: Dict[str, Dict[str, Any]],
    metric: str = "ret12h",
) -> Dict[str, pd.DataFrame]:
    up_zone, down_zone = _up_down_zones(feats, panel, metric=metric)
    out: Dict[str, pd.DataFrame] = {}
    for mode, cfg in mask_params_by_mode.items():
        per_mode = _build_mask_for_mode(panel, feats, cfg)
        if mode == "price_up_tf":
            out[mode] = up_zone & per_mode
        elif mode == "price_up_mr":
            out[mode] = up_zone & per_mode
        elif mode == "price_down_tf":
            out[mode] = down_zone & per_mode
        elif mode == "price_down_mr":
            out[mode] = down_zone & per_mode
        else:
            out[mode] = per_mode
    return out


def _ulcer_index(equity: pd.Series) -> float:
    if equity.empty:
        return float("nan")
    dd = equity / equity.cummax() - 1.0
    return float(np.sqrt(np.mean(np.square(np.minimum(dd, 0.0)))))


def _time_under_water(equity: pd.Series) -> float:
    if equity.empty:
        return float("nan")
    dd = equity / equity.cummax() - 1.0
    return float((dd < 0).mean())


def _safe_ratio(num: float, den: float) -> float:
    return float(num / den) if den and np.isfinite(den) else float("nan")


def _compute_slice_metrics(
    slice_df: pd.DataFrame, annual_days: int
) -> Dict[str, float]:
    if slice_df.empty:
        return {
            k: float("nan")
            for k in [
                "pnl_additive_pct_annual",
                "pnl_compounded_pct_annual",
                "pnl_day",
                "trades_day",
                "pnl_trade",
                "win_rate",
                "avg_gain_win",
                "avg_loss_loss",
                "ulcer",
                "time_under_water",
                "max_drawdown",
                "sortino",
                "sharpe",
                "calmar",
                "pnl_variation_timeslices",
                "pnl_variation_assets",
                "avg_holding_hours",
            ]
        }

    d = slice_df.copy()
    d["trade_day"] = pd.to_datetime(d["t0"]).dt.floor("D")
    daily = d.groupby("trade_day", as_index=True)["net_ret"].sum().sort_index()
    n_days = max(1, daily.shape[0])

    additive_ann = daily.mean() * annual_days * 100.0
    compounded_ann = ((1.0 + daily).prod() ** (annual_days / n_days) - 1.0) * 100.0

    eq = (1.0 + daily).cumprod()
    max_dd = float((eq / eq.cummax() - 1.0).min())
    down = daily[daily < 0.0]
    sharpe = _safe_ratio(daily.mean(), daily.std(ddof=0)) * np.sqrt(annual_days)
    sortino = _safe_ratio(daily.mean(), down.std(ddof=0)) * np.sqrt(annual_days)
    calmar = _safe_ratio((compounded_ann / 100.0), abs(max_dd))

    winners = d[d["net_ret"] > 0.0]["net_ret"]
    losers = d[d["net_ret"] <= 0.0]["net_ret"]

    by_month = d.groupby(pd.to_datetime(d["t0"]).dt.to_period("M"))["net_ret"].sum()
    by_asset = d.groupby("symbol")["net_ret"].sum()

    return {
        "pnl_additive_pct_annual": float(additive_ann),
        "pnl_compounded_pct_annual": float(compounded_ann),
        "pnl_day": float(daily.mean()),
        "trades_day": float(d.shape[0] / n_days),
        "pnl_trade": float(d["net_ret"].mean()),
        "win_rate": float((d["net_ret"] > 0).mean()),
        "avg_gain_win": float(winners.mean()) if not winners.empty else 0.0,
        "avg_loss_loss": float(losers.mean()) if not losers.empty else 0.0,
        "ulcer": _ulcer_index(eq),
        "time_under_water": _time_under_water(eq),
        "max_drawdown": max_dd,
        "sortino": float(sortino),
        "sharpe": float(sharpe),
        "calmar": float(calmar),
        "pnl_variation_timeslices": float(by_month.std(ddof=0))
        if len(by_month) > 1
        else 0.0,
        "pnl_variation_assets": float(by_asset.std(ddof=0))
        if len(by_asset) > 1
        else 0.0,
        "avg_holding_hours": float(d["holding_hours"].mean()),
    }


def run_inference_backtest(
    trades: pd.DataFrame,
    panel: Dict[str, pd.DataFrame],
    feats: Dict[str, pd.DataFrame],
    mask_params_by_mode: Dict[str, Dict[str, Any]],
    strategy_exit_params: Dict[str, Dict[str, Any]],
    *,
    config: Optional[InferenceBacktestConfig] = None,
    planner_cfg: Optional[SlicePlannerConfig] = None,
    data_root: Optional[str] = None,
    run_id: Optional[str] = None,
    use_portfolio_manager: bool = True,
    use_strategy_acceptance: bool = True,
    use_calibration_filter: bool = True,
    initial_threshold: float = 0.5,
) -> Dict[str, Any]:
    """Run unseen walk-forward backtest with inference-equivalent policy logic.

    Required columns in ``trades``:
    - ``event_id``, ``symbol``, ``t0``, ``t1``, ``entry_price``
    - score column (default ``trading_score_oof``)
    - optional ``limit_offset_oof``, ``regime_kind``, ``strategy``, ``side``

    Notes:
    - If no OCO exit is triggered before holdout end, exit uses holdout close.
    - A trade is a "win" iff net return > 0 after round-trip fees.
    """
    cfg = config or InferenceBacktestConfig()
    df = trades.copy()
    
    # Load strategy acceptance filter (upstream filtering)
    accepted_strategies: Optional[Set[str]] = None
    if use_strategy_acceptance and data_root and run_id:
        accepted_strategies = _load_strategy_acceptance_filter(data_root, run_id)
        if accepted_strategies:
            df = _apply_strategy_acceptance_filter(df, accepted_strategies, cfg.strategy_col)

    required = {"event_id", "symbol", "t0", "t1", "entry_price", cfg.rank_col}
    missing = sorted(required.difference(df.columns))
    if missing:
        raise ValueError(f"trades missing required columns: {missing}")

    df["t0"] = pd.to_datetime(df["t0"], utc=True)
    df["t1"] = pd.to_datetime(df["t1"], utc=True)
    if cfg.side_col not in df.columns:
        df[cfg.side_col] = "long"
    if cfg.regime_col not in df.columns:
        df[cfg.regime_col] = "tf"
    if cfg.strategy_col not in df.columns:
        df[cfg.strategy_col] = "default"
    if cfg.limit_offset_col not in df.columns:
        df[cfg.limit_offset_col] = cfg.default_limit_offset_bps

    unseen_mask = _build_unseen_mask(
        df[["event_id", "symbol", "t0", "t1"]].copy(), planner_cfg
    )
    df = df.loc[unseen_mask].copy()
    if df.empty:
        return {"n_unseen": 0, "metrics": {}, "reason": "no_unseen_trades"}
    
    # Load calibration data for confidence filtering
    calibration_data: Dict[str, Dict[str, Any]] = {}
    if use_calibration_filter and data_root and run_id:
        calibration_data = load_calibration_curves(data_root, run_id)
        if calibration_data:
            tprint(f"[InferenceBacktest] Loaded calibration for {len(calibration_data)} strategies")

    mode_masks = _build_mask_lookup(panel, feats, mask_params_by_mode)
    
    # Initialize Portfolio Manager
    portfolio_mgr = None
    if use_portfolio_manager:
        portfolio_mgr = PortfolioManager(
            max_positions=4,
            max_portfolio_pct=0.30,
            max_position_usdt=5000.0,
            cooldown_hours=24.0,
            max_same_side_pct=0.75,
            max_same_strategy_pct=0.50,
        )
        tprint("[InferenceBacktest] PortfolioManager initialized (max 4 pos, 30% cap)")

    valid_period_mask = np.zeros(len(df), dtype=bool)
    for i, row in enumerate(df.itertuples(index=False)):
        mode = _mode_for_row(getattr(row, cfg.side_col), getattr(row, cfg.regime_col))
        mask_df = mode_masks.get(mode)
        if mask_df is None:
            continue
        ts = pd.Timestamp(getattr(row, "t0"))
        sym = str(getattr(row, "symbol"))
        if ts in mask_df.index and sym in mask_df.columns:
            valid_period_mask[i] = bool(mask_df.loc[ts, sym])
    df = df.loc[valid_period_mask].copy()
    if df.empty:
        return {"n_unseen": int(unseen_mask.sum()), "n_masked": int(valid_period_mask.sum()), "metrics": {}, "reason": "all_masked"}
    
    # Apply calibration-based confidence filtering
    if calibration_data:
        n_before = len(df)
        # Filter trades below p75 calibrated threshold
        def passes_calibration(row):
            sid = row[cfg.strategy_col]
            raw_score = row[cfg.rank_col]
            calib = calibration_data.get(sid, {})
            p75 = calib.get("p75_threshold", 0.5)
            if p75 > 0:
                calibrated = calibrate_score(raw_score, sid, calibration_data)
                return calibrated >= p75
            return raw_score >= 0.5
        
        mask = df.apply(passes_calibration, axis=1)
        df = df[mask].copy()
        tprint(f"[InferenceBacktest] Calibration filter: {n_before} -> {len(df)} trades")

    raw_rank = df[cfg.rank_col].to_numpy(dtype=float)
    
    # Resolve trade conflicts using calibrated confidence
    df = _resolve_trade_conflicts(df, calibration_data, cfg.rank_col, cfg.strategy_col)
    
    # Apply position sizing mode
    pos_sizes = _apply_sizing_mode(
        df[cfg.rank_col].to_numpy(dtype=float), 
        cfg.base_position_size, 
        cfg.sizing_mode
    )
    df["position_size"] = pos_sizes
    
    fee_rt = cfg.fee_round_trip_pct / 100.0
    processed_row_positions: list[int] = []
    net_returns: list[float] = []
    holding_hours: list[float] = []
    win_flags: list[bool] = []
    portfolio_states: list[Dict[str, Any]] = []
    
    # Track PortfolioManager state for each timestamp
    current_time: Optional[pd.Timestamp] = None
    position_size_cap: float = 0.0

    for row in df.itertuples(index=False):
        symbol = str(getattr(row, "symbol"))
        side = str(getattr(row, cfg.side_col)).lower()
        is_long = side in {"long", "buy", "1", "up"}
        entry_px = float(getattr(row, "entry_price"))
        offset_bps = float(getattr(row, cfg.limit_offset_col))
        
        # Portfolio Manager check
        if portfolio_mgr is not None:
            t0 = pd.Timestamp(getattr(row, "t0"))
            t1 = pd.Timestamp(getattr(row, "t1"))
            confidence_score = float(getattr(row, cfg.rank_col))
            strategy_id = str(getattr(row, cfg.strategy_col))
            
            can_enter, info = portfolio_mgr.can_enter_position(
                symbol=symbol,
                side=side,
                strategy_id=strategy_id,
                confidence_score=confidence_score,
                initial_threshold=initial_threshold,
                current_time=t0,
            )
            
            if not can_enter:
                # Skip this trade due to portfolio constraints
                continue
            
            # Use position size from portfolio manager's cap
            position_size_cap = info.get("position_size_cap", 0.0)
        else:
            t0 = pd.Timestamp(getattr(row, "t0"))
            t1 = pd.Timestamp(getattr(row, "t1"))
            strategy_id = str(getattr(row, cfg.strategy_col))
        
        if is_long:
            entry_exec = entry_px * (1.0 - offset_bps / 10_000.0)
        else:
            entry_exec = entry_px * (1.0 + offset_bps / 10_000.0)

        close_panel = panel.get("close")
        high_panel = panel.get("high")
        low_panel = panel.get("low")
        open_panel = panel.get("open")
        if any(x is None for x in (open_panel, high_panel, low_panel, close_panel)):
            raise ValueError("panel must include open/high/low/close DataFrames")
        if symbol not in close_panel.columns:
            continue

        bars = pd.DataFrame(
            {
                "open": open_panel[symbol],
                "high": high_panel[symbol],
                "low": low_panel[symbol],
                "close": close_panel[symbol],
            }
        ).dropna()
        bars = bars[(bars.index >= t0) & (bars.index <= t1)]
        if bars.empty:
            continue

        bkey = str(getattr(row, cfg.strategy_col))
        params = dict(strategy_exit_params.get(bkey, {}))
        sl = float(params.get("sl_atr_mult", 0.01))
        tp_ratio = float(params.get("tp_sl_ratio", 2.0))
        if is_long:
            stop_px = entry_exec * (1.0 - sl)
            limit_px = entry_exec * (1.0 + sl * tp_ratio)
        else:
            stop_px = entry_exec * (1.0 + sl)
            limit_px = entry_exec * (1.0 - sl * tp_ratio)

        state = {
            "side": "long" if is_long else "short",
            "entry_price": float(entry_exec),
            "strategy_key": bkey,
            "stop_price": float(stop_px),
            "limit_price": float(limit_px),
            "peak_price": float(entry_exec),
            "mfe": 0.0,
            "last_5m_eval_ts": None,
        }
        ex = _BacktestPolicyExecutor(strategy_exit_params)
        _evaluate_oco_policy(symbol, state, bars, ex)

        exit_px = (
            float(ex.exit_price)
            if ex.closed and np.isfinite(ex.exit_price)
            else float(bars["close"].iloc[-1])
        )
        if is_long:
            gross_ret = (exit_px - entry_exec) / max(entry_exec, 1e-12)
        else:
            gross_ret = (entry_exec - exit_px) / max(entry_exec, 1e-12)

        # Apply position sizing (portfolio manager cap or default)
        if portfolio_mgr is not None and position_size_cap > 0:
            # Use portfolio manager calculated size
            size = min(float(getattr(row, "position_size", 1.0)), position_size_cap / entry_exec)
            portfolio_mgr.record_position_open(
                symbol=symbol,
                side=side,
                strategy_id=strategy_id,
                position_size=position_size_cap,
                entry_price=entry_exec,
                entry_time=t1,
            )
        else:
            size = float(getattr(row, "position_size", 1.0))
        
        net_ret = (gross_ret - fee_rt) * size
        
        # Record position close for portfolio manager
        if portfolio_mgr is not None:
            was_win = net_ret > 0.0
            portfolio_mgr.record_position_close(
                symbol=symbol,
                exit_price=exit_px,
                exit_time=t1,
                exit_reason=ex.exit_reason or "holdout_end",
            )
        hold_h = max((bars.index[-1] - bars.index[0]).total_seconds() / 3600.0, 0.0)

        processed_row_positions.append(getattr(row, 'Index', 0))
        net_returns.append(float(net_ret))
        holding_hours.append(float(hold_h))
        win_flags.append(bool(net_ret > 0.0))
        
        # Record portfolio state for this trade
        if portfolio_mgr is not None:
            portfolio_states.append(portfolio_mgr.get_portfolio_state())

    df = df.iloc[processed_row_positions].copy()
    df["net_ret"] = np.asarray(net_returns, dtype=float)
    df["holding_hours"] = np.asarray(holding_hours, dtype=float)
    df["is_win"] = np.asarray(win_flags, dtype=bool)
    if df.empty:
        result = {
            "n_unseen": int(unseen_mask.sum()),
            "n_masked": int(valid_period_mask.sum()),
            "n_scored": int(len(df)),
            "metrics": {},
            "reason": "no_trades_after_processing",
        }
        if portfolio_mgr is not None:
            result["portfolio_final_state"] = portfolio_mgr.get_portfolio_state()
        return result

    metrics: Dict[str, Dict[str, float]] = {}
    df = df.sort_values(["t0", cfg.rank_col], ascending=[True, False])
    for frac in cfg.top_fracs:
        picked = (
            df.groupby(pd.to_datetime(df["t0"]).dt.floor("D"), group_keys=False)
            .apply(
                lambda g: g.nlargest(max(1, int(np.ceil(len(g) * frac))), cfg.rank_col)
            )
            .reset_index(drop=True)
        )
        metrics[f"top_{int(frac * 100)}pct"] = _compute_slice_metrics(
            picked, cfg.annual_days
        )

    result = {
        "n_total": int(len(trades)),
        "n_unseen": int(unseen_mask.sum()),
        "n_masked": int(valid_period_mask.sum()),
        "n_scored": int(len(df)),
        "win_rate": float(df["is_win"].mean()),
        "metrics": metrics,
        "trades": df,
    }
    
    if portfolio_mgr is not None:
        result["portfolio_final_state"] = portfolio_mgr.get_portfolio_state()
        result["portfolio_history"] = portfolio_states
    
    if accepted_strategies:
        result["accepted_strategies_used"] = len(accepted_strategies)
    
    if calibration_data:
        result["calibration_strategies"] = len(calibration_data)
    
    return result


# =============================================================================
# Strategy Acceptance & Calibration Helpers
# =============================================================================

def _load_strategy_acceptance_filter(
    data_root: str,
    run_id: str,
) -> Optional[Set[str]]:
    """Load accepted strategies from policy_optimiser output.
    
    Returns set of accepted strategy_ids, or None if no acceptance file exists.
    """
    paths = [
        Path(data_root) / "artifacts" / run_id / "strategy_final_acceptation.json",
        Path(data_root) / "artifacts" / run_id / "policy_params" / "strategy_final_acceptation.json",
    ]
    
    for path in paths:
        if path.exists():
            try:
                payload = json.loads(path.read_text())
                strategies = payload.get("strategies", [])
                accepted = {s["strategy_id"] for s in strategies if "strategy_id" in s}
                tprint(f"[StrategyFilter] Loaded {len(accepted)} accepted strategies from {path}")
                return accepted
            except Exception as e:
                tprint(f"[StrategyFilter] Error loading {path}: {e}")
                continue
    
    return None


def _apply_strategy_acceptance_filter(
    df: pd.DataFrame,
    accepted_strategies: Optional[Set[str]],
    strategy_col: str = "strategy",
) -> pd.DataFrame:
    """Filter trades to only accepted strategies."""
    if accepted_strategies is None:
        return df
    
    n_before = len(df)
    df = df[df[strategy_col].isin(accepted_strategies)].copy()
    n_after = len(df)
    
    tprint(f"[StrategyFilter] {n_before} -> {n_after} trades after acceptance filtering")
    return df


def _resolve_trade_conflicts(
    candidates: pd.DataFrame,
    calibration_data: Dict[str, Dict[str, Any]],
    rank_col: str = "trading_score_oof",
    strategy_col: str = "strategy",
) -> pd.DataFrame:
    """Resolve conflicts by keeping highest calibrated confidence.
    
    When multiple trades compete for same timestamp, select based on
    calibrated confidence score = raw_score / p75_threshold.
    """
    if candidates.empty:
        return candidates
    
    if not calibration_data:
        # No calibration - use raw scores directly
        return candidates.loc[candidates.groupby(["symbol", "t0"])[rank_col].idxmax()]
    
    # Compute calibrated scores
    def compute_calibrated_score(row):
        raw_score = row[rank_col]
        sid = row[strategy_col]
        calib = calibration_data.get(sid, {})
        p75 = calib.get("p75_threshold", 0.5)
        if p75 > 0:
            return raw_score / p75
        return raw_score
    
    candidates["_calibrated_score"] = candidates.apply(compute_calibrated_score, axis=1)
    
    # Group by symbol and time, keep highest calibrated
    result = candidates.loc[candidates.groupby(["symbol", "t0"])["_calibrated_score"].idxmax()]
    result = result.drop(columns=["_calibrated_score"])
    
    return result


__all__ = ["InferenceBacktestConfig", "run_inference_backtest"]
