"""Frozen V9 tail overlay driven by the deployed meta-model score.

The historical V9 policy is an overlay on the parent meta rank.  It is not a
second standalone meta model.  This bundle preserves that contract at
inference: map the aligned meta score to a frozen side-specific percentile,
then apply the train-only side x archetype residual-state tail adjustment.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

import numpy as np
import pandas as pd

from .meta_historical_rank import HistoricalScoreRankReference


def _midrank(values: np.ndarray, reference: np.ndarray) -> np.ndarray:
    result = np.full(len(values), 0.5, dtype=np.float32)
    finite = np.isfinite(values)
    if reference.size and finite.any():
        left = np.searchsorted(reference, values[finite], side="left")
        right = np.searchsorted(reference, values[finite], side="right")
        result[finite] = ((left + right) / (2.0 * reference.size)).astype(
            np.float32
        )
    return result


def _normalized_archetype(frame: pd.DataFrame) -> np.ndarray:
    values = frame.get(
        "archetype_policy_key", pd.Series("missing", index=frame.index)
    ).astype(str)
    sides = frame.get("side_name", pd.Series("", index=frame.index)).astype(str)
    output = values.to_numpy(dtype=object, copy=True)
    for side in ("long", "short"):
        prefix = f"{side}__"
        mask = sides.str.lower().eq(side).to_numpy() & values.str.startswith(
            prefix, na=False
        ).to_numpy()
        if mask.any():
            output[mask] = [str(value)[len(prefix) :] for value in output[mask]]
    return output


@dataclass
class MetaScoreV9TailBundle:
    """Apply the frozen V9 tail policy to a calibrated parent meta score."""

    historical_rank_reference: HistoricalScoreRankReference
    local_references: dict[
        tuple[str, str, str], list[tuple[str, float, np.ndarray]]
    ]
    threshold: float = 0.95
    alpha_down: float = 0.005
    alpha_up: float = 0.0
    score_col: str = "score_meta_base_soft_label"
    fit_through: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    # CanonicalMetaPostprocessor uses this marker to apply the overlay after
    # the frozen residual-state transform has generated resid_event_aegmm_*.
    post_state_overlay: bool = True

    def required_input_features(self) -> list[str]:
        # The parent score and identity columns are injected by inference.  The
        # local tail features are generated by the residual-state block.
        return []

    def generated_overlay_features(self) -> list[str]:
        return list(
            dict.fromkeys(
                feature
                for payload in self.local_references.values()
                for feature, _, _ in payload
            )
        )

    def _parent_rank(self, frame: pd.DataFrame) -> np.ndarray:
        rank_frame = pd.DataFrame(index=frame.index)
        rank_frame[self.historical_rank_reference.side_col] = frame.get(
            "side_name", pd.Series("missing", index=frame.index)
        )
        rank_frame[self.historical_rank_reference.score_col] = pd.to_numeric(
            frame[self.score_col], errors="coerce"
        )
        return self.historical_rank_reference.transform(rank_frame).to_numpy(
            dtype=np.float32, copy=False
        )

    def predict(self, frame: pd.DataFrame) -> pd.DataFrame:
        if self.score_col not in frame.columns:
            raise ValueError(f"V9 parent input missing score: {self.score_col}")
        parent_rank = self._parent_rank(frame)
        hit_probability = pd.to_numeric(frame[self.score_col], errors="coerce").to_numpy(
            dtype=np.float32, copy=False
        )
        return pd.DataFrame(
            {
                "score_lifecycle_only": hit_probability,
                "score_residual_overlay": hit_probability,
                "score_shock_adjusted": hit_probability,
                "shock_composite_raw": np.zeros(len(frame), dtype=np.float32),
                "shock_composite_local": np.zeros(len(frame), dtype=np.float32),
                "hit_probability": hit_probability,
                "historical_rank_parent": parent_rank,
                "historical_rank": parent_rank,
                "resid_extreme_adverse_composite": np.full(
                    len(frame), 0.5, dtype=np.float32
                ),
                "resid_extreme_positive_composite": np.full(
                    len(frame), 0.5, dtype=np.float32
                ),
            },
            index=frame.index,
        )

    def _composite(self, frame: pd.DataFrame, event: str) -> np.ndarray:
        output = np.full(len(frame), 0.5, dtype=np.float32)
        sides = frame.get("side_name", pd.Series("", index=frame.index)).astype(
            str
        ).str.lower().to_numpy()
        archetypes = _normalized_archetype(frame)
        for (side, archetype, event_name), payload in self.local_references.items():
            if event_name != event:
                continue
            positions = np.flatnonzero(
                (sides == str(side).lower()) & (archetypes == str(archetype))
            )
            if not len(positions):
                continue
            components: list[np.ndarray] = []
            for feature, direction, reference in payload:
                if feature not in frame.columns:
                    raise ValueError(
                        f"V9 residual overlay missing generated feature: {feature}"
                    )
                values = np.float32(direction) * pd.to_numeric(
                    frame.iloc[positions][feature], errors="coerce"
                ).to_numpy(dtype=np.float32)
                components.append(
                    _midrank(values, np.asarray(reference, dtype=np.float32))
                )
            if components:
                output[positions] = np.mean(
                    np.column_stack(components), axis=1
                ).astype(np.float32)
        return output

    def apply_residual_overlay(
        self,
        frame: pd.DataFrame,
        predecessor: pd.DataFrame,
    ) -> pd.DataFrame:
        result = predecessor.copy()
        parent = pd.to_numeric(
            result.get("historical_rank_parent", result["historical_rank"]),
            errors="coerce",
        ).to_numpy(dtype=np.float32)
        adverse = self._composite(frame, "adverse")
        positive = self._composite(frame, "positive")
        denominator = max(1.0 - float(self.threshold), 1e-6)
        adverse_intensity = np.clip(
            (adverse - float(self.threshold)) / denominator, 0.0, 1.0
        ).astype(np.float32)
        positive_intensity = np.clip(
            (positive - float(self.threshold)) / denominator, 0.0, 1.0
        ).astype(np.float32)
        adjusted = parent.copy()
        top10 = parent >= 0.90
        near = (parent >= 0.80) & (parent < 0.90)
        adjusted[top10] -= np.float32(self.alpha_down) * adverse_intensity[top10]
        adjusted[near] += np.float32(self.alpha_up) * positive_intensity[near]
        result["historical_rank"] = np.clip(adjusted, 0.0, 1.0).astype(
            np.float32
        )
        result["resid_extreme_adverse_composite"] = adverse
        result["resid_extreme_positive_composite"] = positive
        return result

    def manifest(self) -> dict[str, Any]:
        return {
            "schema": "meta_score_v9_tail_bundle_v1",
            "score_col": self.score_col,
            "fit_through": self.fit_through,
            "threshold": float(self.threshold),
            "alpha_down": float(self.alpha_down),
            "alpha_up": float(self.alpha_up),
            "local_cells": int(len(self.local_references)),
            "generated_overlay_features": self.generated_overlay_features(),
            "historical_rank": self.historical_rank_reference.manifest(),
            "metadata": self.metadata,
            "contract": (
                "aligned deployed meta score -> frozen side CDF -> frozen "
                "side x archetype V9 tail overlay"
            ),
        }
