"""
Regime Feature Integration Module

This module provides regime-aware feature integration capabilities for the feature generation system.

The features generated by this module follow three key principles:

1. Lagged Features: Include past values (windowed features) to give the model context.
   - Example: moving averages, volatility over past 3–5 bars
   - Implementation: _generate_lagged_features()

2. Derived Features: Ratios, normalized indicators, or trend strength measures help reduce sensitivity to noise.
   - Example: price-to-MA ratios, Z-scores, coefficient of variation
   - Implementation: _generate_derived_features()

3. Temporal Awareness: Include temporal differences or momentum indicators so the model can learn trends rather than instantaneous values.
   - Example: price differences, momentum indicators, rate of change (ROC)
   - Implementation: _generate_temporal_features()
"""

from typing import Dict, List, Optional, Any, Union
import pandas as pd
import numpy as np
from dataclasses import dataclass
from enum import Enum

from ..core.feature_generator import FeatureGenerator
from ..core.feature_generator import FeatureConfig, FeatureCategory
from ..base_calculations.base_calculator import BaseCalculationType


class RegimeType(Enum):
    """Enumeration of regime types."""
    TRENDING = "trending"
    MEAN_REVERTING = "mean_reverting"
    VOLATILE = "volatile"
    STABLE = "stable"
    UNKNOWN = "unknown"


@dataclass
class RegimeFeatureConfig:
    """Configuration for regime feature integration."""
    
    name: str = "regime_feature_integration"
    enable_regime_detection: bool = True
    regime_threshold: float = 0.5
    lookback_period: int = 20
    min_samples_per_regime: int = 50
    enable_adaptive_features: bool = True
    enable_regime_transitions: bool = True
    vectorbt_threshold: int = 1000
    
    def __post_init__(self):
        """Post-initialization validation."""
        if self.regime_threshold < 0 or self.regime_threshold > 1:
            raise ValueError("regime_threshold must be between 0 and 1")
        if self.lookback_period < 5:
            raise ValueError("lookback_period must be at least 5")


class RegimeFeatureIntegration(FeatureGenerator):
    """Regime-aware feature integration generator."""
    
    def __init__(self, config: Optional[RegimeFeatureConfig] = None):
        """Initialize regime feature integration."""
        if config is None:
            config = RegimeFeatureConfig()
            
        feature_config = FeatureConfig(
            name=config.name,
            category=FeatureCategory.REGIME,
            description="Regime-aware feature integration",
            required_columns=["close", "volume"],
            default_lookback=config.lookback_period,
            min_lookback=10,
            max_lookback=200,
            parameters=config.__dict__,
            matrix_optimized=True,
            gpu_accelerated=False
        )
        super().__init__(feature_config)
        self.regime_config = config
        self.current_regime = RegimeType.UNKNOWN
        self.regime_history = []
        
    def _detect_regime(self, data: pd.DataFrame) -> RegimeType:
        """Detect current market regime."""
        try:
            if len(data) < self.regime_config.min_samples_per_regime:
                return RegimeType.UNKNOWN
                
            # Calculate regime indicators
            returns = data['close'].pct_change().dropna()
            volatility = returns.rolling(window=self.regime_config.lookback_period).std()
            trend_strength = abs(returns.rolling(window=self.regime_config.lookback_period).mean())
            
            # Simple regime detection logic
            recent_vol = volatility.iloc[-1] if not volatility.empty else 0
            recent_trend = trend_strength.iloc[-1] if not trend_strength.empty else 0
            
            if recent_vol > self.regime_config.regime_threshold:
                return RegimeType.VOLATILE
            elif recent_trend > self.regime_config.regime_threshold:
                return RegimeType.TRENDING
            elif recent_vol < 0.1:  # Low volatility threshold
                return RegimeType.STABLE
            else:
                return RegimeType.MEAN_REVERTING
                
        except Exception:
            return RegimeType.UNKNOWN
    
    def _generate_regime_features(self, data: pd.DataFrame) -> Dict[str, Any]:
        """Generate regime-specific features with lagged, derived, and temporal features."""
        regime = self._detect_regime(data)
        self.current_regime = regime
        self.regime_history.append(regime)
        
        # Keep only recent regime history
        if len(self.regime_history) > 100:
            self.regime_history = self.regime_history[-100:]
            
        features = {
            'regime_type': regime.value,
            'regime_confidence': 0.8,  # Placeholder
            'regime_duration': len(self.regime_history),
            'regime_stability': self._calculate_regime_stability()
        }
        
        # Add lagged features (windowed features for past 3-5 bars)
        features.update(self._generate_lagged_features(data))
        
        # Add derived features (ratios, normalized indicators, trend strength)
        features.update(self._generate_derived_features(data))
        
        # Add temporal awareness features (differences, momentum indicators)
        features.update(self._generate_temporal_features(data))
        
        if self.regime_config.enable_adaptive_features:
            features.update(self._generate_adaptive_features(data, regime))
            
        if self.regime_config.enable_regime_transitions:
            features.update(self._generate_transition_features())
            
        return features
    
    def _generate_lagged_features(self, data: pd.DataFrame) -> Dict[str, Any]:
        """
        Generate lagged features: windowed features for past 3-5 bars.
        
        Includes moving averages and volatility over past 3-5 bars to give the model context.
        """
        features = {}
        
        if 'close' not in data.columns or len(data) < 5:
            return features
        
        try:
            # Lagged windows: 3, 4, 5 bars
            windows = [3, 4, 5]
            
            for window in windows:
                if len(data) >= window:
                    # Moving averages over past N bars
                    ma = data['close'].rolling(window=window).mean()
                    if not ma.empty:
                        features[f'lagged_ma_{window}'] = ma.iloc[-1] if not pd.isna(ma.iloc[-1]) else 0.0
                    
                    # Volatility over past N bars
                    returns = data['close'].pct_change().dropna()
                    if len(returns) >= window:
                        vol = returns.rolling(window=window).std()
                        if not vol.empty:
                            features[f'lagged_volatility_{window}'] = vol.iloc[-1] if not pd.isna(vol.iloc[-1]) else 0.0
                    
                    # Price range over past N bars
                    if 'high' in data.columns and 'low' in data.columns:
                        price_range = (data['high'] - data['low']).rolling(window=window).mean()
                        if not price_range.empty:
                            features[f'lagged_range_{window}'] = price_range.iloc[-1] if not pd.isna(price_range.iloc[-1]) else 0.0
                    
                    # Volume moving average over past N bars
                    if 'volume' in data.columns:
                        vol_ma = data['volume'].rolling(window=window).mean()
                        if not vol_ma.empty:
                            features[f'lagged_volume_ma_{window}'] = vol_ma.iloc[-1] if not pd.isna(vol_ma.iloc[-1]) else 0.0
                    
                    # Maximum and minimum prices over past N bars
                    max_price = data['close'].rolling(window=window).max()
                    min_price = data['close'].rolling(window=window).min()
                    if not max_price.empty:
                        features[f'lagged_max_{window}'] = max_price.iloc[-1] if not pd.isna(max_price.iloc[-1]) else 0.0
                    if not min_price.empty:
                        features[f'lagged_min_{window}'] = min_price.iloc[-1] if not pd.isna(min_price.iloc[-1]) else 0.0
                    
        except Exception as e:
            # Return empty dict on error - features will be skipped
            pass
        
        return features
    
    def _generate_derived_features(self, data: pd.DataFrame) -> Dict[str, Any]:
        """
        Generate derived features: ratios, normalized indicators, trend strength measures.
        
        Helps reduce sensitivity to noise through normalized indicators and trend strength measures.
        """
        features = {}
        
        if 'close' not in data.columns or len(data) < 5:
            return features
        
        try:
            returns = data['close'].pct_change().dropna()
            
            if len(returns) < 5:
                return features
            
            # Normalized price position (Z-score relative to recent window)
            window = min(20, len(data))
            if window >= 5:
                price_mean = data['close'].rolling(window=window).mean()
                price_std = data['close'].rolling(window=window).std()
                if not price_mean.empty and not price_std.empty:
                    current_price = data['close'].iloc[-1]
                    mean_val = price_mean.iloc[-1]
                    std_val = price_std.iloc[-1]
                    if not pd.isna(mean_val) and not pd.isna(std_val) and std_val > 1e-8:
                        features['price_zscore'] = (current_price - mean_val) / std_val
                    else:
                        features['price_zscore'] = 0.0
            
            # Price-to-Moving Average Ratio (normalized indicator)
            for window in [5, 10, 20]:
                if len(data) >= window:
                    ma = data['close'].rolling(window=window).mean()
                    if not ma.empty and not pd.isna(ma.iloc[-1]) and ma.iloc[-1] > 1e-8:
                        current_price = data['close'].iloc[-1]
                        features[f'price_to_ma_ratio_{window}'] = current_price / ma.iloc[-1]
            
            # Coefficient of Variation (CV) - normalized volatility measure
            if len(returns) >= 10:
                returns_mean = returns.tail(10).mean()
                returns_std = returns.tail(10).std()
                if not pd.isna(returns_mean) and abs(returns_mean) > 1e-8:
                    features['returns_cv'] = returns_std / abs(returns_mean)
                else:
                    features['returns_cv'] = returns_std if not pd.isna(returns_std) else 0.0
            
            # Trend Strength Ratio (normalized trend measure)
            if len(returns) >= 10:
                positive_returns = (returns.tail(10) > 0).sum()
                total_returns = len(returns.tail(10))
                features['trend_strength_ratio'] = positive_returns / total_returns if total_returns > 0 else 0.5
            
            # Volatility Ratio (current vs historical volatility)
            if len(returns) >= 20:
                short_vol = returns.tail(5).std()
                long_vol = returns.tail(20).std()
                if not pd.isna(short_vol) and not pd.isna(long_vol) and long_vol > 1e-8:
                    features['volatility_ratio'] = short_vol / long_vol
                else:
                    features['volatility_ratio'] = 1.0
            
            # Price Range Ratio (normalized range indicator)
            if 'high' in data.columns and 'low' in data.columns:
                current_range = data['high'].iloc[-1] - data['low'].iloc[-1]
                if len(data) >= 10:
                    avg_range = (data['high'] - data['low']).tail(10).mean()
                    if not pd.isna(avg_range) and avg_range > 1e-8:
                        features['range_ratio'] = current_range / avg_range
                    else:
                        features['range_ratio'] = 1.0
            
            # Volume Ratio (current vs average volume)
            if 'volume' in data.columns and len(data) >= 10:
                current_volume = data['volume'].iloc[-1]
                avg_volume = data['volume'].tail(10).mean()
                if not pd.isna(avg_volume) and avg_volume > 1e-8:
                    features['volume_ratio'] = current_volume / avg_volume
                else:
                    features['volume_ratio'] = 1.0
            
            # Mean Reversion Strength (normalized autocorrelation)
            if len(returns) >= 10:
                autocorr = returns.tail(10).autocorr(lag=1)
                if not pd.isna(autocorr):
                    features['mean_reversion_strength_normalized'] = abs(autocorr)
                else:
                    features['mean_reversion_strength_normalized'] = 0.0
            
        except Exception as e:
            # Return empty dict on error - features will be skipped
            pass
        
        return features
    
    def _generate_temporal_features(self, data: pd.DataFrame) -> Dict[str, Any]:
        """
        Generate temporal awareness features: temporal differences and momentum indicators.
        
        Allows the model to learn trends rather than instantaneous values.
        """
        features = {}
        
        if 'close' not in data.columns or len(data) < 5:
            return features
        
        try:
            # Temporal differences (first and second order)
            if len(data) >= 2:
                # First difference: price change
                price_diff = data['close'].diff()
                if not price_diff.empty:
                    features['temporal_price_diff'] = price_diff.iloc[-1] if not pd.isna(price_diff.iloc[-1]) else 0.0
                
                # Second difference: acceleration
                if len(data) >= 3:
                    price_diff2 = price_diff.diff()
                    if not price_diff2.empty:
                        features['temporal_price_acceleration'] = price_diff2.iloc[-1] if not pd.isna(price_diff2.iloc[-1]) else 0.0
            
            # Momentum indicators
            returns = data['close'].pct_change().dropna()
            
            if len(returns) >= 3:
                # Short-term momentum (3 bars)
                short_momentum = returns.tail(3).sum()
                features['momentum_3'] = short_momentum if not pd.isna(short_momentum) else 0.0
                
                # Medium-term momentum (5 bars)
                if len(returns) >= 5:
                    medium_momentum = returns.tail(5).sum()
                    features['momentum_5'] = medium_momentum if not pd.isna(medium_momentum) else 0.0
                
                # Long-term momentum (10 bars)
                if len(returns) >= 10:
                    long_momentum = returns.tail(10).sum()
                    features['momentum_10'] = long_momentum if not pd.isna(long_momentum) else 0.0
            
            # Momentum acceleration (rate of change of momentum)
            if len(returns) >= 6:
                momentum_3_recent = returns.tail(3).sum()
                momentum_3_previous = returns.iloc[-6:-3].sum() if len(returns) >= 6 else 0.0
                features['momentum_acceleration'] = momentum_3_recent - momentum_3_previous if not pd.isna(momentum_3_recent) else 0.0
            
            # Rate of Change (ROC) indicators
            for period in [3, 5, 10]:
                if len(data) >= period + 1:
                    current_price = data['close'].iloc[-1]
                    past_price = data['close'].iloc[-period-1]
                    if past_price > 1e-8:
                        roc = (current_price - past_price) / past_price
                        features[f'roc_{period}'] = roc if not pd.isna(roc) else 0.0
            
            # Temporal volatility trend (volatility change over time)
            if len(returns) >= 10:
                short_vol = returns.tail(3).std()
                long_vol = returns.tail(10).std()
                if not pd.isna(short_vol) and not pd.isna(long_vol):
                    vol_change = short_vol - long_vol
                    features['volatility_trend'] = vol_change if not pd.isna(vol_change) else 0.0
            
            # Volume momentum
            if 'volume' in data.columns and len(data) >= 5:
                volume_diff = data['volume'].diff()
                if not volume_diff.empty:
                    features['volume_momentum'] = volume_diff.iloc[-1] if not pd.isna(volume_diff.iloc[-1]) else 0.0
                
                # Volume rate of change
                if len(data) >= 5:
                    current_volume = data['volume'].iloc[-1]
                    past_volume = data['volume'].iloc[-5]
                    if past_volume > 1e-8:
                        vol_roc = (current_volume - past_volume) / past_volume
                        features['volume_roc'] = vol_roc if not pd.isna(vol_roc) else 0.0
            
            # Price position trend (whether price is trending up or down relative to recent range)
            if len(data) >= 10:
                recent_max = data['close'].tail(10).max()
                recent_min = data['close'].tail(10).min()
                current_price = data['close'].iloc[-1]
                if recent_max > recent_min:
                    price_position = (current_price - recent_min) / (recent_max - recent_min)
                    features['price_position_trend'] = price_position if not pd.isna(price_position) else 0.5
            
        except Exception as e:
            # Return empty dict on error - features will be skipped
            pass
        
        return features
    
    def _calculate_regime_stability(self) -> float:
        """Calculate regime stability score."""
        if len(self.regime_history) < 2:
            return 1.0
            
        # Count regime changes
        changes = sum(1 for i in range(1, len(self.regime_history)) 
                     if self.regime_history[i] != self.regime_history[i-1])
        
        stability = 1.0 - (changes / len(self.regime_history))
        return max(0.0, min(1.0, stability))
    
    def _generate_adaptive_features(self, data: pd.DataFrame, regime: RegimeType) -> Dict[str, Any]:
        """Generate regime-adaptive features."""
        features = {}
        
        if regime == RegimeType.TRENDING:
            # Trending regime features
            features['trend_strength'] = self._calculate_trend_strength(data)
            features['trend_persistence'] = self._calculate_trend_persistence(data)
            
        elif regime == RegimeType.MEAN_REVERTING:
            # Mean reverting regime features
            features['mean_reversion_strength'] = self._calculate_mean_reversion_strength(data)
            features['reversion_speed'] = self._calculate_reversion_speed(data)
            
        elif regime == RegimeType.VOLATILE:
            # Volatile regime features
            features['volatility_clustering'] = self._calculate_volatility_clustering(data)
            features['volatility_persistence'] = self._calculate_volatility_persistence(data)
            
        return features
    
    def _generate_transition_features(self) -> Dict[str, Any]:
        """Generate regime transition features."""
        if len(self.regime_history) < 2:
            return {}
            
        current_regime = self.regime_history[-1]
        previous_regime = self.regime_history[-2]
        
        return {
            'regime_transition': current_regime != previous_regime,
            'transition_from': previous_regime.value,
            'transition_to': current_regime.value
        }
    
    def _calculate_trend_strength(self, data: pd.DataFrame) -> float:
        """Calculate trend strength indicator."""
        try:
            returns = data['close'].pct_change().dropna()
            if len(returns) < self.regime_config.lookback_period:
                return 0.0
                
            # Simple trend strength calculation
            recent_returns = returns.tail(self.regime_config.lookback_period)
            trend_strength = abs(recent_returns.mean()) / recent_returns.std()
            return min(1.0, trend_strength)
        except:
            return 0.0
    
    def _calculate_trend_persistence(self, data: pd.DataFrame) -> float:
        """Calculate trend persistence indicator."""
        try:
            returns = data['close'].pct_change().dropna()
            if len(returns) < self.regime_config.lookback_period:
                return 0.0
                
            # Count consecutive positive/negative returns
            recent_returns = returns.tail(self.regime_config.lookback_period)
            signs = np.sign(recent_returns)
            persistence = np.sum(np.diff(signs) == 0) / len(signs)
            return persistence
        except:
            return 0.0
    
    def _calculate_mean_reversion_strength(self, data: pd.DataFrame) -> float:
        """Calculate mean reversion strength."""
        try:
            returns = data['close'].pct_change().dropna()
            if len(returns) < self.regime_config.lookback_period:
                return 0.0
                
            # Simple mean reversion calculation
            recent_returns = returns.tail(self.regime_config.lookback_period)
            autocorr = recent_returns.autocorr(lag=1)
            return abs(autocorr) if not np.isnan(autocorr) else 0.0
        except:
            return 0.0
    
    def _calculate_reversion_speed(self, data: pd.DataFrame) -> float:
        """Calculate reversion speed indicator."""
        try:
            returns = data['close'].pct_change().dropna()
            if len(returns) < self.regime_config.lookback_period:
                return 0.0
                
            # Calculate how quickly prices revert to mean
            recent_returns = returns.tail(self.regime_config.lookback_period)
            mean_return = recent_returns.mean()
            deviations = abs(recent_returns - mean_return)
            reversion_speed = 1.0 / (deviations.mean() + 1e-8)
            return min(1.0, reversion_speed)
        except:
            return 0.0
    
    def _calculate_volatility_clustering(self, data: pd.DataFrame) -> float:
        """Calculate volatility clustering indicator."""
        try:
            returns = data['close'].pct_change().dropna()
            if len(returns) < self.regime_config.lookback_period:
                return 0.0
                
            # Calculate volatility clustering
            recent_returns = returns.tail(self.regime_config.lookback_period)
            squared_returns = recent_returns ** 2
            autocorr = squared_returns.autocorr(lag=1)
            return abs(autocorr) if not np.isnan(autocorr) else 0.0
        except:
            return 0.0
    
    def _calculate_volatility_persistence(self, data: pd.DataFrame) -> float:
        """Calculate volatility persistence indicator."""
        try:
            returns = data['close'].pct_change().dropna()
            if len(returns) < self.regime_config.lookback_period:
                return 0.0
                
            # Calculate volatility persistence
            recent_returns = returns.tail(self.regime_config.lookback_period)
            volatility = recent_returns.rolling(window=5).std()
            autocorr = volatility.autocorr(lag=1)
            return abs(autocorr) if not np.isnan(autocorr) else 0.0
        except:
            return 0.0
    
    def _generate_feature(self, data: pd.DataFrame, **kwargs) -> pd.Series:
        """Generate regime integration features."""
        try:
            regime_features = self._generate_regime_features(data)
            
            # Convert to pandas Series
            feature_series = pd.Series(regime_features, index=[data.index[-1]])
            return feature_series
            
        except Exception as e:
            # Return default features on error
            default_features = {
                'regime_type': 'unknown',
                'regime_confidence': 0.0,
                'regime_duration': 0,
                'regime_stability': 0.0
            }
            return pd.Series(default_features, index=[data.index[-1]])


def generate_regime_features(
    data: pd.DataFrame,
    config: Optional[RegimeFeatureConfig] = None
) -> Dict[str, Any]:
    """
    Generate regime features for given data.
    
    Args:
        data: Market data DataFrame
        config: Regime feature configuration
        
    Returns:
        Dictionary of regime features
    """
    if config is None:
        config = RegimeFeatureConfig()
        
    generator = RegimeFeatureIntegration(config)
    return generator._generate_regime_features(data)


# Default regime feature generators
def create_default_regime_feature_generators() -> List[RegimeFeatureIntegration]:
    """Create default regime feature generators."""
    generators = []
    
    # Basic regime detection
    config = RegimeFeatureConfig(
        name="basic_regime_detection",
        enable_regime_detection=True,
        enable_adaptive_features=False,
        enable_regime_transitions=False
    )
    generators.append(RegimeFeatureIntegration(config))
    
    # Advanced regime features
    config = RegimeFeatureConfig(
        name="advanced_regime_features",
        enable_regime_detection=True,
        enable_adaptive_features=True,
        enable_regime_transitions=True
    )
    generators.append(RegimeFeatureIntegration(config))
    
    return generators
