# Combined Sizing Configuration
# This file defines indicators, weights, and thresholds for position and leverage sizing

indicators:
  # ML Confidence Indicators
  ml_confidence:
    description: "ML confidence scores for price movements"
    weight: 0.5
    source: "ml_confidence_predictor"
    
  # Adverse Movement Risk Indicators
  adverse_movement_risk:
    description: "Risk of adverse price movement"
    weight: 0.3
    source: "ml_confidence_predictor"
    
  # Volatility Indicators
  volatility:
    description: "Market volatility measures"
    weight: 0.1
    source: "analyst"
    
  # Market Sentiment Indicators
  market_sentiment:
    description: "Overall market sentiment"
    weight: 0.1
    source: "analyst"
    
  # Strategy Confidence Indicators
  strategy_confidence:
    description: "Strategy confidence from strategist"
    weight: 0.3
    source: "strategist"
    
  # Risk Score Indicators
  risk_score:
    description: "Risk assessment from strategist"
    weight: 0.2
    source: "strategist"
    
  # Entry Confidence Indicators
  entry_confidence:
    description: "Entry confidence from governor"
    weight: 0.2
    source: "governor"
    
  # Liquidation Safety Indicators
  liquidation_safety:
    description: "Liquidation safety ratio"
    weight: 0.3
    source: "governor"

weights:
  # Position Sizing Weights
  position_sizing:
    ml_weight: 0.4
    strategist_weight: 0.3
    analyst_weight: 0.2
    governor_weight: 0.1
    
  # Leverage Sizing Weights
  leverage_sizing:
    ml_weight: 0.4
    liquidation_risk_weight: 0.3
    strategist_weight: 0.2
    analyst_weight: 0.1

thresholds:
  # Volatility Thresholds
  volatility:
    low: 0.02
    medium: 0.03
    high: 0.05
    extreme: 0.08
    
  # Risk Score Thresholds
  risk_score:
    low: 0.3
    medium: 0.5
    high: 0.7
    extreme: 0.9
    
  # Market Sentiment Thresholds
  sentiment:
    very_bearish: 0.2
    bearish: 0.4
    neutral: 0.5
    bullish: 0.6
    very_bullish: 0.8
    
  # Liquidation Safety Thresholds
  liquidation_safety:
    dangerous: 0.3
    risky: 0.5
    safe: 0.6
    very_safe: 0.8
    
  # ML Confidence Thresholds
  ml_confidence:
    low: 0.4
    medium: 0.6
    high: 0.8
    very_high: 0.9
    
  # Adverse Movement Risk Thresholds
  adverse_risk:
    low: 0.2
    medium: 0.4
    high: 0.6
    extreme: 0.8

position_sizing:
  # Kelly Criterion Settings
  kelly_multiplier: 0.25
  max_position_size: 0.5
  min_position_size: 0.01
  
  # Confidence Thresholds
  confidence_threshold: 0.6
  
  # Risk Adjustment Factors
  risk_adjustment:
    volatility_factor: 0.8
    sentiment_factor: 0.9
    risk_score_factor: 0.7

leverage_sizing:
  # Leverage Limits
  max_leverage: 100.0
  min_leverage: 10.0
  
  # Confidence Thresholds
  confidence_threshold: 0.7
  risk_tolerance: 0.3
  
  # Risk Adjustment Factors
  risk_adjustment:
    volatility_factor: 0.6
    liquidation_safety_factor: 0.8
    risk_score_factor: 0.7

# Continuous Monitoring Settings
continuous_monitoring:
  # Monitoring Intervals
  check_interval: 30  # seconds
  update_interval: 60  # seconds
    
  # Position Management
  position_management:
    partial_exit_threshold: 0.6
    full_exit_threshold: 0.8
    trailing_stop_enabled: true
    trailing_stop_distance: 0.5  # percentage

# Direction-Neutral Settings
direction_neutral:
  # Target Levels (0-2% for high leverage)
  target_levels:
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    - 0.6
    - 0.7
    - 0.8
    - 0.9
    - 1.0
    - 1.1
    - 1.2
    - 1.3
    - 1.4
    - 1.5
    - 1.6
    - 1.7
    - 1.8
    - 1.9
    - 2.0
    
  # Direction Detection
  direction_detection:
    confidence_threshold: 0.6
    risk_threshold: 0.4
    min_target_difference: 0.2  # percentage
    
  # Entry Criteria
  entry_criteria:
    min_confidence: 0.7
    max_adverse_risk: 0.5
    min_safety_score: 0.6
    max_liquidation_risk: 0.6
