"""
Core interfaces and base classes for the unified feature generation system.

This module defines the fundamental interfaces that all feature generators
must implement, ensuring consistency and interoperability across the system.
"""

import asyncio
import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Union, Callable, Tuple
from datetime import datetime
import pandas as pd
import numpy as np
from pathlib import Path

from ...utils.logger import system_logger
from ...core.decorators import handles_errors


class FeatureCategory(Enum):
    """Categories for organizing feature generators."""
    TECHNICAL_INDICATORS = "technical_indicators"
    STATISTICAL_FEATURES = "statistical_features"
    MICROSTRUCTURE = "microstructure"
    VOLATILITY = "volatility"
    MOMENTUM = "momentum"
    VOLUME = "volume"
    TIME_SERIES = "time_series"
    CROSS_TIMEFRAME = "cross_timeframe"
    META_LABELING = "meta_labeling"
    PATTERN_RECOGNITION = "pattern_recognition"
    REGIME_DETECTION = "regime_detection"
    LIQUIDITY = "liquidity"
    CUSTOM = "custom"


class FeaturePriority(Enum):
    """Priority levels for feature generation ordering."""
    CRITICAL = 1
    HIGH = 2
    MEDIUM = 3
    LOW = 4
    OPTIONAL = 5


@dataclass
class FeatureGeneratorConfig:
    """Configuration for feature generators."""
    name: str
    category: FeatureCategory
    priority: FeaturePriority = FeaturePriority.MEDIUM
    enabled: bool = True
    parameters: Dict[str, Any] = field(default_factory=dict)
    dependencies: List[str] = field(default_factory=list)
    output_columns: List[str] = field(default_factory=list)
    validation_rules: Dict[str, Any] = field(default_factory=dict)
    performance_targets: Dict[str, float] = field(default_factory=dict)
    memory_limit_mb: Optional[int] = None
    timeout_seconds: Optional[int] = None


@dataclass
class FeatureGenerationResult:
    """Result of feature generation operation."""
    success: bool
    features: Optional[pd.DataFrame] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    performance_metrics: Dict[str, float] = field(default_factory=dict)
    generated_at: datetime = field(default_factory=datetime.now)
    
    def is_valid(self) -> bool:
        """Check if the result is valid."""
        return self.success and self.features is not None and not self.errors


class FeatureGenerator(ABC):
    """
    Base interface for all feature generators.
    
    This abstract base class defines the contract that all feature generators
    must implement, ensuring consistency and interoperability.
    """
    
    def __init__(self, config: FeatureGeneratorConfig):
        """
        Initialize the feature generator.
        
        Args:
            config: Configuration for the feature generator
        """
        self.config = config
        self.logger = system_logger.getChild(f"FeatureGenerator.{config.name}")
        self._is_initialized = False
        self._performance_metrics = {}
        
    @abstractmethod
    async def initialize(self) -> bool:
        """
        Initialize the feature generator.
        
        Returns:
            True if initialization successful, False otherwise
        """
        pass
    
    @abstractmethod
    async def generate_features(
        self, 
        data: pd.DataFrame,
        context: Optional[Dict[str, Any]] = None
    ) -> FeatureGenerationResult:
        """
        Generate features from input data.
        
        Args:
            data: Input data for feature generation
            context: Additional context information
            
        Returns:
            FeatureGenerationResult containing generated features
        """
        pass
    
    @abstractmethod
    def get_required_columns(self) -> List[str]:
        """
        Get the columns required by this feature generator.
        
        Returns:
            List of required column names
        """
        pass
    
    @abstractmethod
    def get_output_columns(self) -> List[str]:
        """
        Get the columns that will be generated by this feature generator.
        
        Returns:
            List of output column names
        """
        pass
    
    def validate_input(self, data: pd.DataFrame) -> Tuple[bool, List[str]]:
        """
        Validate input data for this feature generator.
        
        Args:
            data: Input data to validate
            
        Returns:
            Tuple of (is_valid, error_messages)
        """
        errors = []
        
        # Check if data is empty
        if data.empty:
            errors.append("Input data is empty")
            return False, errors
            
        # Check required columns
        required_columns = self.get_required_columns()
        missing_columns = [col for col in required_columns if col not in data.columns]
        if missing_columns:
            errors.append(f"Missing required columns: {missing_columns}")
            
        # Check data types if specified in config
        if 'required_dtypes' in self.config.validation_rules:
            for col, expected_dtype in self.config.validation_rules['required_dtypes'].items():
                if col in data.columns and not data[col].dtype == expected_dtype:
                    errors.append(f"Column {col} has wrong dtype. Expected {expected_dtype}, got {data[col].dtype}")
        
        return len(errors) == 0, errors
    
    def validate_output(self, features: pd.DataFrame) -> Tuple[bool, List[str]]:
        """
        Validate output features.
        
        Args:
            features: Generated features to validate
            
        Returns:
            Tuple of (is_valid, error_messages)
        """
        errors = []
        
        if features is None or features.empty:
            errors.append("No features generated")
            return False, errors
            
        # Check for NaN values
        nan_columns = features.columns[features.isnull().any()].tolist()
        if nan_columns:
            errors.append(f"Features contain NaN values in columns: {nan_columns}")
            
        # Check for infinite values
        inf_columns = features.columns[np.isinf(features).any()].tolist()
        if inf_columns:
            errors.append(f"Features contain infinite values in columns: {inf_columns}")
            
        # Check expected output columns
        expected_columns = self.get_output_columns()
        missing_output = [col for col in expected_columns if col not in features.columns]
        if missing_output:
            errors.append(f"Missing expected output columns: {missing_output}")
            
        return len(errors) == 0, errors
    
    def get_performance_metrics(self) -> Dict[str, float]:
        """Get performance metrics for this generator."""
        return self._performance_metrics.copy()
    
    def is_initialized(self) -> bool:
        """Check if the generator is initialized."""
        return self._is_initialized
    
    def get_info(self) -> Dict[str, Any]:
        """Get information about this feature generator."""
        return {
            "name": self.config.name,
            "category": self.config.category.value,
            "priority": self.config.priority.value,
            "enabled": self.config.enabled,
            "initialized": self._is_initialized,
            "required_columns": self.get_required_columns(),
            "output_columns": self.get_output_columns(),
            "performance_metrics": self.get_performance_metrics()
        }


class CompositeFeatureGenerator(FeatureGenerator):
    """
    A feature generator that combines multiple other generators.
    
    This allows for complex feature generation pipelines while maintaining
    the same interface as individual generators.
    """
    
    def __init__(self, config: FeatureGeneratorConfig, generators: List[FeatureGenerator]):
        """
        Initialize composite feature generator.
        
        Args:
            config: Configuration for the composite generator
            generators: List of feature generators to combine
        """
        super().__init__(config)
        self.generators = generators
        self._generator_map = {gen.config.name: gen for gen in generators}
        
    async def initialize(self) -> bool:
        """Initialize all sub-generators."""
        try:
            self.logger.info(f"Initializing composite generator with {len(self.generators)} sub-generators")
            
            for generator in self.generators:
                if not await generator.initialize():
                    self.logger.error(f"Failed to initialize generator: {generator.config.name}")
                    return False
                    
            self._is_initialized = True
            self.logger.info("Composite generator initialized successfully")
            return True
            
        except Exception as e:
            self.logger.error(f"Error initializing composite generator: {e}")
            return False
    
    async def generate_features(
        self, 
        data: pd.DataFrame,
        context: Optional[Dict[str, Any]] = None
    ) -> FeatureGenerationResult:
        """Generate features using all sub-generators."""
        if not self._is_initialized:
            return FeatureGenerationResult(
                success=False,
                errors=["Composite generator not initialized"]
            )
            
        try:
            all_features = []
            all_errors = []
            all_warnings = []
            performance_metrics = {}
            
            # Generate features using each sub-generator
            for generator in self.generators:
                if not generator.config.enabled:
                    continue
                    
                result = await generator.generate_features(data, context)
                
                if result.success and result.features is not None:
                    all_features.append(result.features)
                else:
                    all_errors.extend(result.errors)
                    
                all_warnings.extend(result.warnings)
                performance_metrics.update(result.performance_metrics)
            
            # Combine all features
            if all_features:
                combined_features = pd.concat(all_features, axis=1)
                # Remove duplicate columns
                combined_features = combined_features.loc[:, ~combined_features.columns.duplicated()]
                
                return FeatureGenerationResult(
                    success=True,
                    features=combined_features,
                    metadata={"generator_count": len(self.generators)},
                    errors=all_errors,
                    warnings=all_warnings,
                    performance_metrics=performance_metrics
                )
            else:
                return FeatureGenerationResult(
                    success=False,
                    errors=all_errors,
                    warnings=all_warnings,
                    performance_metrics=performance_metrics
                )
                
        except Exception as e:
            self.logger.error(f"Error in composite feature generation: {e}")
            return FeatureGenerationResult(
                success=False,
                errors=[f"Composite generation error: {str(e)}"]
            )
    
    def get_required_columns(self) -> List[str]:
        """Get all required columns from sub-generators."""
        required = set()
        for generator in self.generators:
            required.update(generator.get_required_columns())
        return list(required)
    
    def get_output_columns(self) -> List[str]:
        """Get all output columns from sub-generators."""
        output = set()
        for generator in self.generators:
            output.update(generator.get_output_columns())
        return list(output)
    
    def get_generator(self, name: str) -> Optional[FeatureGenerator]:
        """Get a specific sub-generator by name."""
        return self._generator_map.get(name)
    
    def add_generator(self, generator: FeatureGenerator) -> None:
        """Add a new sub-generator."""
        self.generators.append(generator)
        self._generator_map[generator.config.name] = generator
        
    def remove_generator(self, name: str) -> bool:
        """Remove a sub-generator by name."""
        if name in self._generator_map:
            generator = self._generator_map.pop(name)
            self.generators.remove(generator)
            return True
        return False