"""Type stubs for common_operations"""

from typing import Any, Dict, List, Optional, Union, Callable, Generator, Tuple
import datetime
import pandas as pd
import numpy as np
from pathlib import Path
from collections import defaultdict, Counter, deque
import asyncio
import logging
import argparse

# DateTime utilities
def get_current_datetime() -> datetime.datetime: ...
def get_today() -> datetime.date: ...
def format_datetime(dt: datetime.datetime, fmt: str = ...) -> str: ...
def parse_datetime(date_string: str, fmt: str = ...) -> datetime.datetime: ...

# DataFrame operations
def create_empty_dataframe(columns: List[str]) -> pd.DataFrame: ...
def safe_fillna(df: pd.DataFrame, value: Any = ...) -> pd.DataFrame: ...
def safe_rolling(df: pd.DataFrame, window: int, min_periods: int = ...) -> pd.core.window.Rolling: ...
def safe_copy(df: pd.DataFrame, deep: bool = ...) -> pd.DataFrame: ...
def safe_deepcopy(obj: Any) -> Any: ...
def safe_resample(df: pd.DataFrame, rule: str, agg_dict: Optional[Dict[str, str]] = ...) -> pd.DataFrame: ...
def align_dataframes(*dfs: pd.DataFrame, method: str = ...) -> List[pd.DataFrame]: ...

# Numeric operations
def safe_mean(values: Union[List, np.ndarray, pd.Series]) -> float: ...
def safe_std(values: Union[List, np.ndarray, pd.Series]) -> float: ...

# File operations
def ensure_directory(path: Union[str, Path]) -> Path: ...
def safe_file_exists(path: Union[str, Path]) -> bool: ...
def safe_json_dump(data: Any, file_path: Union[str, Path], **kwargs) -> None: ...
def safe_json_load(file_path: Union[str, Path]) -> Any: ...
def safe_glob(pattern: str, recursive: bool = ...) -> List[Path]: ...
def list_files(directory: Union[str, Path], pattern: str = ..., suffix: Optional[str] = ...) -> List[Path]: ...
def get_latest_file(directory: Union[str, Path], pattern: str = ...) -> Optional[Path]: ...

# Parquet operations
def safe_read_parquet(file_path: Union[str, Path], columns: Optional[List[str]] = ...) -> pd.DataFrame: ...
def safe_to_parquet(df: pd.DataFrame, file_path: Union[str, Path], **kwargs) -> bool: ...
def list_parquet_files(directory: Union[str, Path], recursive: bool = ...) -> List[Path]: ...

# Hashing and cache operations
def generate_hash(data: Union[str, bytes, pd.DataFrame], algorithm: str = ...) -> str: ...
def generate_cache_key(prefix: str, *args, max_length: int = ...) -> str: ...

# Async utilities
async def safe_sleep(seconds: float) -> None: ...
async def safe_gather(*coroutines, return_exceptions: bool = ...): ...
def create_async_task(coroutine) -> asyncio.Task: ...

# Collection utilities
def safe_append(lst: List[Any], item: Any) -> List[Any]: ...
def safe_extend(lst: List[Any], items: List[Any]) -> List[Any]: ...
def safe_dict_get(d: Dict[Any, Any], key: Any, default: Any = ...) -> Any: ...
def safe_dict_items(d: Dict[Any, Any]) -> List[tuple]: ...
def safe_defaultdict(default_factory: Callable) -> defaultdict: ...
def safe_counter(items: Optional[List[Any]] = ...) -> Counter: ...
def safe_deque(items: Optional[List[Any]] = ..., maxlen: Optional[int] = ...) -> deque: ...

# String operations
def safe_lower(s: str) -> str: ...
def safe_upper(s: str) -> str: ...
def safe_join(separator: str, items: List[Any]) -> str: ...

# Logging utilities
def get_logger(name: str) -> logging.Logger: ...
def setup_basic_logging(level: int = ...) -> None: ...

# Argument parsing utilities
def create_argument_parser(description: str) -> argparse.ArgumentParser: ...
def add_common_arguments(parser: argparse.ArgumentParser) -> None: ...

# Exception handling utilities
def safe_exception_handler(func: Callable) -> Callable: ...

# Type conversion utilities
def safe_float(value: Any, default: float = ...) -> float: ...
def safe_int(value: Any, default: int = ...) -> int: ...

# Optuna utilities
def suggest_float_uniform(trial: Any, name: str, low: float, high: float) -> float: ...
def suggest_int_uniform(trial: Any, name: str, low: int, high: int) -> int: ...

# Validation utilities
def validate_dataframe(df: pd.DataFrame, required_columns: List[str]) -> bool: ...
def validate_numeric_range(value: float, min_val: float, max_val: float) -> bool: ...
def validate_dataframe_schema(df: pd.DataFrame, required_columns: List[str], 
                            column_types: Optional[Dict[str, type]] = ...) -> Tuple[bool, List[str]]: ...
def validate_data_quality(df: pd.DataFrame, max_nan_ratio: float = ..., 
                        check_duplicates: bool = ...) -> Dict[str, Any]: ...

# Memory optimization utilities
def optimize_dataframe_dtypes(df: pd.DataFrame) -> pd.DataFrame: ...

# Progress and timing utilities
def timed_operation(operation_name: str) -> Callable: ...
def format_bytes(size_bytes: int) -> str: ...

# Batch processing utilities
def chunked_iterable(iterable: List[Any], chunk_size: int) -> List[List[Any]]: ...
def parallel_map(func: Callable, items: List[Any], max_workers: Optional[int] = ...) -> List[Any]: ...

# MLflow integration helpers
def safe_log_metric(key: str, value: float, step: Optional[int] = ...) -> None: ...
def safe_log_params(params: Dict[str, Any]) -> None: ...
def safe_log_artifact(file_path: Union[str, Path]) -> None: ...
