"""Type stubs for common_operations module.

This file provides comprehensive type hints for all functions in common_operations.py.
"""

import argparse
import asyncio
import datetime
import logging
from collections import Counter, defaultdict, deque
from collections.abc import Awaitable, Callable
from pathlib import Path
from typing import Any, TypeVar, Union

import numpy as np
import pandas as pd
from numpy.typing import NDArray

# Type aliases
PathLike = Union[str, Path]
NumericArray = Union[list[int | float], NDArray[np.number], pd.Series]
JSONSerializable = Union[None, bool, int, float, str, list["JSONSerializable"], dict[str, "JSONSerializable"]]
T = TypeVar("T")

# DateTime utilities
def get_current_datetime() -> datetime.datetime: ...
def get_today() -> datetime.date: ...
def format_datetime(dt: datetime.datetime, fmt: str = ...) -> str: ...
def parse_datetime(date_string: str, fmt: str = ...) -> datetime.datetime: ...

# DataFrame operations
def create_empty_dataframe(columns: list[str]) -> pd.DataFrame: ...
def safe_fillna(df: pd.DataFrame, value: Any = ...) -> pd.DataFrame: ...
def safe_rolling(df: pd.DataFrame, window: int, min_periods: int = ...) -> pd.core.window.Rolling: ...
def safe_copy(df: pd.DataFrame, deep: bool = ...) -> pd.DataFrame: ...
def safe_deepcopy(obj: Any) -> Any: ...
def safe_resample(df: pd.DataFrame, rule: str, agg_dict: dict[str, str] | None = ...) -> pd.DataFrame: ...
def align_dataframes(*dfs: pd.DataFrame, method: str = ...) -> list[pd.DataFrame]: ...

# Numeric operations
def safe_mean(values: list | np.ndarray | pd.Series) -> float: ...
def safe_std(values: list | np.ndarray | pd.Series) -> float: ...

# File operations
def ensure_directory(path: PathLike) -> Path: ...
def safe_file_exists(path: PathLike) -> bool: ...
def safe_json_dump(data: JSONSerializable, file_path: PathLike, **kwargs: Any) -> None: ...
def safe_json_load(file_path: PathLike) -> Any: ...
def safe_glob(pattern: str, recursive: bool = ...) -> list[Path]: ...
def list_files(directory: PathLike, pattern: str = ..., suffix: str | None = ...) -> list[Path]: ...
def get_latest_file(directory: PathLike, pattern: str = ...) -> Path | None: ...

# Parquet operations
def safe_read_parquet(file_path: PathLike, columns: list[str] | None = ...) -> pd.DataFrame: ...
def safe_to_parquet(df: pd.DataFrame, file_path: PathLike, **kwargs: Any) -> bool: ...
def list_parquet_files(directory: PathLike, recursive: bool = ...) -> list[Path]: ...

# Hashing and cache operations
def generate_hash(data: str | bytes | pd.DataFrame, algorithm: str = ...) -> str: ...
def generate_cache_key(prefix: str, *args, max_length: int = ...) -> str: ...

# Async utilities
async def safe_sleep(seconds: float) -> None: ...
async def safe_gather(*coroutines: Awaitable[T], return_exceptions: bool = ...) -> list[T | BaseException]: ...
def create_async_task(coroutine: Awaitable[T]) -> asyncio.Task[T]: ...

# Collection utilities
def safe_append(lst: list[Any], item: Any) -> list[Any]: ...
def safe_extend(lst: list[Any], items: list[Any]) -> list[Any]: ...
def safe_dict_get(d: dict[Any, Any], key: Any, default: Any = ...) -> Any: ...
def safe_dict_items(d: dict[Any, Any]) -> list[tuple]: ...
def safe_defaultdict(default_factory: Callable) -> defaultdict: ...
def safe_counter(items: list[Any] | None = ...) -> Counter: ...
def safe_deque(items: list[Any] | None = ..., maxlen: int | None = ...) -> deque: ...

# String operations
def safe_lower(s: str) -> str: ...
def safe_upper(s: str) -> str: ...
def safe_join(separator: str, items: list[Any]) -> str: ...

# Logging utilities
def get_logger(name: str) -> logging.Logger: ...
def setup_basic_logging(level: int = ...) -> None: ...

# Argument parsing utilities
def create_argument_parser(description: str) -> argparse.ArgumentParser: ...
def add_common_arguments(parser: argparse.ArgumentParser) -> None: ...

# Exception handling utilities
def safe_exception_handler(func: Callable) -> Callable: ...

# Type conversion utilities
def safe_float(value: Any, default: float = ...) -> float: ...
def safe_int(value: Any, default: int = ...) -> int: ...

# Optuna utilities
def suggest_float_uniform(trial: Any, name: str, low: float, high: float) -> float: ...
def suggest_int_uniform(trial: Any, name: str, low: int, high: int) -> int: ...

# Validation utilities
def validate_dataframe(df: pd.DataFrame, required_columns: list[str]) -> bool: ...
def validate_numeric_range(value: float, min_val: float, max_val: float) -> bool: ...
def validate_dataframe_schema(df: pd.DataFrame, required_columns: list[str],
                            column_types: dict[str, type] | None = ...) -> tuple[bool, list[str]]: ...
def validate_data_quality(df: pd.DataFrame, max_nan_ratio: float = ...,
                        check_duplicates: bool = ...) -> dict[str, Any]: ...

# Memory optimization utilities
def optimize_dataframe_dtypes(df: pd.DataFrame) -> pd.DataFrame: ...

# Progress and timing utilities
def timed_operation(operation_name: str) -> Callable: ...
def format_bytes(size_bytes: int) -> str: ...

# Batch processing utilities
def chunked_iterable(iterable: list[Any], chunk_size: int) -> list[list[Any]]: ...
def parallel_map(func: Callable, items: list[Any], max_workers: int | None = ...) -> list[Any]: ...

# MLflow integration helpers
def safe_log_metric(key: str, value: float, step: int | None = ...) -> None: ...
def safe_log_params(params: dict[str, Any]) -> None: ...
def safe_log_artifact(file_path: str | Path) -> None: ...
