"""
Enhanced Pre-training artifact manager.

Provides a centralized interface for saving and retrieving intermediate
artifacts (dataframes, series, metadata) generated by the unified
pre-training pipeline steps. Supports optional spilling of large
artifacts to disk to keep memory usage bounded.

Enhanced with:
- Robust error handling with retry mechanisms
- Compression support for storage optimization
- Comprehensive metadata tracking and artifact lineage
- Thread safety and concurrent access protection
- Performance monitoring and metrics collection
- Intelligent caching strategies with memory management
"""

from __future__ import annotations

import asyncio
import logging
import shutil
import uuid
import json
import time
import threading
from dataclasses import dataclass, field, asdict
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, Optional, List, Set, Tuple, Union
from collections import defaultdict, deque
from enum import Enum
import weakref
import hashlib
import pickle
import gzip
import lz4.frame
import psutil

import pandas as pd
import numpy as np


class CompressionType(Enum):
    """Supported compression algorithms."""
    NONE = "none"
    GZIP = "gzip"
    LZ4 = "lz4"
    AUTO = "auto"  # Automatically choose best compression


class OperationType(Enum):
    """Types of artifact operations."""
    SAVE = "save"
    LOAD = "load"
    DELETE = "delete"
    LIST = "list"


class RetryStrategy(Enum):
    """Retry strategies for failed operations."""
    EXPONENTIAL_BACKOFF = "exponential_backoff"
    LINEAR_BACKOFF = "linear_backoff"
    FIXED_DELAY = "fixed_delay"


@dataclass
class RetryConfig:
    """Configuration for retry mechanisms."""
    max_retries: int = 3
    base_delay: float = 1.0
    max_delay: float = 60.0
    strategy: RetryStrategy = RetryStrategy.EXPONENTIAL_BACKOFF
    retryable_exceptions: Tuple[type, ...] = (OSError, IOError, ConnectionError)


@dataclass
class CompressionConfig:
    """Configuration for artifact compression."""
    enabled: bool = True
    algorithm: CompressionType = CompressionType.AUTO
    min_size_mb: float = 10.0
    compression_level: int = 6
    enable_for_memory: bool = True
    enable_for_disk: bool = True


@dataclass
class MemoryConfig:
    """Configuration for memory management."""
    max_memory_mb: float = 2000.0
    cache_memory_mb: float = 500.0
    spill_threshold_mb: float = 150.0
    cleanup_interval_seconds: float = 300.0
    enable_gc_collection: bool = True


@dataclass
class ArtifactMetadata:
    """Enhanced metadata for artifacts."""
    artifact_key: str
    step_name: str
    artifact_type: str
    size_bytes: int
    compressed_size_bytes: Optional[int] = None
    checksum: str = ""
    created_at: datetime = field(default_factory=datetime.utcnow)
    modified_at: datetime = field(default_factory=datetime.utcnow)
    compression_used: CompressionType = CompressionType.NONE
    storage_location: str = "memory"
    parent_artifacts: List[str] = field(default_factory=list)
    tags: Dict[str, str] = field(default_factory=dict)
    description: str = ""
    version: str = "1.0"


@dataclass
class OperationMetrics:
    """Metrics for artifact operations."""
    operation_type: OperationType
    artifact_key: str
    step_name: str
    duration_seconds: float
    success: bool
    error_message: Optional[str] = None
    retry_count: int = 0
    bytes_processed: int = 0
    compression_ratio: float = 1.0
    timestamp: datetime = field(default_factory=datetime.utcnow)


@dataclass
class CacheEntry:
    """Cache entry with metadata."""
    artifact_key: str
    data: Any
    metadata: ArtifactMetadata
    last_accessed: datetime = field(default_factory=datetime.utcnow)
    access_count: int = 0
    memory_size_mb: float = 0.0


class ArtifactKeys:
    """Standard artifact keys shared across pre-training steps."""

    # Data validation step artifacts
    RAW_DATAFRAME = "raw_dataframe"
    VALIDATED_DATAFRAME = "validated_dataframe"
    VALIDATION_METRICS = "validation_metrics"
    VALIDATION_WARNINGS = "validation_warnings"
    DATA_QUALITY_SCORES = "data_quality_scores"

    # Labeling integration step artifacts
    LABELED_DATAFRAME = "labeled_dataframe"
    TARGETS = "targets"
    LABELING_METRICS = "labeling_metrics"
    LABELING_QUALITY_SCORES = "labeling_quality_scores"
    LABELING_WARNINGS = "labeling_warnings"

    # Feature generation step artifacts
    FEATURE_DATAFRAME = "feature_dataframe"
    FEATURE_NAMES = "feature_names"
    FEATURE_CATEGORIES = "feature_categories"
    FEATURE_GENERATION_METRICS = "feature_generation_metrics"
    FEATURE_GENERATION_STATS = "feature_generation_stats"
    FEATURE_OPTIMIZATION_STATS = "feature_optimization_stats"

    # Feature selection step artifacts
    SELECTED_FEATURES = "selected_features"
    FEATURE_SELECTION_SCORES = "feature_selection_scores"
    FEATURE_IMPORTANCE_RANKINGS = "feature_importance_rankings"
    SELECTION_METRICS = "selection_metrics"
    SELECTION_PERFORMANCE = "selection_performance"
    FEATURE_REDUNDANCY_ANALYSIS = "feature_redundancy_analysis"

    # Period/lookback optimization step artifacts
    OPTIMIZED_PERIODS = "optimized_periods"
    OPTIMIZED_LOOKBACKS = "optimized_lookbacks"
    PERIOD_OPTIMIZATION_METRICS = "period_optimization_metrics"
    LOOKBACK_OPTIMIZATION_METRICS = "lookback_optimization_metrics"
    OPTIMIZATION_CONSTRAINTS = "optimization_constraints"
    CORRELATION_ANALYSIS = "correlation_analysis"
    OPTIMIZED_FEATURE_DATAFRAME = "optimized_feature_dataframe"

    # Interaction generation step artifacts
    INTERACTION_FEATURES = "interaction_features"
    INTERACTION_METADATA = "interaction_metadata"
    INTERACTION_GENERATION_METRICS = "interaction_generation_metrics"
    INTERACTION_PERFORMANCE = "interaction_performance"
    INTERACTION_QUALITY_SCORES = "interaction_quality_scores"

    # Vectorization step artifacts
    VECTORIZED_FEATURES = "vectorized_features"
    VECTORIZATION_METADATA = "vectorization_metadata"
    VECTORIZATION_PERFORMANCE = "vectorization_performance"
    VECTORIZATION_METRICS = "vectorization_metrics"
    VECTORIZATION_OPTIMIZATION = "vectorization_optimization"

    # Final validation step artifacts
    FINAL_DATASET = "final_dataset"
    FINAL_VALIDATION_METRICS = "final_validation_metrics"
    FINAL_QUALITY_SCORES = "final_quality_scores"
    FINAL_VALIDATION_WARNINGS = "final_validation_warnings"
    FINAL_PERFORMANCE_METRICS = "final_performance_metrics"

    # Cross-step artifacts
    PIPELINE_METADATA = "pipeline_metadata"
    STEP_EXECUTION_TIMES = "step_execution_times"
    MEMORY_USAGE_TRACKING = "memory_usage_tracking"
    ERROR_LOG = "error_log"
    WARNING_LOG = "warning_log"


_DATA_VALIDATION_KEYS = frozenset({
    ArtifactKeys.RAW_DATAFRAME,
    ArtifactKeys.VALIDATED_DATAFRAME,
    ArtifactKeys.VALIDATION_METRICS,
    ArtifactKeys.VALIDATION_WARNINGS,
    ArtifactKeys.DATA_QUALITY_SCORES,
})

_LABELING_KEYS = frozenset({
    ArtifactKeys.LABELED_DATAFRAME,
    ArtifactKeys.TARGETS,
    ArtifactKeys.LABELING_METRICS,
    ArtifactKeys.LABELING_QUALITY_SCORES,
    ArtifactKeys.LABELING_WARNINGS,
})

_FEATURE_GENERATION_KEYS = frozenset({
    ArtifactKeys.FEATURE_DATAFRAME,
    ArtifactKeys.FEATURE_NAMES,
    ArtifactKeys.FEATURE_CATEGORIES,
    ArtifactKeys.FEATURE_GENERATION_METRICS,
    ArtifactKeys.FEATURE_GENERATION_STATS,
    ArtifactKeys.FEATURE_OPTIMIZATION_STATS,
})

_FEATURE_SELECTION_KEYS = frozenset({
    ArtifactKeys.SELECTED_FEATURES,
    ArtifactKeys.FEATURE_SELECTION_SCORES,
    ArtifactKeys.FEATURE_IMPORTANCE_RANKINGS,
    ArtifactKeys.SELECTION_METRICS,
    ArtifactKeys.SELECTION_PERFORMANCE,
    ArtifactKeys.FEATURE_REDUNDANCY_ANALYSIS,
})

_PERIOD_LOOKBACK_KEYS = frozenset({
    ArtifactKeys.OPTIMIZED_PERIODS,
    ArtifactKeys.OPTIMIZED_LOOKBACKS,
    ArtifactKeys.PERIOD_OPTIMIZATION_METRICS,
    ArtifactKeys.LOOKBACK_OPTIMIZATION_METRICS,
    ArtifactKeys.OPTIMIZATION_CONSTRAINTS,
    ArtifactKeys.CORRELATION_ANALYSIS,
    ArtifactKeys.OPTIMIZED_FEATURE_DATAFRAME,
})

_INTERACTION_KEYS = frozenset({
    ArtifactKeys.INTERACTION_FEATURES,
    ArtifactKeys.INTERACTION_METADATA,
    ArtifactKeys.INTERACTION_GENERATION_METRICS,
    ArtifactKeys.INTERACTION_PERFORMANCE,
    ArtifactKeys.INTERACTION_QUALITY_SCORES,
})

_VECTORIZATION_KEYS = frozenset({
    ArtifactKeys.VECTORIZED_FEATURES,
    ArtifactKeys.VECTORIZATION_METADATA,
    ArtifactKeys.VECTORIZATION_PERFORMANCE,
    ArtifactKeys.VECTORIZATION_METRICS,
    ArtifactKeys.VECTORIZATION_OPTIMIZATION,
})

_FINAL_VALIDATION_KEYS = frozenset({
    ArtifactKeys.FINAL_DATASET,
    ArtifactKeys.FINAL_VALIDATION_METRICS,
    ArtifactKeys.FINAL_QUALITY_SCORES,
    ArtifactKeys.FINAL_VALIDATION_WARNINGS,
    ArtifactKeys.FINAL_PERFORMANCE_METRICS,
})

STEP_NAME_ALIASES: Dict[str, str] = {
    'data_validation': 'feature_generation_data_validation_step',
    'labeling_integration': 'feature_generation_labeling_integration_step',
    'feature_generation': 'feature_generation_feature_generation_step',
    'feature_selection': 'feature_generation_feature_selection_step',
    'period_lookback_optimization': 'feature_generation_period_lookback_optimization_step',
    'interaction_generation': 'feature_generation_interaction_generation_step',
    'vectorization': 'feature_generation_vectorization_step',
    'final_validation': 'feature_generation_final_validation_step',
}

_STEP_KEY_MAP: Dict[str, frozenset[str]] = {
    'feature_generation_data_validation_step': _DATA_VALIDATION_KEYS,
    'feature_generation_labeling_integration_step': _LABELING_KEYS,
    'feature_generation_feature_generation_step': _FEATURE_GENERATION_KEYS,
    'feature_generation_feature_selection_step': _FEATURE_SELECTION_KEYS,
    'feature_generation_period_lookback_optimization_step': _PERIOD_LOOKBACK_KEYS,
    'feature_generation_interaction_generation_step': _INTERACTION_KEYS,
    'feature_generation_vectorization_step': _VECTORIZATION_KEYS,
    'feature_generation_final_validation_step': _FINAL_VALIDATION_KEYS,
}

# Register alias mappings to the same key sets
for alias, canonical in STEP_NAME_ALIASES.items():
    if canonical in _STEP_KEY_MAP:
        _STEP_KEY_MAP[alias] = _STEP_KEY_MAP[canonical]

_REVERSE_STEP_ALIASES: Dict[str, Set[str]] = defaultdict(set)
for alias, canonical in STEP_NAME_ALIASES.items():
    _REVERSE_STEP_ALIASES[canonical].add(alias)


def canonical_step_name(step_name: str) -> str:
    """Resolve a step name to its canonical representation."""
    if not step_name:
        return step_name
    return STEP_NAME_ALIASES.get(step_name, step_name)


def get_default_step_for_key(key: str) -> Optional[str]:
    """Infer the canonical step name that owns a given artifact key."""
    for step, keys in _STEP_KEY_MAP.items():
        if key in keys:
            return canonical_step_name(step)
    return None


def get_registered_keys_for_step(step_name: str) -> Set[str]:
    """Return the set of known artifact keys for a step (including aliases)."""
    canonical = canonical_step_name(step_name)
    keys = set(_STEP_KEY_MAP.get(canonical, frozenset()))
    for alias in _REVERSE_STEP_ALIASES.get(canonical, set()):
        keys.update(_STEP_KEY_MAP.get(alias, frozenset()))
    return keys


@dataclass
class ArtifactConfig:
    """Enhanced configuration controlling artifact persistence behaviour."""

    spill_threshold_mb: float = 150.0
    base_dir: Path = Path("artifacts/pre_training/artifact_store")
    cache_materialized: bool = True
    max_runs_to_keep: int = 3

    # Enhanced configuration options
    compression: CompressionConfig = field(default_factory=CompressionConfig)
    memory: MemoryConfig = field(default_factory=MemoryConfig)
    retry: RetryConfig = field(default_factory=RetryConfig)

    # Performance and monitoring
    enable_metrics: bool = True
    enable_thread_safety: bool = True
    enable_compression: bool = True
    enable_caching: bool = True

    # Cleanup and maintenance
    cleanup_interval_seconds: float = 300.0
    enable_health_checks: bool = True


@dataclass
class StoredArtifact:
    """Representation of a stored artifact entry."""

    kind: str
    key: str
    value: Any = None
    path: Optional[Path] = None
    size_bytes: Optional[int] = None
    shape: Optional[Any] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


class PreTrainingArtifactManager:
    """
    Enhanced centralized artifact storage with optional disk spilling.

    Features:
    - Robust error handling with retry mechanisms
    - Compression support for storage optimization
    - Comprehensive metadata tracking and artifact lineage
    - Thread safety and concurrent access protection
    - Performance monitoring and metrics collection
    - Intelligent caching strategies with memory management
    """

    def __init__(self, config: Optional[ArtifactConfig] = None) -> None:
        self.config = config or ArtifactConfig()

        # Core storage
        self._artifacts: Dict[str, Dict[str, StoredArtifact]] = {}
        self._metadata: Dict[str, Dict[str, Any]] = {}
        self._artifact_registry: Dict[str, ArtifactMetadata] = {}
        self._current_run_id: Optional[str] = None
        self._run_dir: Optional[Path] = None

        # Thread safety
        self._lock = threading.RLock() if self.config.enable_thread_safety else None
        self._active_operations: Set[str] = set()

        # Caching system
        self._cache: Dict[str, CacheEntry] = {}
        self._cache_lru: deque = deque()

        # Performance monitoring
        self._metrics: List[OperationMetrics] = []
        self._operation_counts: Dict[OperationType, int] = defaultdict(int)
        self._error_counts: Dict[str, int] = defaultdict(int)

        # Memory management
        self._memory_usage_mb = 0.0
        self._last_cleanup = datetime.utcnow()

        # Compression utilities
        self._compressor = self.ArtifactCompressor()

        # Logger
        self._logger = logging.getLogger(__name__).getChild("PreTrainingArtifactManager")

        # Initialize directories
        self.config.base_dir.mkdir(parents=True, exist_ok=True)

        # Start background tasks
        self._start_background_tasks()

        self.reset_run()

    # ------------------------------------------------------------------
    # Helper Classes and Methods
    # ------------------------------------------------------------------

    class ArtifactCompressor:
        """Utility class for artifact compression."""

        def __init__(self):
            self._logger = logging.getLogger(__name__ + ".ArtifactCompressor")

        def should_compress(self, data_size_bytes: int, config: CompressionConfig) -> bool:
            """Determine if data should be compressed based on configuration."""
            if not config.enabled:
                return False

            min_size_bytes = int(config.min_size_mb * 1024 * 1024)
            return data_size_bytes >= min_size_bytes

        def choose_compression(self, data_size_bytes: int, config: CompressionConfig) -> CompressionType:
            """Choose the best compression algorithm for the data."""
            if not config.enabled:
                return CompressionType.NONE

            if config.algorithm != CompressionType.AUTO:
                return config.algorithm

            # Auto-select based on data size and characteristics
            if data_size_bytes > 100 * 1024 * 1024:  # > 100MB
                return CompressionType.LZ4  # Fast compression for large data
            else:
                return CompressionType.GZIP  # Better compression ratio for smaller data

        def compress_data(self, data: Any, compression_type: CompressionType) -> bytes:
            """Compress data using the specified algorithm."""
            try:
                if compression_type == CompressionType.GZIP:
                    return gzip.compress(pickle.dumps(data, protocol=pickle.HIGHEST_PROTOCOL))
                elif compression_type == CompressionType.LZ4:
                    return lz4.frame.compress(pickle.dumps(data, protocol=pickle.HIGHEST_PROTOCOL))
                else:
                    return pickle.dumps(data, protocol=pickle.HIGHEST_PROTOCOL)
            except Exception as e:
                self._logger.warning(f"Compression failed, falling back to no compression: {e}")
                return pickle.dumps(data, protocol=pickle.HIGHEST_PROTOCOL)

        def decompress_data(self, compressed_data: bytes, compression_type: CompressionType) -> Any:
            """Decompress data using the specified algorithm."""
            try:
                if compression_type == CompressionType.GZIP:
                    return pickle.loads(gzip.decompress(compressed_data))
                elif compression_type == CompressionType.LZ4:
                    return pickle.loads(lz4.frame.decompress(compressed_data))
                else:
                    return pickle.loads(compressed_data)
            except Exception as e:
                self._logger.error(f"Decompression failed: {e}")
                raise

    def _start_background_tasks(self) -> None:
        """Start background maintenance tasks."""
        if self.config.enable_health_checks:
            # Start cleanup task
            cleanup_task = threading.Thread(
                target=self._background_cleanup,
                daemon=True,
                name="ArtifactManagerCleanup"
            )
            cleanup_task.start()

            self._logger.debug("Background cleanup task started")

    def _background_cleanup(self) -> None:
        """Background task for periodic cleanup and maintenance."""
        while True:
            try:
                time.sleep(self.config.cleanup_interval_seconds)
                self._perform_cleanup()
            except Exception as e:
                self._logger.error(f"Background cleanup failed: {e}")

    def _perform_cleanup(self) -> None:
        """Perform cleanup operations."""
        with self._lock:
            current_time = datetime.utcnow()

            # Check if cleanup is needed
            if (current_time - self._last_cleanup).total_seconds() < self.config.cleanup_interval_seconds:
                return

            # Clean up old cache entries
            self._cleanup_cache()

            # Clean up old run directories
            self._cleanup_old_runs()

            # Force garbage collection if enabled
            if self.config.memory.enable_gc_collection:
                import gc
                gc.collect()

            self._last_cleanup = current_time

    def _cleanup_cache(self) -> None:
        """Clean up old cache entries based on LRU and memory usage."""
        if not self.config.enable_caching:
            return

        max_memory_mb = self.config.memory.cache_memory_mb
        current_memory_mb = self._memory_usage_mb

        # Remove LRU entries if memory usage is high
        while current_memory_mb > max_memory_mb and self._cache_lru:
            oldest_key = self._cache_lru.popleft()
            if oldest_key in self._cache:
                entry = self._cache.pop(oldest_key)
                current_memory_mb -= entry.memory_size_mb
                self._logger.debug(f"Evicted cache entry: {oldest_key}")

        # Remove entries not accessed recently (older than 1 hour)
        cutoff_time = datetime.utcnow() - timedelta(hours=1)
        to_remove = []

        for key, entry in self._cache.items():
            if entry.last_accessed < cutoff_time and entry.access_count < 2:
                to_remove.append(key)
                current_memory_mb -= entry.memory_size_mb

        for key in to_remove:
            self._cache.pop(key, None)

        self._memory_usage_mb = current_memory_mb

    def _calculate_memory_usage(self, data: Any) -> float:
        """Calculate memory usage of data in MB."""
        try:
            if isinstance(data, pd.DataFrame):
                return data.memory_usage(deep=True).sum() / (1024 * 1024)
            elif isinstance(data, pd.Series):
                return data.memory_usage(deep=True) / (1024 * 1024)
            elif isinstance(data, np.ndarray):
                return data.nbytes / (1024 * 1024)
            else:
                # Estimate for other objects
                return len(pickle.dumps(data, protocol=pickle.HIGHEST_PROTOCOL)) / (1024 * 1024)
        except Exception:
            return 0.0

    def _generate_checksum(self, data: Any) -> str:
        """Generate checksum for data integrity."""
        try:
            data_bytes = pickle.dumps(data, protocol=pickle.HIGHEST_PROTOCOL)
            return hashlib.md5(data_bytes).hexdigest()
        except Exception:
            return hashlib.md5(str(data).encode()).hexdigest()

    def _record_metrics(self, metrics: OperationMetrics) -> None:
        """Record operation metrics."""
        if not self.config.enable_metrics:
            return

        self._metrics.append(metrics)
        self._operation_counts[metrics.operation_type] += 1

        # Keep only recent metrics (last 1000 operations)
        if len(self._metrics) > 1000:
            self._metrics = self._metrics[-1000:]

    def _retry_operation(self, operation_func, *args, **kwargs) -> Any:
        """Execute operation with retry logic."""
        last_exception = None

        for attempt in range(self.config.retry.max_retries + 1):
            try:
                return operation_func(*args, **kwargs)
            except self.config.retry.retryable_exceptions as e:
                last_exception = e
                if attempt < self.config.retry.max_retries:
                    delay = self._calculate_retry_delay(attempt)
                    self._logger.warning(f"Operation failed (attempt {attempt + 1}), retrying in {delay}s: {e}")
                    time.sleep(delay)
                else:
                    self._logger.error(f"Operation failed after {self.config.retry.max_retries + 1} attempts: {e}")
                    raise
            except Exception as e:
                # Non-retryable exception
                self._logger.error(f"Non-retryable operation failure: {e}")
                raise

        if last_exception:
            raise last_exception

    def _calculate_retry_delay(self, attempt: int) -> float:
        """Calculate delay for retry attempts."""
        if self.config.retry.strategy == RetryStrategy.EXPONENTIAL_BACKOFF:
            delay = self.config.retry.base_delay * (2 ** attempt)
        elif self.config.retry.strategy == RetryStrategy.LINEAR_BACKOFF:
            delay = self.config.retry.base_delay * (attempt + 1)
        else:  # FIXED_DELAY
            delay = self.config.retry.base_delay

        return min(delay, self.config.retry.max_delay)

    def _safe_operation(self, operation_type: OperationType, operation_func, *args, **kwargs) -> Any:
        """Execute operation with thread safety and metrics."""
        operation_id = f"{operation_type.value}_{uuid.uuid4().hex[:8]}"

        with self._lock:
            self._active_operations.add(operation_id)

        try:
            start_time = time.time()
            result = self._retry_operation(operation_func, *args, **kwargs)
            duration = time.time() - start_time

            # Record success metrics
            metrics = OperationMetrics(
                operation_type=operation_type,
                artifact_key=kwargs.get('artifact_key', 'unknown'),
                step_name=kwargs.get('step_name', 'unknown'),
                duration_seconds=duration,
                success=True,
                bytes_processed=kwargs.get('bytes_processed', 0)
            )
            self._record_metrics(metrics)

            return result

        except Exception as e:
            duration = time.time() - start_time

            # Record failure metrics
            metrics = OperationMetrics(
                operation_type=operation_type,
                artifact_key=kwargs.get('artifact_key', 'unknown'),
                step_name=kwargs.get('step_name', 'unknown'),
                duration_seconds=duration,
                success=False,
                error_message=str(e)
            )
            self._record_metrics(metrics)

            raise
        finally:
            with self._lock:
                self._active_operations.discard(operation_id)

    def _update_cache_entry(self, artifact_key: str, data: Any, metadata: ArtifactMetadata) -> None:
        """Update or create cache entry."""
        if not self.config.enable_caching:
            return

        memory_size = self._calculate_memory_usage(data)

        # Check if we need to evict entries due to memory pressure
        if self._memory_usage_mb + memory_size > self.config.memory.cache_memory_mb:
            self._cleanup_cache()

            # If still over limit, don't cache
            if self._memory_usage_mb + memory_size > self.config.memory.cache_memory_mb:
                self._logger.debug(f"Skipping cache for {artifact_key} due to memory pressure")
                return

        # Create or update cache entry
        if artifact_key in self._cache:
            # Update existing entry
            entry = self._cache[artifact_key]
            old_size = entry.memory_size_mb
            self._memory_usage_mb = self._memory_usage_mb - old_size + memory_size
        else:
            # Create new entry
            self._memory_usage_mb += memory_size
            self._cache_lru.append(artifact_key)

        # Create cache entry
        cache_entry = CacheEntry(
            artifact_key=artifact_key,
            data=data,
            metadata=metadata,
            memory_size_mb=memory_size
        )

        self._cache[artifact_key] = cache_entry

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------
    def reset_run(self) -> None:
        """Clear all artifacts and prepare storage for a new pipeline run."""
        with self._lock:
            # Clear all storage
            self._artifacts.clear()
            self._metadata.clear()
            self._artifact_registry.clear()

            # Reset cache and memory tracking
            self._cache.clear()
            self._cache_lru.clear()
            self._memory_usage_mb = 0.0

            # Reset metrics
            self._metrics.clear()
            self._operation_counts.clear()
            self._error_counts.clear()

            # Create new run directory
            self._current_run_id = datetime.utcnow().strftime("%Y%m%d_%H%M%S") + f"_{uuid.uuid4().hex[:8]}"
            self._run_dir = self.config.base_dir / self._current_run_id

            # Clean up old run directory if it exists
            if self._run_dir.exists():
                try:
                    shutil.rmtree(self._run_dir, ignore_errors=True)
                except Exception as e:
                    self._logger.warning(f"Failed to remove old run directory: {e}")

            # Create new run directory
            self._run_dir.mkdir(parents=True, exist_ok=True)

            # Clean up old runs
            self._cleanup_old_runs()

            self._logger.debug(f"Initialized enhanced artifact storage for run {self._current_run_id}")

    def get_run_id(self) -> Optional[str]:
        """Get the current run ID."""
        return self._current_run_id

    def get_run_dir(self) -> Optional[Path]:
        """Get the current run directory."""
        return self._run_dir

    def _cleanup_old_runs(self) -> None:
        """Remove old run directories beyond the retention limit."""
        try:
            run_dirs = sorted(
                [p for p in self.config.base_dir.iterdir() if p.is_dir()],
                key=lambda p: p.stat().st_mtime,
                reverse=True,
            )
            for old_run in run_dirs[self.config.max_runs_to_keep :]:
                shutil.rmtree(old_run, ignore_errors=True)
        except Exception as exc:  # pragma: no cover - best effort cleanup
            self._logger.debug("Failed to cleanup old artifact runs: %s", exc, exc_info=True)

    # ------------------------------------------------------------------
    # Persistence helpers
    # ------------------------------------------------------------------
    def save(
        self,
        step_name: str,
        artifacts: Optional[Dict[str, Any]] = None,
        metadata: Optional[Dict[str, Any]] = None,
        parent_artifacts: Optional[List[str]] = None,
        tags: Optional[Dict[str, str]] = None,
    ) -> None:
        """Enhanced artifact persistence with compression, metadata tracking, and error handling."""
        if not step_name:
            raise ValueError("step_name is required when saving artifacts")

        canonical_step = canonical_step_name(step_name)

        def _save_operation(**kwargs):
            artifacts_dict = artifacts or {}
            stored: Dict[str, StoredArtifact] = {}

            for key, value in artifacts_dict.items():
                artifact_key = f"{canonical_step}:{key}"

                # Create enhanced metadata
                artifact_metadata = ArtifactMetadata(
                    artifact_key=artifact_key,
                    step_name=canonical_step,
                    artifact_type=type(value).__name__,
                    size_bytes=self._calculate_memory_usage(value) * 1024 * 1024,  # Convert to bytes
                    checksum=self._generate_checksum(value),
                    parent_artifacts=parent_artifacts or [],
                    tags=tags or {},
                    description=f"Artifact from step {step_name}"
                )

                # Handle compression for large artifacts
                if self.config.enable_compression and isinstance(value, (pd.DataFrame, pd.Series)):
                    data_size_bytes = int(artifact_metadata.size_bytes)
                    if self._compressor.should_compress(data_size_bytes, self.config.compression):
                        compression_type = self._compressor.choose_compression(data_size_bytes, self.config.compression)
                        if compression_type != CompressionType.NONE:
                            try:
                                compressed_data = self._compressor.compress_data(value, compression_type)
                                compressed_size = len(compressed_data)
                                compression_ratio = compressed_size / data_size_bytes

                                # Store compressed data
                                stored[key] = StoredArtifact(
                                    kind="compressed_object",
                                    key=key,
                                    value=compressed_data,
                                    metadata={
                                        'compression_type': compression_type.value,
                                        'original_size': data_size_bytes,
                                        'compressed_size': compressed_size,
                                        'compression_ratio': compression_ratio
                                    }
                                )

                                # Update metadata
                                artifact_metadata.compression_used = compression_type
                                artifact_metadata.compressed_size_bytes = compressed_size
                                artifact_metadata.storage_location = "memory"

                                self._logger.debug(f"Compressed artifact {key} with {compression_type.value} (ratio: {compression_ratio:.2f})")

                            except Exception as e:
                                self._logger.warning(f"Compression failed for {key}, storing uncompressed: {e}")
                                stored[key] = StoredArtifact(kind="object", key=key, value=value)
                        else:
                            stored[key] = StoredArtifact(kind="object", key=key, value=value)
                    else:
                        stored[key] = StoredArtifact(kind="object", key=key, value=value)
                else:
                    stored[key] = StoredArtifact(kind="object", key=key, value=value)

                # Register artifact metadata
                self._artifact_registry[artifact_key] = artifact_metadata

                # Update cache
                self._update_cache_entry(artifact_key, value, artifact_metadata)

            if stored:
                existing = dict(self._artifacts.get(canonical_step, {}))
                existing.update(stored)
                self._artifacts[canonical_step] = existing
                # Persist to disk
                self._persist_artifacts_to_disk(canonical_step, existing)

            if metadata:
                merged_meta = dict(self._metadata.get(canonical_step, {}))
                merged_meta.update(dict(metadata))
                self._metadata[canonical_step] = merged_meta
                # Persist metadata to disk
                self._persist_metadata_to_disk(canonical_step, merged_meta)

            if stored:
                self._logger.debug(f"Saved {len(stored)} artifacts for step {canonical_step}: {', '.join(stored.keys())}")

        # Execute with enhanced error handling and metrics
        self._safe_operation(
            OperationType.SAVE,
            _save_operation,
            step_name=canonical_step,
            artifacts=artifacts
        )

    def _persist_artifacts_to_disk(self, step_name: str, artifacts: Dict[str, StoredArtifact]) -> None:
        """Persist artifacts to disk for long-term storage."""
        try:
            step_name = canonical_step_name(step_name)
            # Create artifacts directory if it doesn't exist
            artifacts_dir = self.config.base_dir / step_name
            artifacts_dir.mkdir(parents=True, exist_ok=True)

            # Save each artifact to disk
            for key, artifact in artifacts.items():
                artifact_file = artifacts_dir / f"{key}.pkl"
                with open(artifact_file, 'wb') as f:
                    pickle.dump(artifact, f)
                    
            self._logger.debug(f"Persisted {len(artifacts)} artifacts to disk for step {step_name}")
        except Exception as e:
            self._logger.warning(f"Failed to persist artifacts to disk: {e}")

    def _persist_metadata_to_disk(self, step_name: str, metadata: Dict[str, Any]) -> None:
        """Persist metadata to disk for long-term storage."""
        try:
            step_name = canonical_step_name(step_name)
            # Create artifacts directory if it doesn't exist
            artifacts_dir = self.config.base_dir / step_name
            artifacts_dir.mkdir(parents=True, exist_ok=True)

            # Save metadata to disk
            metadata_file = artifacts_dir / "metadata.json"
            with open(metadata_file, 'w') as f:
                json.dump(metadata, f, indent=2, default=str)
                
            self._logger.debug(f"Persisted metadata to disk for step {step_name}")
        except Exception as e:
            self._logger.warning(f"Failed to persist metadata to disk: {e}")

    def _load_artifacts_from_disk(self, step_name: str) -> Dict[str, StoredArtifact]:
        """Load artifacts from disk."""
        artifacts = {}
        try:
            step_name = canonical_step_name(step_name)
            artifacts_dir = self.config.base_dir / step_name
            if not artifacts_dir.exists():
                return artifacts
                
            # Load each artifact from disk
            for artifact_file in artifacts_dir.glob("*.pkl"):
                if artifact_file.name == "metadata.json":
                    continue
                    
                key = artifact_file.stem
                with open(artifact_file, 'rb') as f:
                    artifact = pickle.load(f)
                    artifacts[key] = artifact
                    
            self._logger.debug(f"Loaded {len(artifacts)} artifacts from disk for step {step_name}")
        except Exception as e:
            self._logger.warning(f"Failed to load artifacts from disk: {e}")
            
        return artifacts

    def _load_metadata_from_disk(self, step_name: str) -> Dict[str, Any]:
        """Load metadata from disk."""
        metadata = {}
        try:
            step_name = canonical_step_name(step_name)
            artifacts_dir = self.config.base_dir / step_name
            metadata_file = artifacts_dir / "metadata.json"
            
            if metadata_file.exists():
                with open(metadata_file, 'r') as f:
                    metadata = json.load(f)
                    
            self._logger.debug(f"Loaded metadata from disk for step {step_name}")
        except Exception as e:
            self._logger.warning(f"Failed to load metadata from disk: {e}")
            
        return metadata

    def _store_dataframe(self, step_name: str, key: str, df: pd.DataFrame) -> StoredArtifact:
        size_bytes = int(df.memory_usage(deep=True).sum())
        threshold_bytes = int(self.config.memory.spill_threshold_mb * 1024 * 1024)

        # Check if we should use compression for memory storage
        if size_bytes <= threshold_bytes:
            # Try compression for memory storage
            if self.config.enable_compression and self.config.compression.enable_for_memory:
                if self._compressor.should_compress(size_bytes, self.config.compression):
                    compression_type = self._compressor.choose_compression(size_bytes, self.config.compression)
                    if compression_type != CompressionType.NONE:
                        try:
                            compressed_data = self._compressor.compress_data(df, compression_type)
                            compressed_size = len(compressed_data)
                            compression_ratio = compressed_size / size_bytes

                            return StoredArtifact(
                                kind="compressed_dataframe",
                                key=key,
                                value=compressed_data,
                                size_bytes=size_bytes,
                                shape=df.shape,
                                metadata={
                                    'compression_type': compression_type.value,
                                    'original_size': size_bytes,
                                    'compressed_size': compressed_size,
                                    'compression_ratio': compression_ratio
                                }
                            )
                        except Exception as e:
                            self._logger.warning(f"DataFrame compression failed for {key}, storing uncompressed: {e}")

            return StoredArtifact(
                kind="dataframe",
                key=key,
                value=df.copy(deep=True),
                size_bytes=size_bytes,
                shape=df.shape,
            )

        # Spill to disk with optional compression
        path = self._spill_to_disk(step_name, key, df)
        return StoredArtifact(
            kind="dataframe_pointer",
            key=key,
            path=path,
            size_bytes=size_bytes,
            shape=df.shape,
        )

    def _store_series(self, step_name: str, key: str, series: pd.Series) -> StoredArtifact:
        size_bytes = int(series.memory_usage(deep=True))
        threshold_bytes = int(self.config.memory.spill_threshold_mb * 1024 * 1024)

        if size_bytes <= threshold_bytes:
            # Try compression for memory storage
            if self.config.enable_compression and self.config.compression.enable_for_memory:
                if self._compressor.should_compress(size_bytes, self.config.compression):
                    compression_type = self._compressor.choose_compression(size_bytes, self.config.compression)
                    if compression_type != CompressionType.NONE:
                        try:
                            compressed_data = self._compressor.compress_data(series, compression_type)
                            compressed_size = len(compressed_data)
                            compression_ratio = compressed_size / size_bytes

                            return StoredArtifact(
                                kind="compressed_series",
                                key=key,
                                value=compressed_data,
                                size_bytes=size_bytes,
                                shape=series.shape,
                                metadata={
                                    'compression_type': compression_type.value,
                                    'original_size': size_bytes,
                                    'compressed_size': compressed_size,
                                    'compression_ratio': compression_ratio,
                                    'column': series.name
                                }
                            )
                        except Exception as e:
                            self._logger.warning(f"Series compression failed for {key}, storing uncompressed: {e}")

            return StoredArtifact(
                kind="series",
                key=key,
                value=series.copy(deep=True),
                size_bytes=size_bytes,
                shape=series.shape,
            )

        path = self._spill_to_disk(step_name, key, series.to_frame())
        return StoredArtifact(
            kind="series_pointer",
            key=key,
            path=path,
            size_bytes=size_bytes,
            shape=series.shape,
            metadata={'column': series.name},
        )

    def _spill_to_disk(self, step_name: str, key: str, df: pd.DataFrame) -> Path:
        if self._run_dir is None:
            raise RuntimeError("Artifact manager not initialised. Call reset_run().")

        step_name = canonical_step_name(step_name)

        step_dir = self._run_dir / step_name
        step_dir.mkdir(parents=True, exist_ok=True)

        # Check if we should compress for disk storage
        if self.config.enable_compression and self.config.compression.enable_for_disk:
            df_size_bytes = int(df.memory_usage(deep=True).sum())
            if self._compressor.should_compress(df_size_bytes, self.config.compression):
                compression_type = self._compressor.choose_compression(df_size_bytes, self.config.compression)
                if compression_type != CompressionType.NONE:
                    try:
                        # Use parquet for DataFrames, but with compression considerations
                        filename = f"{key}_{uuid.uuid4().hex[:8]}.parquet"
                        path = step_dir / filename
                        df.to_parquet(path, compression='snappy')  # Use parquet's built-in compression
                        self._logger.debug(f"Spilled compressed artifact {step_name}/{key} to disk at {path}")
                        return path
                    except Exception as e:
                        self._logger.warning(f"Disk compression failed for {key}, storing uncompressed: {e}")

        # Standard parquet storage
        filename = f"{key}_{uuid.uuid4().hex[:8]}.parquet"
        path = step_dir / filename
        df.to_parquet(path)
        self._logger.debug("Spilled artifact %s/%s to disk at %s", step_name, key, path)
        return path

    # ------------------------------------------------------------------
    # Retrieval
    # ------------------------------------------------------------------
    def get_artifact(self, step_name: str, key: str) -> Optional[Any]:
        """Enhanced artifact retrieval with caching and error handling."""
        canonical_step = canonical_step_name(step_name)
        candidate_steps = []
        if step_name:
            candidate_steps.append(step_name)
        if canonical_step not in candidate_steps:
            candidate_steps.append(canonical_step)
        candidate_steps.extend(
            alias for alias in _REVERSE_STEP_ALIASES.get(canonical_step, set())
            if alias not in candidate_steps
        )

        def _get_operation(**kwargs):
            entry = None
            resolved_step = None

            for candidate in candidate_steps:
                candidate_canonical = canonical_step_name(candidate)
                entry = self._artifacts.get(candidate_canonical, {}).get(key)
                if entry is not None:
                    resolved_step = candidate_canonical
                    break

                # Try to load from disk if not found in memory
                disk_artifacts = self._load_artifacts_from_disk(candidate_canonical)
                if key in disk_artifacts:
                    self._artifacts.setdefault(candidate_canonical, {})[key] = disk_artifacts[key]
                    entry = disk_artifacts[key]
                    resolved_step = candidate_canonical
                    break

            if entry is None or resolved_step is None:
                return None

            # Check cache first
            artifact_key = f"{resolved_step}:{key}"
            if self.config.enable_caching and artifact_key in self._cache:
                cache_entry = self._cache[artifact_key]
                cache_entry.last_accessed = datetime.utcnow()
                cache_entry.access_count += 1
                return cache_entry.data

            # Materialize from storage
            result = self._materialize(entry)

            # Update cache if enabled
            if result is not None and self.config.enable_caching:
                metadata = self._artifact_registry.get(artifact_key)
                if metadata:
                    self._update_cache_entry(artifact_key, result, metadata)

            return result

        return self._safe_operation(
            OperationType.LOAD,
            _get_operation,
            step_name=canonical_step,
            artifact_key=f"{canonical_step}:{key}"
        )

    def get_dataframe(self, step_name: str, key: str) -> Optional[pd.DataFrame]:
        value = self.get_artifact(step_name, key)
        if value is None:
            return None
        if isinstance(value, pd.DataFrame):
            return value
        if isinstance(value, pd.Series):
            return value.to_frame(name=value.name or key)
        return None

    def get_series(self, step_name: str, key: str) -> Optional[pd.Series]:
        value = self.get_artifact(step_name, key)
        if isinstance(value, pd.Series):
            return value
        if isinstance(value, pd.DataFrame) and key in value.columns:
            return value[key]
        return None

    def get_step_artifacts(self, step_name: str) -> Dict[str, Any]:
        """Return all artifacts stored for a step, resolving aliases and disk-backed entries."""
        canonical = canonical_step_name(step_name)
        steps_to_try = [canonical]
        steps_to_try.extend(
            alias for alias in _REVERSE_STEP_ALIASES.get(canonical, set())
            if alias not in steps_to_try
        )

        result: Dict[str, Any] = {}
        for candidate in steps_to_try:
            candidate_canonical = canonical_step_name(candidate)
            entries = self._artifacts.get(candidate_canonical)
            if not entries:
                entries = self._load_artifacts_from_disk(candidate_canonical)
                if entries:
                    existing = dict(self._artifacts.get(candidate_canonical, {}))
                    existing.update(entries)
                    self._artifacts[candidate_canonical] = existing

            if not entries:
                continue

            for key in entries.keys():
                if key in result:
                    continue
                value = self.get_artifact(candidate_canonical, key)
                if value is not None:
                    result[key] = value

        return result

    def store_enhanced(
        self,
        key: str,
        data: Any,
        metadata: Optional[Dict[str, Any]] = None,
        step_name: Optional[str] = None,
    ) -> bool:
        """Compatibility wrapper that infers the target step before saving."""
        inferred_step = step_name or (metadata or {}).get('step') or get_default_step_for_key(key) or "__shared__"
        canonical = canonical_step_name(inferred_step)

        metadata_to_store = dict(metadata or {})
        metadata_to_store.setdefault('step', canonical)

        try:
            self.save(
                step_name=canonical,
                artifacts={key: data},
                metadata=metadata_to_store
            )
            return True
        except Exception as exc:
            self._logger.error(f"Failed to store enhanced artifact {key}: {exc}", exc_info=True)
            return False

    def retrieve_enhanced(self, key: str, step_name: Optional[str] = None) -> Optional[Any]:
        """Compatibility wrapper that searches across known steps for a key."""
        candidates: List[str] = []
        if step_name:
            candidates.append(step_name)

        inferred_step = get_default_step_for_key(key)
        if inferred_step and inferred_step not in candidates:
            candidates.append(inferred_step)

        if "__shared__" not in candidates:
            candidates.append("__shared__")

        # Include loaded steps
        for registered_step in self._artifacts.keys():
            if registered_step not in candidates:
                candidates.append(registered_step)

        # Attempt retrieval
        for candidate in candidates:
            value = self.get_artifact(candidate, key)
            if value is not None:
                return value

        # Fallback to on-disk directories not yet loaded
        try:
            for directory in self.config.base_dir.iterdir():
                if not directory.is_dir():
                    continue
                candidate = canonical_step_name(directory.name)
                if candidate in candidates:
                    continue
                value = self.get_artifact(candidate, key)
                if value is not None:
                    return value
        except Exception as exc:  # pragma: no cover - best effort
            self._logger.debug(f"Enhanced retrieval disk scan failed: {exc}", exc_info=True)

        return None

    def get_metadata(self, step_name: str) -> Dict[str, Any]:
        canonical = canonical_step_name(step_name)
        base_meta = dict(self._metadata.get(canonical, {}))
        for alias in _REVERSE_STEP_ALIASES.get(canonical, set()):
            base_meta.update(self._metadata.get(alias, {}))
        return base_meta

    def list_steps(self) -> List[str]:
        return sorted({canonical_step_name(step) for step in self._artifacts.keys()})

    def _materialize(self, entry: StoredArtifact) -> Any:
        """Enhanced materialization with compression support."""
        # First check if the value is already a DataFrame or Series (regardless of kind)
        if isinstance(entry.value, pd.DataFrame):
            self._logger.debug(f"Returning DataFrame directly from entry: {entry.value.shape}")
            return entry.value
        if isinstance(entry.value, pd.Series):
            self._logger.debug(f"Returning Series directly from entry: {entry.value.shape}")
            return entry.value
        
        # Additional check for DataFrame-like objects
        if hasattr(entry.value, 'shape') and hasattr(entry.value, 'columns') and not isinstance(entry.value, (str, bytes, bytearray, memoryview)):
            self._logger.debug(f"Returning DataFrame-like object directly: {entry.value.shape}")
            return entry.value
            
        if entry.kind == "dataframe":
            return entry.value
        if entry.kind == "series":
            return entry.value

        # Handle compressed artifacts
        if entry.kind == "compressed_dataframe":
            try:
                # If already materialized, return directly
                if isinstance(entry.value, pd.DataFrame):
                    self._logger.debug(f"Returning existing DataFrame directly: {entry.value.shape}")
                    return entry.value
                if hasattr(entry.value, 'shape') and hasattr(entry.value, 'columns') and not isinstance(entry.value, (str, bytes, bytearray, memoryview)):
                    self._logger.debug(f"Detected DataFrame-like object, returning directly: {entry.value.shape}")
                    return entry.value

                # Only decompress if value is bytes-like
                if isinstance(entry.value, (bytes, bytearray, memoryview)):
                    compression_type = CompressionType(entry.metadata.get('compression_type', 'none'))
                    self._logger.debug(f"Decompressing dataframe with compression type: {compression_type}")
                    decompressed_data = self._compressor.decompress_data(entry.value, compression_type)
                    return pickle.loads(decompressed_data)
                else:
                    self._logger.debug(f"Returning non-bytes dataframe object as-is: {type(entry.value)}")
                    return entry.value
            except Exception as e:
                self._logger.error(f"Failed to decompress dataframe: {e}")
                self._logger.debug(f"Entry value type: {type(entry.value)}")
                return None

        if entry.kind == "compressed_series":
            try:
                # If already materialized, return directly
                if isinstance(entry.value, pd.Series):
                    self._logger.debug(f"Returning existing Series directly: {entry.value.shape}")
                    return entry.value
                if hasattr(entry.value, 'shape') and hasattr(entry.value, 'index') and not isinstance(entry.value, (str, bytes, bytearray, memoryview)):
                    self._logger.debug(f"Detected Series-like object, returning directly: {entry.value.shape}")
                    return entry.value

                # Only decompress if value is bytes-like
                if isinstance(entry.value, (bytes, bytearray, memoryview)):
                    compression_type = CompressionType(entry.metadata.get('compression_type', 'none'))
                    self._logger.debug(f"Decompressing series with compression type: {compression_type}")
                    decompressed_data = self._compressor.decompress_data(entry.value, compression_type)
                    return pickle.loads(decompressed_data)
                else:
                    self._logger.debug(f"Returning non-bytes series object as-is: {type(entry.value)}")
                    return entry.value
            except Exception as e:
                self._logger.error(f"Failed to decompress series: {e}")
                self._logger.debug(f"Entry value type: {type(entry.value)}")
                return None

        if entry.kind == "compressed_object":
            try:
                # If already materialized, return directly
                if isinstance(entry.value, pd.DataFrame):
                    self._logger.debug(f"Returning existing DataFrame directly: {entry.value.shape}")
                    return entry.value
                if isinstance(entry.value, pd.Series):
                    self._logger.debug(f"Returning existing Series directly: {entry.value.shape}")
                    return entry.value

                # DataFrame-like or Series-like objects (stored uncompressed)
                if hasattr(entry.value, 'shape') and not isinstance(entry.value, (str, bytes, bytearray, memoryview)):
                    if hasattr(entry.value, 'columns'):
                        self._logger.debug(f"Detected DataFrame-like object, returning directly: {entry.value.shape}")
                    elif hasattr(entry.value, 'index'):
                        self._logger.debug(f"Detected Series-like object, returning directly: {entry.value.shape}")
                    return entry.value

                # Only attempt decompression if value is bytes-like
                if isinstance(entry.value, (bytes, bytearray, memoryview)):
                    compression_type = CompressionType(entry.metadata.get('compression_type', 'none'))
                    self._logger.debug(f"Decompressing object with compression type: {compression_type}")
                    decompressed_data = self._compressor.decompress_data(entry.value, compression_type)
                    return pickle.loads(decompressed_data)

                # Fallback: return as-is
                self._logger.debug(f"Returning non-bytes object as-is: {type(entry.value)}")
                return entry.value

            except Exception as e:
                self._logger.error(f"Failed to decompress object: {e}")
                self._logger.debug(f"Entry value type: {type(entry.value)}")
                return None

        if entry.kind == "dataframe_pointer":
            if entry.path and entry.path.exists():
                df = pd.read_parquet(entry.path)
                if self.config.cache_materialized:
                    entry.value = df
                    entry.kind = "dataframe"
                return df
            self._logger.warning("Missing persisted dataframe at %s", entry.path)
            return None
        if entry.kind == "series_pointer":
            if entry.path and entry.path.exists():
                df = pd.read_parquet(entry.path)
                col = entry.metadata.get('column')
                series = df[col] if col and col in df.columns else df.iloc[:, 0]
                if self.config.cache_materialized:
                    entry.value = series
                    entry.kind = "series"
                return series
            self._logger.warning("Missing persisted series at %s", entry.path)
            return None
        return entry.value

    # ------------------------------------------------------------------
    # Enhanced Monitoring and Management
    # ------------------------------------------------------------------

    def get_metrics(self) -> Dict[str, Any]:
        """Get comprehensive metrics about artifact manager performance."""
        if not self.config.enable_metrics:
            return {"metrics_disabled": True}

        total_operations = sum(self._operation_counts.values())
        total_errors = sum(self._error_counts.values())

        # Calculate success rate
        success_rate = (total_operations - total_errors) / total_operations if total_operations > 0 else 0.0

        # Get recent metrics (last 100 operations)
        recent_metrics = self._metrics[-100:] if self._metrics else []

        # Calculate average operation time
        avg_operation_time = sum(m.duration_seconds for m in recent_metrics) / len(recent_metrics) if recent_metrics else 0.0

        # Memory usage statistics
        memory_usage_mb = self._memory_usage_mb
        cache_usage_mb = sum(entry.memory_size_mb for entry in self._cache.values())

        return {
            "run_id": self._current_run_id,
            "total_operations": total_operations,
            "total_errors": total_errors,
            "success_rate": success_rate,
            "average_operation_time_seconds": avg_operation_time,
            "memory_usage_mb": memory_usage_mb,
            "cache_usage_mb": cache_usage_mb,
            "cache_entries": len(self._cache),
            "active_operations": len(self._active_operations),
            "artifacts_stored": len(self._artifact_registry),
            "compression_enabled": self.config.enable_compression,
            "caching_enabled": self.config.enable_caching,
            "thread_safety_enabled": self.config.enable_thread_safety,
            "recent_operations": len(recent_metrics)
        }

    def get_artifact_metadata(self, step_name: str, key: str) -> Optional[ArtifactMetadata]:
        """Get metadata for a specific artifact."""
        artifact_key = f"{canonical_step_name(step_name)}:{key}"
        return self._artifact_registry.get(artifact_key)

    def get_artifact_lineage(self, step_name: str, key: str) -> List[str]:
        """Get the lineage (parent artifacts) for a specific artifact."""
        metadata = self.get_artifact_metadata(step_name, key)
        return metadata.parent_artifacts if metadata else []

    def list_artifacts(self, step_name: Optional[str] = None, artifact_type: Optional[str] = None) -> List[ArtifactMetadata]:
        """List artifacts with optional filtering."""
        canonical = canonical_step_name(step_name) if step_name else None
        artifacts = []

        # Check memory artifacts first
        for metadata in self._artifact_registry.values():
            if canonical and canonical_step_name(metadata.step_name) != canonical:
                continue
            if artifact_type and metadata.artifact_type != artifact_type:
                continue
            artifacts.append(metadata)

        # Also check disk storage if step_name is specified
        if canonical:
            try:
                artifacts_dir = self.config.base_dir / canonical
                if artifacts_dir.exists():
                    # Load artifacts from disk to get metadata
                    disk_artifacts = self._load_artifacts_from_disk(canonical)
                    for key, artifact in disk_artifacts.items():
                        # Create metadata for disk artifacts
                        artifact_key = f"{canonical}:{key}"
                        if artifact_key not in self._artifact_registry:
                            metadata = ArtifactMetadata(
                                artifact_key=artifact_key,
                                step_name=canonical,
                                artifact_type=type(artifact.value).__name__ if artifact.value else 'unknown',
                                size_bytes=getattr(artifact, 'size_bytes', 0),
                                checksum=getattr(artifact, 'checksum', ''),
                                parent_artifacts=[],
                                tags={},
                                description=f"Artifact from disk storage"
                            )
                            if not artifact_type or metadata.artifact_type == artifact_type:
                                artifacts.append(metadata)
            except Exception as e:
                self._logger.warning(f"Failed to list disk artifacts: {e}")

        return sorted(artifacts, key=lambda x: x.created_at, reverse=True)

    def get_cache_stats(self) -> Dict[str, Any]:
        """Get cache performance statistics."""
        if not self.config.enable_caching:
            return {"caching_disabled": True}

        total_accesses = sum(entry.access_count for entry in self._cache.values())
        total_entries = len(self._cache)

        return {
            "cache_entries": total_entries,
            "memory_usage_mb": self._memory_usage_mb,
            "max_memory_mb": self.config.memory.cache_memory_mb,
            "total_accesses": total_accesses,
            "average_accesses_per_entry": total_accesses / total_entries if total_entries > 0 else 0,
            "lru_queue_length": len(self._cache_lru),
            "compression_enabled": self.config.enable_compression
        }

    def clear_cache(self) -> None:
        """Clear the artifact cache."""
        with self._lock:
            self._cache.clear()
            self._cache_lru.clear()
            self._memory_usage_mb = 0.0
            self._logger.info("Artifact cache cleared")

    def get_health_status(self) -> Dict[str, Any]:
        """Get health status of the artifact manager."""
        health = {
            "status": "healthy",
            "run_id": self._current_run_id,
            "active_operations": len(self._active_operations),
            "artifacts_count": len(self._artifact_registry),
            "cache_entries": len(self._cache),
            "memory_usage_mb": self._memory_usage_mb,
            "disk_usage_mb": self._get_disk_usage_mb(),
            "last_cleanup": self._last_cleanup.isoformat() if self._last_cleanup else None,
            "background_tasks_running": self.config.enable_health_checks
        }

        # Check for potential issues
        warnings = []

        if len(self._active_operations) > 10:
            warnings.append("High number of active operations")

        if self._memory_usage_mb > self.config.memory.max_memory_mb * 0.9:
            warnings.append("High memory usage")
            health["status"] = "warning"

        if len(self._error_counts) > 0:
            warnings.append(f"Recent errors: {dict(self._error_counts)}")
            if sum(self._error_counts.values()) > 10:
                health["status"] = "warning"

        health["warnings"] = warnings

        return health

    def _get_disk_usage_mb(self) -> float:
        """Get disk usage in MB for the current run directory."""
        try:
            if self._run_dir and self._run_dir.exists():
                total_size = sum(f.stat().st_size for f in self._run_dir.rglob('*') if f.is_file())
                return total_size / (1024 * 1024)
        except Exception as e:
            self._logger.warning(f"Failed to calculate disk usage: {e}")
        return 0.0

    def export_metrics(self, format: str = "json") -> str:
        """Export metrics in specified format."""
        metrics = self.get_metrics()
        cache_stats = self.get_cache_stats()
        health_status = self.get_health_status()

        export_data = {
            "timestamp": datetime.utcnow().isoformat(),
            "metrics": metrics,
            "cache_stats": cache_stats,
            "health_status": health_status,
            "configuration": asdict(self.config)
        }

        if format.lower() == "json":
            return json.dumps(export_data, indent=2, default=str)
        else:
            # Return as formatted string for other formats
            return str(export_data)

    def optimize_storage(self) -> Dict[str, Any]:
        """Perform storage optimization operations."""
        results = {
            "cache_cleanup": False,
            "old_runs_cleanup": False,
            "compression_reapplied": False,
            "memory_freed_mb": 0.0,
            "files_optimized": 0
        }

        with self._lock:
            # Force cache cleanup
            old_memory_usage = self._memory_usage_mb
            self._cleanup_cache()
            memory_freed = old_memory_usage - self._memory_usage_mb
            results["cache_cleanup"] = True
            results["memory_freed_mb"] = memory_freed

            # Force old runs cleanup
            self._cleanup_old_runs()
            results["old_runs_cleanup"] = True

            # Reapply compression to large artifacts if beneficial
            if self.config.enable_compression:
                optimized_count = self._reapply_compression()
                results["compression_reapplied"] = True
                results["files_optimized"] = optimized_count

        self._logger.info(f"Storage optimization completed: {results}")
        return results

    def _reapply_compression(self) -> int:
        """Reapply compression to artifacts that could benefit from it."""
        optimized_count = 0

        # This is a simplified version - in practice, you'd want more sophisticated logic
        # to determine which artifacts should be recompressed

        return optimized_count

    def get_storage_summary(self) -> Dict[str, Any]:
        """Get a comprehensive storage summary."""
        return {
            "artifacts": {
                "total_count": len(self._artifact_registry),
                "by_type": self._count_artifacts_by_type(),
                "by_step": self._count_artifacts_by_step()
            },
            "memory": {
                "cache_usage_mb": self._memory_usage_mb,
                "max_cache_mb": self.config.memory.cache_memory_mb,
                "spill_threshold_mb": self.config.memory.spill_threshold_mb
            },
            "disk": {
                "current_run_mb": self._get_disk_usage_mb(),
                "base_directory": str(self.config.base_dir)
            },
            "compression": {
                "enabled": self.config.enable_compression,
                "algorithm": self.config.compression.algorithm.value,
                "compressed_artifacts": self._count_compressed_artifacts()
            }
        }

    def _count_artifacts_by_type(self) -> Dict[str, int]:
        """Count artifacts by type."""
        counts = defaultdict(int)
        for metadata in self._artifact_registry.values():
            counts[metadata.artifact_type] += 1
        return dict(counts)

    def _count_artifacts_by_step(self) -> Dict[str, int]:
        """Count artifacts by step."""
        counts = defaultdict(int)
        for metadata in self._artifact_registry.values():
            counts[metadata.step_name] += 1
        return dict(counts)

    def _count_compressed_artifacts(self) -> int:
        """Count compressed artifacts."""
        count = 0
        for metadata in self._artifact_registry.values():
            if metadata.compression_used != CompressionType.NONE:
                count += 1
        return count


_artifact_manager: Optional[PreTrainingArtifactManager] = None


def get_pretraining_artifact_manager() -> PreTrainingArtifactManager:
    """Return singleton instance of the artifact manager."""
    global _artifact_manager
    if _artifact_manager is None:
        _artifact_manager = PreTrainingArtifactManager()
    return _artifact_manager
