"""
Domain Whitelist for Feature Interactions

This module implements a sophisticated domain whitelist system that ensures only
economically meaningful feature interactions are generated. It categorizes features
into domains and defines rules for which interactions are allowed.

Key Features:
- Feature domain classification
- Economic logic validation
- Cross-domain interaction rules
- Redundancy prevention
- Performance optimization
"""

import re
from typing import Dict, List, Set, Tuple, Optional, Any
from dataclasses import dataclass
from enum import Enum
import logging

from src.utils.tprint import (
    tprint, tprint_info, tprint_success, tprint_warning, tprint_error,
    tprint_debug, tprint_performance
)

logger = logging.getLogger(__name__)


class FeatureDomain(Enum):
    """Feature domains for interaction whitelisting."""
    PRICE_MOMENTUM = "price_momentum"
    VOLATILITY = "volatility"
    VOLUME = "volume"
    TREND = "trend"
    MEAN_REVERSION = "mean_reversion"
    CROSS_ASSET = "cross_asset"
    TECHNICAL_INDICATORS = "technical_indicators"
    ROLLING_STATS = "rolling_stats"
    CROSS_TIMEFRAME = "cross_timeframe"
    UNKNOWN = "unknown"


@dataclass
class InteractionRule:
    """Rule for allowing interactions between domains."""
    domain1: FeatureDomain
    domain2: FeatureDomain
    allowed: bool
    reason: str
    priority: int = 0  # Higher priority rules override lower ones


class DomainWhitelist:
    """
    Domain whitelist system for feature interactions.
    
    Ensures only economically meaningful interactions are generated by:
    1. Classifying features into domains
    2. Defining interaction rules between domains
    3. Validating interaction plausibility
    4. Preventing redundant interactions
    """
    
    def __init__(self):
        """Initialize the domain whitelist system."""
        self.domain_patterns = self._build_domain_patterns()
        self.interaction_rules = self._build_interaction_rules()
        self.feature_domains: Dict[str, FeatureDomain] = {}
        
        tprint_info("🔧 Domain whitelist system initialized")
        tprint_info(f"📊 Domains: {len(FeatureDomain)}")
        tprint_info(f"📊 Rules: {len(self.interaction_rules)}")
    
    def _build_domain_patterns(self) -> Dict[FeatureDomain, List[str]]:
        """Build regex patterns for feature domain classification."""
        return {
            FeatureDomain.PRICE_MOMENTUM: [
                r'.*rsi.*', r'.*macd.*', r'.*momentum.*', r'.*roc.*',
                r'.*stoch.*', r'.*williams.*', r'.*cci.*', r'.*adx.*',
                r'.*price.*change.*', r'.*return.*', r'.*pct.*change.*'
            ],
            FeatureDomain.VOLATILITY: [
                r'.*atr.*', r'.*bb.*', r'.*bollinger.*', r'.*volatility.*',
                r'.*std.*', r'.*variance.*', r'.*vol.*', r'.*vol_ratio.*',
                r'.*volatility.*ratio.*', r'.*vol.*ma.*'
            ],
            FeatureDomain.VOLUME: [
                r'.*volume.*', r'.*vol.*', r'.*volume_ma.*', r'.*volume_ratio.*',
                r'.*volume_roc.*', r'.*obv.*', r'.*ad.*', r'.*cmf.*',
                r'.*volume.*change.*', r'.*vol.*change.*'
            ],
            FeatureDomain.TREND: [
                r'.*sma.*', r'.*ema.*', r'.*ma.*', r'.*trend.*',
                r'.*slope.*', r'.*angle.*', r'.*directional.*', r'.*adx.*',
                r'.*trend.*strength.*', r'.*trend.*direction.*'
            ],
            FeatureDomain.MEAN_REVERSION: [
                r'.*bb_position.*', r'.*z_score.*', r'.*price_vs.*', r'.*mean_reversion.*',
                r'.*reversion.*', r'.*deviation.*', r'.*distance.*from.*mean.*',
                r'.*current_vs.*mean.*', r'.*current_vs.*max.*', r'.*current_vs.*min.*'
            ],
            FeatureDomain.CROSS_ASSET: [
                r'.*spy.*', r'.*vix.*', r'.*sector.*', r'.*correlation.*',
                r'.*beta.*', r'.*relative.*', r'.*vs.*', r'.*ratio.*',
                r'.*cross.*asset.*', r'.*market.*'
            ],
            FeatureDomain.TECHNICAL_INDICATORS: [
                r'.*rsi.*', r'.*macd.*', r'.*bollinger.*', r'.*atr.*',
                r'.*stoch.*', r'.*williams.*', r'.*cci.*', r'.*adx.*',
                r'.*obv.*', r'.*ad.*', r'.*cmf.*'
            ],
            FeatureDomain.ROLLING_STATS: [
                r'.*mean.*', r'.*std.*', r'.*min.*', r'.*max.*',
                r'.*median.*', r'.*skew.*', r'.*kurt.*', r'.*rolling.*',
                r'.*window.*', r'.*period.*'
            ],
            FeatureDomain.CROSS_TIMEFRAME: [
                r'.*ctf.*', r'.*cross.*timeframe.*', r'.*multi.*period.*',
                r'.*timeframe.*', r'.*period.*aggregation.*'
            ]
        }
    
    def _build_interaction_rules(self) -> List[InteractionRule]:
        """Build rules for domain interactions."""
        return [
            # High-priority rules for economically meaningful interactions
            InteractionRule(
                FeatureDomain.PRICE_MOMENTUM, FeatureDomain.VOLATILITY, True,
                "Momentum indicators benefit from volatility context", priority=10
            ),
            InteractionRule(
                FeatureDomain.VOLUME, FeatureDomain.PRICE_MOMENTUM, True,
                "Volume confirms price momentum - highly meaningful for trading", priority=10
            ),
            InteractionRule(
                FeatureDomain.TREND, FeatureDomain.MEAN_REVERSION, True,
                "Trend vs mean reversion is a classic strategy", priority=10
            ),
            InteractionRule(
                FeatureDomain.CROSS_ASSET, FeatureDomain.PRICE_MOMENTUM, True,
                "Cross-asset momentum provides diversification", priority=9
            ),
            InteractionRule(
                FeatureDomain.CROSS_ASSET, FeatureDomain.VOLATILITY, True,
                "Cross-asset volatility for risk management", priority=9
            ),
            InteractionRule(
                FeatureDomain.CROSS_TIMEFRAME, FeatureDomain.PRICE_MOMENTUM, True,
                "Multi-timeframe momentum analysis", priority=8
            ),
            InteractionRule(
                FeatureDomain.CROSS_TIMEFRAME, FeatureDomain.VOLATILITY, True,
                "Multi-timeframe volatility analysis", priority=8
            ),
            InteractionRule(
                FeatureDomain.ROLLING_STATS, FeatureDomain.PRICE_MOMENTUM, True,
                "Statistical measures of momentum", priority=7
            ),
            InteractionRule(
                FeatureDomain.ROLLING_STATS, FeatureDomain.VOLATILITY, True,
                "Statistical measures of volatility", priority=7
            ),
            
            # Medium-priority rules
            InteractionRule(
                FeatureDomain.TECHNICAL_INDICATORS, FeatureDomain.VOLUME, True,
                "Technical indicators with volume confirmation", priority=6
            ),
            InteractionRule(
                FeatureDomain.TECHNICAL_INDICATORS, FeatureDomain.TREND, True,
                "Technical indicators with trend context", priority=6
            ),
            InteractionRule(
                FeatureDomain.VOLUME, FeatureDomain.VOLATILITY, True,
                "Volume-volatility relationship - volume spikes indicate volatility", priority=8
            ),
            InteractionRule(
                FeatureDomain.TREND, FeatureDomain.VOLUME, True,
                "Trend confirmation with volume - volume validates trend strength", priority=8
            ),
            InteractionRule(
                FeatureDomain.VOLUME, FeatureDomain.MEAN_REVERSION, True,
                "Volume at extremes signals mean reversion opportunities", priority=7
            ),
            InteractionRule(
                FeatureDomain.VOLUME, FeatureDomain.CROSS_ASSET, True,
                "Cross-asset volume patterns reveal market sentiment", priority=6
            ),
            
            # Low-priority rules
            InteractionRule(
                FeatureDomain.ROLLING_STATS, FeatureDomain.TREND, True,
                "Statistical measures of trend", priority=4
            ),
            InteractionRule(
                FeatureDomain.ROLLING_STATS, FeatureDomain.MEAN_REVERSION, True,
                "Statistical measures of mean reversion", priority=4
            ),
            
            # Prohibited interactions (redundant or meaningless)
            InteractionRule(
                FeatureDomain.PRICE_MOMENTUM, FeatureDomain.PRICE_MOMENTUM, False,
                "Redundant momentum indicators", priority=1
            ),
            InteractionRule(
                FeatureDomain.TREND, FeatureDomain.TREND, False,
                "Redundant trend indicators", priority=1
            ),
            InteractionRule(
                FeatureDomain.VOLUME, FeatureDomain.VOLUME, False,
                "Redundant volume indicators", priority=1
            ),
            InteractionRule(
                FeatureDomain.VOLATILITY, FeatureDomain.VOLATILITY, False,
                "Redundant volatility indicators", priority=1
            ),
            InteractionRule(
                FeatureDomain.MEAN_REVERSION, FeatureDomain.MEAN_REVERSION, False,
                "Redundant mean reversion indicators", priority=1
            ),
        ]
    
    def classify_feature(self, feature_name: str) -> FeatureDomain:
        """Classify a feature into its domain."""
        feature_name_lower = feature_name.lower()
        
        # Check each domain pattern
        for domain, patterns in self.domain_patterns.items():
            for pattern in patterns:
                if re.match(pattern, feature_name_lower):
                    return domain
        
        return FeatureDomain.UNKNOWN
    
    def is_interaction_allowed(self, feature1: str, feature2: str) -> Tuple[bool, str]:
        """
        Check if an interaction between two features is allowed.
        
        Args:
            feature1: First feature name
            feature2: Second feature name
            
        Returns:
            Tuple of (is_allowed, reason)
        """
        # Classify features
        domain1 = self.classify_feature(feature1)
        domain2 = self.classify_feature(feature2)
        
        # Store classifications for future use
        self.feature_domains[feature1] = domain1
        self.feature_domains[feature2] = domain2
        
        # Check interaction rules
        applicable_rules = [
            rule for rule in self.interaction_rules
            if (rule.domain1 == domain1 and rule.domain2 == domain2) or
               (rule.domain1 == domain2 and rule.domain2 == domain1)
        ]
        
        if not applicable_rules:
            # No specific rule - use default logic
            return self._default_interaction_logic(domain1, domain2)
        
        # Sort by priority (highest first)
        applicable_rules.sort(key=lambda x: x.priority, reverse=True)
        
        # Use highest priority rule
        rule = applicable_rules[0]
        return rule.allowed, rule.reason
    
    def _default_interaction_logic(self, domain1: FeatureDomain, domain2: FeatureDomain) -> Tuple[bool, str]:
        """Default logic for interactions when no specific rule exists."""
        # Allow interactions between different domains
        if domain1 != domain2:
            return True, f"Cross-domain interaction between {domain1.value} and {domain2.value}"
        
        # Allow interactions within same domain if it's not a redundant domain
        if domain1 in [FeatureDomain.CROSS_ASSET, FeatureDomain.CROSS_TIMEFRAME]:
            return True, f"Within-domain interaction for {domain1.value}"
        
        # Default to not allowing same-domain interactions
        return False, f"Redundant within-domain interaction for {domain1.value}"
    
    def get_allowed_interactions(self, features: List[str], 
                               max_interactions: int = 50) -> List[Tuple[str, str, str]]:
        """
        Get list of allowed interactions from a feature list.
        
        Args:
            features: List of feature names
            max_interactions: Maximum number of interactions to return
            
        Returns:
            List of (feature1, feature2, reason) tuples
        """
        allowed_interactions = []
        
        # Generate all possible pairs
        for i, feature1 in enumerate(features):
            for feature2 in features[i+1:]:
                is_allowed, reason = self.is_interaction_allowed(feature1, feature2)
                
                if is_allowed:
                    allowed_interactions.append((feature1, feature2, reason))
        
        # Sort by priority (based on domain types)
        def interaction_priority(interaction):
            feature1, feature2, reason = interaction
            domain1 = self.classify_feature(feature1)
            domain2 = self.classify_feature(feature2)
            
            # Higher priority for cross-domain interactions
            if domain1 != domain2:
                return 10
            else:
                return 5
        
        allowed_interactions.sort(key=interaction_priority, reverse=True)
        
        # Return top interactions
        return allowed_interactions[:max_interactions]
    
    def get_domain_breakdown(self, features: List[str]) -> Dict[FeatureDomain, List[str]]:
        """Get breakdown of features by domain."""
        breakdown = {domain: [] for domain in FeatureDomain}
        
        for feature in features:
            domain = self.classify_feature(feature)
            breakdown[domain].append(feature)
        
        return breakdown
    
    def get_interaction_statistics(self, features: List[str]) -> Dict[str, Any]:
        """Get statistics about potential interactions."""
        total_pairs = len(features) * (len(features) - 1) // 2
        allowed_interactions = self.get_allowed_interactions(features)
        allowed_count = len(allowed_interactions)
        
        # Domain breakdown
        domain_breakdown = self.get_domain_breakdown(features)
        
        # Interaction type breakdown
        interaction_types = {}
        for feature1, feature2, reason in allowed_interactions:
            domain1 = self.classify_feature(feature1)
            domain2 = self.classify_feature(feature2)
            
            if domain1 != domain2:
                key = f"{domain1.value}_x_{domain2.value}"
            else:
                key = f"{domain1.value}_internal"
            
            interaction_types[key] = interaction_types.get(key, 0) + 1
        
        return {
            'total_features': len(features),
            'total_pairs': total_pairs,
            'allowed_interactions': allowed_count,
            'interaction_rate': allowed_count / total_pairs if total_pairs > 0 else 0,
            'domain_breakdown': {domain.value: len(features) for domain, features in domain_breakdown.items()},
            'interaction_types': interaction_types
        }
    
    def validate_interaction_quality(self, feature1: str, feature2: str, 
                                   interaction_type: str) -> Tuple[bool, str]:
        """
        Validate the quality of a specific interaction.
        
        Args:
            feature1: First feature name
            feature2: Second feature name
            interaction_type: Type of interaction (ratio, product, etc.)
            
        Returns:
            Tuple of (is_valid, reason)
        """
        is_allowed, reason = self.is_interaction_allowed(feature1, feature2)
        
        if not is_allowed:
            return False, f"Interaction not allowed: {reason}"
        
        # Additional quality checks
        domain1 = self.classify_feature(feature1)
        domain2 = self.classify_feature(feature2)
        
        # Check for division by zero risk
        if interaction_type in ['ratio', 'divide']:
            if domain2 in [FeatureDomain.VOLUME, FeatureDomain.VOLATILITY]:
                return True, "Volume/volatility ratios are generally safe"
            elif domain2 in [FeatureDomain.PRICE_MOMENTUM, FeatureDomain.TREND]:
                return True, "Momentum/trend ratios are generally safe"
            else:
                return True, "Ratio interaction validated"
        
        # Check for scaling issues
        if interaction_type in ['product', 'multiply']:
            if domain1 == domain2:
                return False, "Product of same-domain features may cause scaling issues"
            else:
                return True, "Cross-domain product interaction validated"
        
        return True, "Interaction quality validated"


# Global instance for convenience
_domain_whitelist = None

def get_domain_whitelist() -> DomainWhitelist:
    """Get the global domain whitelist instance."""
    global _domain_whitelist
    if _domain_whitelist is None:
        _domain_whitelist = DomainWhitelist()
    return _domain_whitelist

def is_interaction_allowed(feature1: str, feature2: str) -> Tuple[bool, str]:
    """Check if an interaction is allowed using the global whitelist."""
    whitelist = get_domain_whitelist()
    return whitelist.is_interaction_allowed(feature1, feature2)

def get_allowed_interactions(features: List[str], max_interactions: int = 50) -> List[Tuple[str, str, str]]:
    """Get allowed interactions using the global whitelist."""
    whitelist = get_domain_whitelist()
    return whitelist.get_allowed_interactions(features, max_interactions)