"""
Consensus System Example

This module provides a comprehensive example demonstrating the complete consensus-based
ML indicator system that only uses indicators generated by multiple models.

Key Features:
- Complete system demonstration
- Model comparison and consensus generation
- Interpretability analysis
- Real-time consensus indicator generation
- Performance evaluation and validation
"""

import numpy as np
import pandas as pd
import warnings
from typing import Any, Dict, List, Optional, Union, Tuple
import logging
import time
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import seaborn as sns

# Core imports
from .ml_candle_pattern_indicators import (
    MLIndicatorGenerator, IndicatorType, ModelType, IndicatorConfig,
    create_ml_indicator_generator
)
from .model_comparison_pipeline import (
    ModelComparisonPipeline, ConsensusMethod, ConsensusConfig, create_model_comparison_pipeline
)
from .interpretability_analysis import (
    InterpretabilityAnalyzer, InterpretabilityConfig, create_interpretability_analyzer
)
from .consensus_indicator_system import (
    ConsensusIndicatorSystem, ConsensusSystemConfig, create_consensus_system
)

logger = logging.getLogger(__name__)


class ConsensusSystemDemo:
    """
    Comprehensive demonstration of the consensus-based ML indicator system.
    
    This demo shows how to:
    1. Train multiple ML models
    2. Compare their performance
    3. Generate consensus indicators
    4. Analyze interpretability
    5. Validate consensus quality
    """
    
    def __init__(self):
        self.consensus_system = None
        self.comparison_pipeline = None
        self.interpretability_analyzer = None
        self.results = {}
        
        logger.info("🎯 Consensus System Demo initialized")
    
    def run_complete_demo(self, data: pd.DataFrame, symbol: str = 'BTCUSDT') -> Dict[str, Any]:
        """
        Run the complete consensus system demonstration.
        
        Args:
            data: Historical OHLCV data
            symbol: Trading symbol
            
        Returns:
            Complete demonstration results
        """
        logger.info(f"🚀 Starting complete consensus system demo for {symbol}")
        start_time = time.time()
        
        demo_results = {
            'symbol': symbol,
            'start_time': start_time,
            'data_samples': len(data),
            'steps_completed': [],
            'results': {}
        }
        
        try:
            # Step 1: Train consensus system
            logger.info("📚 Step 1: Training consensus system...")
            consensus_results = self._train_consensus_system(data, symbol)
            demo_results['steps_completed'].append('consensus_training')
            demo_results['results']['consensus_training'] = consensus_results
            
            # Step 2: Model comparison analysis
            logger.info("🔍 Step 2: Model comparison analysis...")
            comparison_results = self._analyze_model_comparison()
            demo_results['steps_completed'].append('model_comparison')
            demo_results['results']['model_comparison'] = comparison_results
            
            # Step 3: Interpretability analysis
            logger.info("🧠 Step 3: Interpretability analysis...")
            interpretability_results = self._analyze_interpretability()
            demo_results['steps_completed'].append('interpretability_analysis')
            demo_results['results']['interpretability_analysis'] = interpretability_results
            
            # Step 4: Consensus validation
            logger.info("✅ Step 4: Consensus validation...")
            validation_results = self._validate_consensus_quality()
            demo_results['steps_completed'].append('consensus_validation')
            demo_results['results']['consensus_validation'] = validation_results
            
            # Step 5: Real-time generation demo
            logger.info("⚡ Step 5: Real-time generation demo...")
            realtime_results = self._demo_realtime_generation(data)
            demo_results['steps_completed'].append('realtime_generation')
            demo_results['results']['realtime_generation'] = realtime_results
            
            # Step 6: Performance evaluation
            logger.info("📊 Step 6: Performance evaluation...")
            performance_results = self._evaluate_system_performance(data)
            demo_results['steps_completed'].append('performance_evaluation')
            demo_results['results']['performance_evaluation'] = performance_results
            
            demo_results['success'] = True
            
        except Exception as e:
            logger.error(f"Demo failed: {e}")
            demo_results['success'] = False
            demo_results['error'] = str(e)
        
        demo_results['end_time'] = time.time()
        demo_results['total_time'] = demo_results['end_time'] - start_time
        
        logger.info(f"🎉 Complete demo finished in {demo_results['total_time']:.2f} seconds")
        return demo_results
    
    def _train_consensus_system(self, data: pd.DataFrame, symbol: str) -> Dict[str, Any]:
        """Train the consensus system with multiple models."""
        # Configure consensus system
        config = ConsensusSystemConfig(
            min_models_required=2,
            min_agreement_threshold=0.6,
            min_confidence_threshold=0.7,
            consensus_method=ConsensusMethod.CONFIDENCE_WEIGHTED,
            enable_quality_control=True,
            enable_consensus_interpretability=True
        )
        
        # Create consensus system
        self.consensus_system = create_consensus_system(config)
        
        # Train system
        training_results = self.consensus_system.train_consensus_system(
            data, 
            symbol=symbol,
            model_types=[ModelType.LIGHTGBM, ModelType.RANDOM_FOREST]
        )
        
        return training_results
    
    def _analyze_model_comparison(self) -> Dict[str, Any]:
        """Analyze model comparison results."""
        if not self.consensus_system:
            return {'error': 'Consensus system not trained'}
        
        comparison_pipeline = self.consensus_system.comparison_pipeline
        comparison_results = comparison_pipeline.comparison_history[-1] if comparison_pipeline.comparison_history else {}
        
        # Extract key metrics
        analysis = {
            'total_models': len(comparison_results.get('model_results', {})),
            'successful_models': len([r for r in comparison_results.get('model_results', {}).values() if r.get('success', False)]),
            'model_performance': {},
            'consensus_analysis': comparison_results.get('consensus_analysis', {}),
            'performance_comparison': comparison_results.get('performance_comparison', {})
        }
        
        # Analyze individual model performance
        for model_name, result in comparison_results.get('model_results', {}).items():
            if result.get('success', False):
                performance = result.get('performance', {})
                analysis['model_performance'][model_name] = {
                    'f1_score': performance.get('f1_score', 0),
                    'accuracy': performance.get('accuracy', 0),
                    'confidence': result.get('confidence', 0)
                }
        
        return analysis
    
    def _analyze_interpretability(self) -> Dict[str, Any]:
        """Analyze interpretability across models."""
        if not self.consensus_system or not self.consensus_system.interpretability_analyzer:
            return {'error': 'Interpretability analyzer not available'}
        
        # Get interpretability results from consensus system
        interpretability_results = self.consensus_system.consensus_history[-1].get('interpretability_results', {})
        
        analysis = {
            'consensus_features': interpretability_results.get('consensus_features', {}),
            'feature_agreement': interpretability_results.get('feature_agreement', {}),
            'model_consensus_scores': interpretability_results.get('model_consensus_scores', {}),
            'top_consensus_features': interpretability_results.get('top_consensus_features', [])
        }
        
        return analysis
    
    def _validate_consensus_quality(self) -> Dict[str, Any]:
        """Validate the quality of consensus indicators."""
        if not self.consensus_system:
            return {'error': 'Consensus system not trained'}
        
        # Get quality validation from training results
        training_results = self.consensus_system.consensus_history[-1]
        quality_validation = training_results.get('quality_validation', {})
        
        validation_analysis = {
            'consensus_strength': quality_validation.get('consensus_strength', 0),
            'model_agreement': quality_validation.get('model_agreement', 0),
            'indicator_stability': quality_validation.get('indicator_stability', 0),
            'quality_score': quality_validation.get('quality_score', 0),
            'validation_passed': quality_validation.get('validation_passed', False)
        }
        
        return validation_analysis
    
    def _demo_realtime_generation(self, data: pd.DataFrame) -> Dict[str, Any]:
        """Demonstrate real-time consensus indicator generation."""
        if not self.consensus_system:
            return {'error': 'Consensus system not trained'}
        
        # Use last portion of data as "new" data
        new_data = data.iloc[-100:]
        
        # Generate consensus indicators
        consensus_indicators = self.consensus_system.generate_consensus_indicators(new_data)
        
        if 'error' in consensus_indicators:
            return consensus_indicators
        
        # Analyze real-time results
        realtime_analysis = {
            'indicators_generated': len(consensus_indicators['consensus_indicators']),
            'models_used': len(consensus_indicators['models_used']),
            'consensus_method': consensus_indicators['consensus_method'],
            'reliability_distribution': consensus_indicators['reliability_levels'].value_counts().to_dict(),
            'indicator_statistics': {
                'mean': consensus_indicators['consensus_indicators'].mean(),
                'std': consensus_indicators['consensus_indicators'].std(),
                'min': consensus_indicators['consensus_indicators'].min(),
                'max': consensus_indicators['consensus_indicators'].max()
            }
        }
        
        return realtime_analysis
    
    def _evaluate_system_performance(self, data: pd.DataFrame) -> Dict[str, Any]:
        """Evaluate overall system performance."""
        if not self.consensus_system:
            return {'error': 'Consensus system not trained'}
        
        # Get system summary
        summary = self.consensus_system.get_consensus_summary()
        
        # Calculate additional performance metrics
        performance_metrics = {
            'system_summary': summary,
            'consensus_reliability': self._calculate_consensus_reliability(),
            'model_agreement_analysis': self._analyze_model_agreement(),
            'consensus_stability': self._analyze_consensus_stability(data)
        }
        
        return performance_metrics
    
    def _calculate_consensus_reliability(self) -> Dict[str, Any]:
        """Calculate consensus reliability metrics."""
        if not self.consensus_system:
            return {'error': 'Consensus system not trained'}
        
        # Get reliability scores from training
        reliability_scores = self.consensus_system.model_reliability_scores
        
        reliability_analysis = {
            'total_models': len(reliability_scores),
            'average_reliability': np.mean(list(reliability_scores.values())) if reliability_scores else 0,
            'max_reliability': max(reliability_scores.values()) if reliability_scores else 0,
            'min_reliability': min(reliability_scores.values()) if reliability_scores else 0,
            'reliability_distribution': reliability_scores
        }
        
        return reliability_analysis
    
    def _analyze_model_agreement(self) -> Dict[str, Any]:
        """Analyze agreement between models."""
        if not self.consensus_system:
            return {'error': 'Consensus system not trained'}
        
        # Get agreement scores from comparison pipeline
        comparison_pipeline = self.consensus_system.comparison_pipeline
        if not comparison_pipeline.comparison_history:
            return {'error': 'No comparison history available'}
        
        latest_comparison = comparison_pipeline.comparison_history[-1]
        consensus_analysis = latest_comparison.get('consensus_analysis', {})
        agreement_scores = consensus_analysis.get('agreement_scores', {})
        
        agreement_analysis = {
            'total_pairs': len(agreement_scores),
            'average_agreement': np.mean(list(agreement_scores.values())) if agreement_scores else 0,
            'max_agreement': max(agreement_scores.values()) if agreement_scores else 0,
            'min_agreement': min(agreement_scores.values()) if agreement_scores else 0,
            'agreement_scores': agreement_scores
        }
        
        return agreement_analysis
    
    def _analyze_consensus_stability(self, data: pd.DataFrame) -> Dict[str, Any]:
        """Analyze consensus stability over time."""
        if not self.consensus_system:
            return {'error': 'Consensus system not trained'}
        
        # Generate consensus indicators for the entire dataset
        consensus_indicators = self.consensus_system.generate_consensus_indicators(data)
        
        if 'error' in consensus_indicators:
            return consensus_indicators
        
        indicators = consensus_indicators['consensus_indicators']
        
        # Calculate stability metrics
        stability_analysis = {
            'total_indicators': len(indicators),
            'volatility': indicators.std(),
            'trend_stability': self._calculate_trend_stability(indicators),
            'consistency_score': self._calculate_consistency_score(indicators),
            'stability_periods': self._identify_stability_periods(indicators)
        }
        
        return stability_analysis
    
    def _calculate_trend_stability(self, indicators: pd.Series) -> float:
        """Calculate trend stability of indicators."""
        if len(indicators) < 10:
            return 0.0
        
        # Calculate rolling trend
        rolling_trend = indicators.rolling(10).apply(
            lambda x: np.polyfit(range(len(x)), x, 1)[0] if len(x) == 10 else 0
        )
        
        # Stability is inverse of trend volatility
        trend_volatility = rolling_trend.std()
        stability = 1.0 / (1.0 + trend_volatility)
        
        return stability
    
    def _calculate_consistency_score(self, indicators: pd.Series) -> float:
        """Calculate consistency score for indicators."""
        if len(indicators) < 20:
            return 0.0
        
        # Calculate rolling correlation with previous values
        rolling_corr = indicators.rolling(20).apply(
            lambda x: x.corr(pd.Series(range(len(x)))) if len(x) == 20 else 0
        )
        
        return rolling_corr.mean()
    
    def _identify_stability_periods(self, indicators: pd.Series) -> List[Dict[str, Any]]:
        """Identify periods of high stability."""
        if len(indicators) < 50:
            return []
        
        # Calculate rolling volatility
        rolling_vol = indicators.rolling(20).std()
        volatility_threshold = rolling_vol.quantile(0.3)  # Bottom 30% volatility
        
        # Find stable periods
        stable_periods = []
        in_stable_period = False
        stable_start = None
        
        for i, vol in enumerate(rolling_vol):
            if vol <= volatility_threshold and not in_stable_period:
                in_stable_period = True
                stable_start = i
            elif vol > volatility_threshold and in_stable_period:
                in_stable_period = False
                if stable_start is not None:
                    stable_periods.append({
                        'start': stable_start,
                        'end': i,
                        'length': i - stable_start,
                        'avg_volatility': rolling_vol.iloc[stable_start:i].mean()
                    })
        
        # Sort by length (longest first)
        stable_periods.sort(key=lambda x: x['length'], reverse=True)
        
        return stable_periods[:5]  # Top 5 stable periods
    
    def generate_demo_report(self, results: Dict[str, Any]) -> str:
        """Generate a comprehensive demo report."""
        report = f"""
# Consensus ML Indicator System Demo Report

## Overview
- **Symbol**: {results['symbol']}
- **Data Samples**: {results['data_samples']}
- **Total Time**: {results['total_time']:.2f} seconds
- **Success**: {'✅' if results['success'] else '❌'}

## Steps Completed
{chr(10).join(f"- {step}" for step in results['steps_completed'])}

## Results Summary

### 1. Consensus Training
- **Models Trained**: {results['results']['consensus_training'].get('comparison_results', {}).get('model_results', {})}
- **Training Time**: {results['results']['consensus_training'].get('total_time', 0):.2f}s
- **Success**: {'✅' if results['results']['consensus_training'].get('success', False) else '❌'}

### 2. Model Comparison
- **Total Models**: {results['results']['model_comparison'].get('total_models', 0)}
- **Successful Models**: {results['results']['model_comparison'].get('successful_models', 0)}

### 3. Interpretability Analysis
- **Consensus Features**: {len(results['results']['interpretability_analysis'].get('consensus_features', {}))}
- **Feature Agreement**: {len(results['results']['interpretability_analysis'].get('feature_agreement', {}))}

### 4. Consensus Validation
- **Validation Passed**: {'✅' if results['results']['consensus_validation'].get('validation_passed', False) else '❌'}
- **Quality Score**: {results['results']['consensus_validation'].get('quality_score', 0):.4f}
- **Consensus Strength**: {results['results']['consensus_validation'].get('consensus_strength', 0):.4f}

### 5. Real-time Generation
- **Indicators Generated**: {results['results']['realtime_generation'].get('indicators_generated', 0)}
- **Models Used**: {results['results']['realtime_generation'].get('models_used', 0)}
- **Consensus Method**: {results['results']['realtime_generation'].get('consensus_method', 'N/A')}

### 6. Performance Evaluation
- **System Reliability**: {results['results']['performance_evaluation'].get('consensus_reliability', {}).get('average_reliability', 0):.4f}
- **Model Agreement**: {results['results']['performance_evaluation'].get('model_agreement_analysis', {}).get('average_agreement', 0):.4f}

## Conclusion
The consensus ML indicator system successfully demonstrates:
- Multi-model training and comparison
- Consensus-based indicator generation
- Interpretability analysis
- Quality validation
- Real-time generation capabilities

The system ensures that only indicators generated by multiple models are used, providing higher reliability and reducing false signals.
"""
        return report


def create_sample_data(n_samples: int = 2000) -> pd.DataFrame:
    """Create realistic sample OHLCV data for demonstration."""
    np.random.seed(42)
    
    # Generate price series with trend and volatility
    base_price = 100.0
    trend = np.linspace(0, 0.1, n_samples)  # 10% trend over period
    noise = np.random.normal(0, 0.02, n_samples)
    returns = trend + noise
    
    prices = base_price * np.exp(np.cumsum(returns))
    
    # Create OHLCV data
    data = pd.DataFrame({
        'open': prices * (1 + np.random.normal(0, 0.005, n_samples)),
        'high': prices * (1 + np.abs(np.random.normal(0, 0.01, n_samples))),
        'low': prices * (1 - np.abs(np.random.normal(0, 0.01, n_samples))),
        'close': prices,
        'volume': np.random.lognormal(10, 1, n_samples)
    }, index=pd.date_range('2020-01-01', periods=n_samples, freq='1min'))
    
    # Ensure OHLC constraints
    data['high'] = np.maximum(data['high'], np.maximum(data['open'], data['close']))
    data['low'] = np.minimum(data['low'], np.minimum(data['open'], data['close']))
    
    return data


def run_consensus_system_demo():
    """Run the complete consensus system demonstration."""
    print("🚀 Consensus ML Indicator System Demo")
    print("=" * 60)
    
    # Create sample data
    print("📊 Creating sample data...")
    data = create_sample_data(2000)
    print(f"   Generated {len(data)} samples")
    
    # Create demo
    demo = ConsensusSystemDemo()
    
    # Run complete demo
    print("\n🎯 Running complete consensus system demo...")
    results = demo.run_complete_demo(data, symbol='BTCUSDT')
    
    # Generate and display report
    print("\n📋 Generating demo report...")
    report = demo.generate_demo_report(results)
    print(report)
    
    # Save results
    import json
    with open('consensus_demo_results.json', 'w') as f:
        json.dump(results, f, default=str, indent=2)
    
    print(f"\n💾 Results saved to 'consensus_demo_results.json'")
    print("\n🎉 Consensus system demo completed successfully!")
    
    return demo, results


if __name__ == "__main__":
    demo, results = run_consensus_system_demo()