"""
Model Comparison Pipeline for ML Indicators

This module provides a comprehensive pipeline for comparing indicators generated
by different ML models, analyzing their performance, and selecting consensus-based
indicators that are generated by multiple models.

Key Features:
- Multi-model indicator comparison
- Performance analysis and ranking
- Consensus-based indicator selection
- Interpretability analysis
- Model agreement scoring
- Confidence-weighted consensus
"""

import numpy as np
import pandas as pd
import warnings
from typing import Any, Dict, List, Optional, Union, Tuple, Callable
import logging
import time
from datetime import datetime, timedelta
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
import json
import matplotlib.pyplot as plt
import seaborn as sns

# Core imports
from .ml_candle_pattern_indicators import (
    MLIndicatorGenerator, IndicatorType, ModelType, IndicatorConfig,
    create_ml_indicator_generator
)
from .ml_neural_indicators import (
    NeuralIndicatorGenerator, NeuralConfig, create_neural_indicator_generator
)

# ML common imports
try:
    from src.utils.ml_common.evaluation.unified_evaluator import evaluate_model
    from src.utils.ml_common.confidence_metrics import calculate_confidence_metrics
    from src.utils.ml_common.explainability.model_explainability import ModelExplainabilityManager
    ML_COMMON_AVAILABLE = True
except ImportError:
    ML_COMMON_AVAILABLE = False

# SHAP imports for interpretability
try:
    import shap
    SHAP_AVAILABLE = True
except ImportError:
    SHAP_AVAILABLE = False

logger = logging.getLogger(__name__)


class ConsensusMethod(Enum):
    """Methods for generating consensus indicators."""
    MAJORITY_VOTE = "majority_vote"
    WEIGHTED_AVERAGE = "weighted_average"
    CONFIDENCE_WEIGHTED = "confidence_weighted"
    PERFORMANCE_WEIGHTED = "performance_weighted"
    AGREEMENT_THRESHOLD = "agreement_threshold"


class ComparisonMetric(Enum):
    """Metrics for comparing model performance."""
    ACCURACY = "accuracy"
    PRECISION = "precision"
    RECALL = "recall"
    F1_SCORE = "f1_score"
    SHARPE_RATIO = "sharpe_ratio"
    MAX_DRAWDOWN = "max_drawdown"
    WIN_RATE = "win_rate"
    CONSISTENCY = "consistency"


@dataclass
class ConsensusConfig:
    """Configuration for consensus-based indicator selection."""
    # Consensus parameters
    consensus_method: ConsensusMethod = ConsensusMethod.CONFIDENCE_WEIGHTED
    min_agreement_threshold: float = 0.6  # Minimum agreement between models
    min_models_required: int = 2  # Minimum number of models that must agree
    confidence_threshold: float = 0.7  # Minimum confidence for consensus
    
    # Performance weighting
    performance_weights: Dict[ComparisonMetric, float] = None
    use_dynamic_weights: bool = True
    weight_update_frequency: int = 100  # Update weights every N samples
    
    # Interpretability
    enable_interpretability: bool = True
    explainability_methods: List[str] = None
    feature_importance_threshold: float = 0.1
    
    # Consensus validation
    enable_consensus_validation: bool = True
    validation_window: int = 20
    consensus_stability_threshold: float = 0.8
    
    def __post_init__(self):
        if self.performance_weights is None:
            self.performance_weights = {
                ComparisonMetric.ACCURACY: 0.3,
                ComparisonMetric.F1_SCORE: 0.3,
                ComparisonMetric.SHARPE_RATIO: 0.2,
                ComparisonMetric.CONSISTENCY: 0.2
            }
        
        if self.explainability_methods is None:
            self.explainability_methods = ['shap', 'feature_importance', 'permutation_importance']


class ModelComparisonPipeline:
    """
    Pipeline for comparing ML models and generating consensus indicators.
    
    This pipeline trains multiple ML models, compares their performance,
    and generates consensus-based indicators that are validated by multiple models.
    """
    
    def __init__(self, config: Optional[ConsensusConfig] = None):
        self.config = config or ConsensusConfig()
        self.models = {}
        self.model_performance = {}
        self.consensus_indicators = {}
        self.interpretability_results = {}
        self.comparison_history = []
        
        # Initialize interpretability analyzer if available
        if self.config.enable_interpretability and ML_COMMON_AVAILABLE:
            self.interpretability_analyzer = ModelExplainabilityManager()
        else:
            self.interpretability_analyzer = None
        
        logger.info("🔍 Model Comparison Pipeline initialized")
    
    def train_and_compare_models(self, data: pd.DataFrame, 
                                target_column: str = 'future_return',
                                symbol: str = 'BTCUSDT',
                                model_types: List[ModelType] = None) -> Dict[str, Any]:
        """
        Train multiple models and compare their performance.
        
        Args:
            data: Historical OHLCV data
            target_column: Target variable column name
            symbol: Trading symbol
            model_types: List of model types to compare
            
        Returns:
            Comparison results dictionary
        """
        if model_types is None:
            model_types = [ModelType.LIGHTGBM, ModelType.RANDOM_FOREST]
        
        logger.info(f"🔧 Training and comparing {len(model_types)} models for {symbol}")
        start_time = time.time()
        
        comparison_results = {
            'symbol': symbol,
            'start_time': start_time,
            'model_results': {},
            'performance_comparison': {},
            'consensus_analysis': {},
            'interpretability_analysis': {}
        }
        
        # Train each model
        for model_type in model_types:
            try:
                logger.info(f"📚 Training {model_type.value} model...")
                
                # Create and train model
                model_result = self._train_single_model(data, model_type, target_column)
                
                if model_result['success']:
                    self.models[model_type.value] = model_result
                    comparison_results['model_results'][model_type.value] = model_result
                    logger.info(f"✅ {model_type.value} training completed successfully")
                else:
                    logger.error(f"❌ {model_type.value} training failed: {model_result['error']}")
                    comparison_results['model_results'][model_type.value] = model_result
                
            except Exception as e:
                logger.error(f"❌ {model_type.value} training failed: {e}")
                comparison_results['model_results'][model_type.value] = {
                    'success': False,
                    'error': str(e)
                }
        
        # Compare model performance
        if len(self.models) > 1:
            logger.info("📊 Comparing model performance...")
            performance_comparison = self._compare_model_performance(data)
            comparison_results['performance_comparison'] = performance_comparison
        
        # Generate consensus indicators
        if len(self.models) >= self.config.min_models_required:
            logger.info("🤝 Generating consensus indicators...")
            consensus_analysis = self._generate_consensus_indicators(data)
            comparison_results['consensus_analysis'] = consensus_analysis
        
        # Interpretability analysis
        if self.config.enable_interpretability and len(self.models) > 0:
            logger.info("🔍 Performing interpretability analysis...")
            interpretability_analysis = self._analyze_interpretability(data)
            comparison_results['interpretability_analysis'] = interpretability_analysis
        
        comparison_results['end_time'] = time.time()
        comparison_results['total_time'] = comparison_results['end_time'] - start_time
        
        # Store comparison history
        self.comparison_history.append(comparison_results)
        
        logger.info(f"🎉 Model comparison completed in {comparison_results['total_time']:.2f} seconds")
        return comparison_results
    
    def _train_single_model(self, data: pd.DataFrame, model_type: ModelType, 
                           target_column: str) -> Dict[str, Any]:
        """Train a single model and evaluate its performance."""
        try:
            # Create model
            if model_type in [ModelType.GRU, ModelType.TFT]:
                neural_config = NeuralConfig(
                    hidden_size=64,
                    num_layers=2,
                    sequence_length=20,
                    num_epochs=20
                )
                generator = create_neural_indicator_generator(
                    model_type=model_type,
                    neural_config=neural_config
                )
                generator.train_neural_models(data)
            else:
                generator = create_ml_indicator_generator(model_type=model_type)
                generator.train_models(data)
            
            # Generate indicators
            indicators = generator._generate_feature(data)
            
            # Evaluate performance
            performance = self._evaluate_model_performance(data, indicators, target_column)
            
            # Calculate model confidence
            confidence = self._calculate_model_confidence(indicators)
            
            return {
                'success': True,
                'model_type': model_type.value,
                'generator': generator,
                'indicators': indicators,
                'performance': performance,
                'confidence': confidence,
                'training_time': time.time()
            }
            
        except Exception as e:
            return {
                'success': False,
                'model_type': model_type.value,
                'error': str(e)
            }
    
    def _evaluate_model_performance(self, data: pd.DataFrame, indicators: pd.Series, 
                                   target_column: str) -> Dict[str, float]:
        """Evaluate model performance using multiple metrics."""
        try:
            # Create binary signals
            signals = np.where(indicators > 0.5, 1, 0)
            
            # Create target (future price direction)
            if target_column in data.columns:
                future_returns = data[target_column]
            else:
                future_returns = data['close'].pct_change().shift(-1)
            
            targets = np.where(future_returns > 0, 1, 0)
            
            # Align signals and targets
            min_len = min(len(signals), len(targets))
            signals = signals[:min_len]
            targets = targets[:min_len]
            
            # Calculate classification metrics
            from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
            
            accuracy = accuracy_score(targets, signals)
            precision = precision_score(targets, signals, zero_division=0)
            recall = recall_score(targets, signals, zero_division=0)
            f1 = f1_score(targets, signals, zero_division=0)
            
            # Calculate trading metrics
            returns = data['close'].pct_change()
            strategy_returns = signals * returns
            
            sharpe_ratio = strategy_returns.mean() / strategy_returns.std() * np.sqrt(252) if strategy_returns.std() > 0 else 0
            max_drawdown = (strategy_returns.cumsum() - strategy_returns.cumsum().expanding().max()).min()
            win_rate = (strategy_returns > 0).mean()
            
            # Calculate consistency (how often the model makes the same prediction)
            consistency = self._calculate_consistency(indicators)
            
            return {
                'accuracy': accuracy,
                'precision': precision,
                'recall': recall,
                'f1_score': f1,
                'sharpe_ratio': sharpe_ratio,
                'max_drawdown': max_drawdown,
                'win_rate': win_rate,
                'consistency': consistency
            }
            
        except Exception as e:
            logger.warning(f"Performance evaluation failed: {e}")
            return {'error': str(e)}
    
    def _calculate_consistency(self, indicators: pd.Series) -> float:
        """Calculate model consistency over time."""
        if len(indicators) < 10:
            return 0.0
        
        # Calculate rolling correlation with previous values
        rolling_corr = indicators.rolling(10).apply(
            lambda x: x.corr(pd.Series(range(len(x)))) if len(x) == 10 else 0
        )
        
        return rolling_corr.mean()
    
    def _calculate_model_confidence(self, indicators: pd.Series) -> float:
        """Calculate model confidence based on indicator distribution."""
        # Confidence based on how far indicators are from 0.5 (neutral)
        distance_from_neutral = np.abs(indicators - 0.5)
        confidence = distance_from_neutral.mean() * 2  # Scale to 0-1
        
        return min(confidence, 1.0)
    
    def _compare_model_performance(self, data: pd.DataFrame) -> Dict[str, Any]:
        """Compare performance across all trained models."""
        if len(self.models) < 2:
            return {'error': 'Insufficient models for comparison'}
        
        comparison_results = {
            'model_rankings': {},
            'performance_matrix': {},
            'best_model': None,
            'worst_model': None,
            'performance_correlation': {}
        }
        
        # Create performance matrix
        performance_matrix = {}
        for model_name, model_result in self.models.items():
            if model_result['success']:
                performance_matrix[model_name] = model_result['performance']
        
        # Rank models by different metrics
        for metric in ComparisonMetric:
            if metric.value in performance_matrix[list(performance_matrix.keys())[0]]:
                metric_values = {
                    model: perf.get(metric.value, 0) 
                    for model, perf in performance_matrix.items()
                }
                
                # Sort by metric value (higher is better for most metrics)
                sorted_models = sorted(metric_values.items(), key=lambda x: x[1], reverse=True)
                comparison_results['model_rankings'][metric.value] = sorted_models
        
        # Find best and worst models (using F1 score as primary metric)
        if 'f1_score' in comparison_results['model_rankings']:
            f1_rankings = comparison_results['model_rankings']['f1_score']
            comparison_results['best_model'] = f1_rankings[0][0]
            comparison_results['worst_model'] = f1_rankings[-1][0]
        
        # Calculate performance correlation between models
        if len(performance_matrix) > 1:
            model_names = list(performance_matrix.keys())
            correlation_matrix = np.zeros((len(model_names), len(model_names)))
            
            for i, model1 in enumerate(model_names):
                for j, model2 in enumerate(model_names):
                    if i != j:
                        # Calculate correlation between model indicators
                        indicators1 = self.models[model1]['indicators']
                        indicators2 = self.models[model2]['indicators']
                        correlation = indicators1.corr(indicators2)
                        correlation_matrix[i, j] = correlation
            
            comparison_results['performance_correlation'] = {
                'correlation_matrix': correlation_matrix.tolist(),
                'model_names': model_names
            }
        
        comparison_results['performance_matrix'] = performance_matrix
        return comparison_results
    
    def _generate_consensus_indicators(self, data: pd.DataFrame) -> Dict[str, Any]:
        """Generate consensus indicators from multiple models."""
        if len(self.models) < self.config.min_models_required:
            return {'error': f'Insufficient models for consensus (need {self.config.min_models_required})'}
        
        consensus_results = {
            'consensus_method': self.config.consensus_method.value,
            'models_used': [],
            'consensus_indicators': {},
            'agreement_scores': {},
            'confidence_scores': {}
        }
        
        # Collect indicators from all successful models
        model_indicators = {}
        model_confidences = {}
        
        for model_name, model_result in self.models.items():
            if model_result['success']:
                model_indicators[model_name] = model_result['indicators']
                model_confidences[model_name] = model_result['confidence']
                consensus_results['models_used'].append(model_name)
        
        if len(model_indicators) < self.config.min_models_required:
            return {'error': 'Insufficient successful models for consensus'}
        
        # Generate consensus indicators based on method
        if self.config.consensus_method == ConsensusMethod.MAJORITY_VOTE:
            consensus_indicators = self._majority_vote_consensus(model_indicators)
        elif self.config.consensus_method == ConsensusMethod.WEIGHTED_AVERAGE:
            consensus_indicators = self._weighted_average_consensus(model_indicators)
        elif self.config.consensus_method == ConsensusMethod.CONFIDENCE_WEIGHTED:
            consensus_indicators = self._confidence_weighted_consensus(model_indicators, model_confidences)
        elif self.config.consensus_method == ConsensusMethod.PERFORMANCE_WEIGHTED:
            consensus_indicators = self._performance_weighted_consensus(model_indicators)
        elif self.config.consensus_method == ConsensusMethod.AGREEMENT_THRESHOLD:
            consensus_indicators = self._agreement_threshold_consensus(model_indicators)
        else:
            consensus_indicators = self._weighted_average_consensus(model_indicators)
        
        # Calculate agreement scores
        agreement_scores = self._calculate_agreement_scores(model_indicators)
        
        # Calculate confidence scores
        confidence_scores = self._calculate_consensus_confidence(consensus_indicators, model_indicators)
        
        consensus_results['consensus_indicators'] = consensus_indicators
        consensus_results['agreement_scores'] = agreement_scores
        consensus_results['confidence_scores'] = confidence_scores
        
        # Store consensus indicators
        self.consensus_indicators = consensus_indicators
        
        return consensus_results
    
    def _majority_vote_consensus(self, model_indicators: Dict[str, pd.Series]) -> pd.Series:
        """Generate consensus using majority vote."""
        # Convert to binary signals
        binary_signals = {}
        for model_name, indicators in model_indicators.items():
            binary_signals[model_name] = np.where(indicators > 0.5, 1, 0)
        
        # Calculate majority vote
        signal_matrix = np.array(list(binary_signals.values()))
        majority_votes = np.mean(signal_matrix, axis=0)
        
        # Convert back to continuous indicators
        consensus_indicators = pd.Series(majority_votes, index=model_indicators[list(model_indicators.keys())[0]].index)
        
        return consensus_indicators
    
    def _weighted_average_consensus(self, model_indicators: Dict[str, pd.Series]) -> pd.Series:
        """Generate consensus using weighted average."""
        # Equal weights for all models
        weights = {model: 1.0 for model in model_indicators.keys()}
        total_weight = sum(weights.values())
        
        # Calculate weighted average
        weighted_sum = None
        for model_name, indicators in model_indicators.items():
            if weighted_sum is None:
                weighted_sum = indicators * weights[model_name]
            else:
                weighted_sum += indicators * weights[model_name]
        
        consensus_indicators = weighted_sum / total_weight
        return consensus_indicators
    
    def _confidence_weighted_consensus(self, model_indicators: Dict[str, pd.Series], 
                                     model_confidences: Dict[str, float]) -> pd.Series:
        """Generate consensus using confidence-weighted average."""
        # Use model confidences as weights
        total_confidence = sum(model_confidences.values())
        
        # Calculate confidence-weighted average
        weighted_sum = None
        for model_name, indicators in model_indicators.items():
            weight = model_confidences[model_name] / total_confidence
            if weighted_sum is None:
                weighted_sum = indicators * weight
            else:
                weighted_sum += indicators * weight
        
        consensus_indicators = weighted_sum
        return consensus_indicators
    
    def _performance_weighted_consensus(self, model_indicators: Dict[str, pd.Series]) -> pd.Series:
        """Generate consensus using performance-weighted average."""
        # Calculate performance weights based on F1 scores
        performance_weights = {}
        for model_name, model_result in self.models.items():
            if model_result['success']:
                f1_score = model_result['performance'].get('f1_score', 0)
                performance_weights[model_name] = f1_score
        
        total_weight = sum(performance_weights.values())
        if total_weight == 0:
            return self._weighted_average_consensus(model_indicators)
        
        # Calculate performance-weighted average
        weighted_sum = None
        for model_name, indicators in model_indicators.items():
            weight = performance_weights[model_name] / total_weight
            if weighted_sum is None:
                weighted_sum = indicators * weight
            else:
                weighted_sum += indicators * weight
        
        consensus_indicators = weighted_sum
        return consensus_indicators
    
    def _agreement_threshold_consensus(self, model_indicators: Dict[str, pd.Series]) -> pd.Series:
        """Generate consensus only when models agree above threshold."""
        # Convert to binary signals
        binary_signals = {}
        for model_name, indicators in model_indicators.items():
            binary_signals[model_name] = np.where(indicators > 0.5, 1, 0)
        
        # Calculate agreement for each time point
        signal_matrix = np.array(list(binary_signals.values()))
        agreement_rates = np.mean(signal_matrix, axis=0)
        
        # Only use consensus when agreement is above threshold
        consensus_signals = np.where(
            agreement_rates >= self.config.min_agreement_threshold,
            agreement_rates,
            0.5  # Neutral when no agreement
        )
        
        consensus_indicators = pd.Series(consensus_signals, 
                                       index=model_indicators[list(model_indicators.keys())[0]].index)
        
        return consensus_indicators
    
    def _calculate_agreement_scores(self, model_indicators: Dict[str, pd.Series]) -> Dict[str, float]:
        """Calculate agreement scores between models."""
        agreement_scores = {}
        model_names = list(model_indicators.keys())
        
        for i, model1 in enumerate(model_names):
            for j, model2 in enumerate(model_names):
                if i < j:  # Avoid duplicate pairs
                    indicators1 = model_indicators[model1]
                    indicators2 = model_indicators[model2]
                    
                    # Calculate correlation as agreement measure
                    correlation = indicators1.corr(indicators2)
                    agreement_scores[f"{model1}_vs_{model2}"] = correlation
        
        return agreement_scores
    
    def _calculate_consensus_confidence(self, consensus_indicators: pd.Series, 
                                      model_indicators: Dict[str, pd.Series]) -> pd.Series:
        """Calculate confidence scores for consensus indicators."""
        # Confidence based on agreement between models
        model_array = np.array(list(model_indicators.values()))
        model_std = np.std(model_array, axis=0)
        
        # Higher agreement (lower std) = higher confidence
        confidence = 1.0 / (1.0 + model_std)
        
        return pd.Series(confidence, index=consensus_indicators.index)
    
    def _analyze_interpretability(self, data: pd.DataFrame) -> Dict[str, Any]:
        """Analyze model interpretability and feature importance."""
        if not self.config.enable_interpretability or len(self.models) == 0:
            return {'error': 'Interpretability analysis not enabled or no models available'}
        
        interpretability_results = {
            'feature_importance': {},
            'model_explanations': {},
            'consensus_features': {},
            'interpretability_scores': {}
        }
        
        # Analyze each model
        for model_name, model_result in self.models.items():
            if model_result['success']:
                try:
                    generator = model_result['generator']
                    
                    # Get feature importance if available
                    if hasattr(generator, 'get_feature_importance'):
                        feature_importance = generator.get_feature_importance()
                        interpretability_results['feature_importance'][model_name] = feature_importance
                    
                    # Generate model explanations
                    if self.interpretability_analyzer:
                        explanations = self._generate_model_explanations(generator, data)
                        interpretability_results['model_explanations'][model_name] = explanations
                    
                except Exception as e:
                    logger.warning(f"Interpretability analysis failed for {model_name}: {e}")
        
        # Find consensus features (features important across multiple models)
        if len(interpretability_results['feature_importance']) > 1:
            consensus_features = self._find_consensus_features(interpretability_results['feature_importance'])
            interpretability_results['consensus_features'] = consensus_features
        
        return interpretability_results
    
    def _generate_model_explanations(self, generator, data: pd.DataFrame) -> Dict[str, Any]:
        """Generate explanations for a single model."""
        try:
            # This would implement model-specific explanation generation
            # For now, return a placeholder
            return {
                'explanation_method': 'placeholder',
                'feature_contributions': {},
                'model_decision_factors': []
            }
        except Exception as e:
            logger.warning(f"Model explanation generation failed: {e}")
            return {'error': str(e)}
    
    def _find_consensus_features(self, feature_importance_dict: Dict[str, Any]) -> Dict[str, Any]:
        """Find features that are important across multiple models."""
        # This would implement consensus feature analysis
        # For now, return a placeholder
        return {
            'consensus_features': [],
            'feature_agreement_scores': {},
            'top_consensus_features': []
        }
    
    def get_consensus_indicators(self) -> Dict[str, pd.Series]:
        """Get the latest consensus indicators."""
        return self.consensus_indicators.copy()
    
    def get_model_performance_summary(self) -> Dict[str, Any]:
        """Get summary of model performance."""
        if not self.models:
            return {'error': 'No models available'}
        
        summary = {
            'total_models': len(self.models),
            'successful_models': len([m for m in self.models.values() if m['success']]),
            'model_performance': {},
            'best_model': None,
            'worst_model': None
        }
        
        # Calculate performance summary
        performance_scores = {}
        for model_name, model_result in self.models.items():
            if model_result['success']:
                performance = model_result['performance']
                f1_score = performance.get('f1_score', 0)
                performance_scores[model_name] = f1_score
                summary['model_performance'][model_name] = performance
        
        if performance_scores:
            best_model = max(performance_scores.items(), key=lambda x: x[1])
            worst_model = min(performance_scores.items(), key=lambda x: x[1])
            summary['best_model'] = best_model[0]
            summary['worst_model'] = worst_model[0]
        
        return summary
    
    def save_comparison_results(self, save_path: str):
        """Save comparison results to disk."""
        save_dir = Path(save_path)
        save_dir.mkdir(parents=True, exist_ok=True)
        
        # Save comparison results
        results_path = save_dir / 'comparison_results.json'
        with open(results_path, 'w') as f:
            json.dump(self.comparison_history, f, default=str, indent=2)
        
        # Save model performance
        performance_path = save_dir / 'model_performance.json'
        with open(performance_path, 'w') as f:
            json.dump(self.model_performance, f, default=str, indent=2)
        
        logger.info(f"💾 Comparison results saved to {save_path}")


def create_model_comparison_pipeline(config: Optional[ConsensusConfig] = None) -> ModelComparisonPipeline:
    """Create a model comparison pipeline with specified configuration."""
    return ModelComparisonPipeline(config)


def test_model_comparison_pipeline():
    """Test function for the model comparison pipeline."""
    print("🧪 Testing Model Comparison Pipeline...")
    
    # Create sample data
    np.random.seed(42)
    n_samples = 1000
    
    # Generate realistic OHLCV data
    base_price = 100.0
    returns = np.random.normal(0, 0.02, n_samples)
    prices = base_price * np.exp(np.cumsum(returns))
    
    data = pd.DataFrame({
        'open': prices * (1 + np.random.normal(0, 0.005, n_samples)),
        'high': prices * (1 + np.abs(np.random.normal(0, 0.01, n_samples))),
        'low': prices * (1 - np.abs(np.random.normal(0, 0.01, n_samples))),
        'close': prices,
        'volume': np.random.lognormal(10, 1, n_samples)
    }, index=pd.date_range('2020-01-01', periods=n_samples, freq='1min'))
    
    # Ensure OHLC constraints
    data['high'] = np.maximum(data['high'], np.maximum(data['open'], data['close']))
    data['low'] = np.minimum(data['low'], np.minimum(data['open'], data['close']))
    
    # Create comparison pipeline
    config = ConsensusConfig(
        consensus_method=ConsensusMethod.CONFIDENCE_WEIGHTED,
        min_models_required=2,
        enable_interpretability=True
    )
    pipeline = create_model_comparison_pipeline(config)
    
    # Train and compare models
    print("🔧 Training and comparing models...")
    results = pipeline.train_and_compare_models(
        data, 
        symbol='BTCUSDT',
        model_types=[ModelType.LIGHTGBM, ModelType.RANDOM_FOREST]
    )
    
    # Display results
    print("\n📊 Model Comparison Results:")
    for model_name, result in results['model_results'].items():
        if result.get('success', False):
            performance = result['performance']
            print(f"   ✅ {model_name}:")
            print(f"      F1-Score: {performance.get('f1_score', 0):.4f}")
            print(f"      Accuracy: {performance.get('accuracy', 0):.4f}")
            print(f"      Confidence: {result.get('confidence', 0):.4f}")
        else:
            print(f"   ❌ {model_name}: Failed")
    
    # Display consensus analysis
    if 'consensus_analysis' in results and 'consensus_indicators' in results['consensus_analysis']:
        consensus_indicators = results['consensus_analysis']['consensus_indicators']
        print(f"\n🤝 Consensus Indicators Generated:")
        print(f"   Mean: {consensus_indicators.mean():.4f}")
        print(f"   Std: {consensus_indicators.std():.4f}")
        print(f"   Models used: {len(results['consensus_analysis']['models_used'])}")
    
    # Get performance summary
    summary = pipeline.get_model_performance_summary()
    print(f"\n📈 Performance Summary:")
    print(f"   Total models: {summary['total_models']}")
    print(f"   Successful models: {summary['successful_models']}")
    if summary['best_model']:
        print(f"   Best model: {summary['best_model']}")
    
    print("\n🎉 Model Comparison Pipeline test completed successfully!")
    return pipeline, results


if __name__ == "__main__":
    test_model_comparison_pipeline()