#!/usr/bin/env python3
"""Test an extreme-score, same-model reserve-seeded admission fallback.

The exact-producer reserve map remains the primary 50-bps admission gate.
Only when it rejects does this ablation permit a candidate through the
same-model reserve-seeded causal map, and then only above a declared final-CDF
floor.  ``final_score`` is already a prior-42-day CDF generated by the exact
same producer, so this uses no held-window percentile and no cross-vintage
raw-score comparison.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np
import pandas as pd


LINEAGE = [
    "candidate_id", "__decision_ts__", "final_score", "conversion_bundle_sha256",
    "upstream_bundle_sha256", "geometry_bundle_sha256", "ev_score_family_id",
    "policy_path_valid", "policy_net_bps", "policy_gross_bps",
]
EXACT_MODE = "strict_oof_exact_producer_reserve_map_plus_causal_residual_v1"
SEEDED_MODE = "same_model_42d_reserve_seeded_v1"


def _sha(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def _summary(
    frame: pd.DataFrame, *, selected: pd.Series, expected: pd.Series, arm: str,
) -> list[dict[str, object]]:
    decision = pd.to_datetime(frame["__decision_ts__"], utc=True, errors="raise")
    valid = frame["policy_path_valid"].fillna(False).astype(bool)
    result: list[dict[str, object]] = []
    for frequency, periods in (("all", pd.Series("all", index=frame.index)), ("M", decision.dt.tz_localize(None).dt.to_period("M").astype(str)), ("W-MON", decision.dt.tz_localize(None).dt.to_period("W-MON").astype(str))):
        for period, positions in periods.groupby(periods, observed=True, sort=True).groups.items():
            index = np.asarray(list(positions), dtype=np.int64)
            mask = selected.iloc[index] & valid.iloc[index]
            net = pd.to_numeric(frame.policy_net_bps.iloc[index][mask], errors="coerce")
            gross = pd.to_numeric(frame.policy_gross_bps.iloc[index][mask], errors="coerce")
            result.append({
                "arm": arm, "frequency": frequency, "period": str(period),
                "scored_rows": int(len(index)), "selected_rows": int(selected.iloc[index].sum()),
                "valid_selected_rows": int(mask.sum()),
                "expected_net_bps_per_trade": float(expected.iloc[index][mask].mean()) if mask.any() else np.nan,
                "net_bps_per_trade": float(net.mean()) if len(net) else np.nan,
                "gross_bps_per_trade": float(gross.mean()) if len(gross) else np.nan,
                "positive_net_rate": float(net.gt(0).mean()) if len(net) else np.nan,
            })
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exact", type=Path, required=True)
    parser.add_argument("--seeded", type=Path, required=True)
    parser.add_argument("--cdf-floors", nargs="+", type=float, default=[0.99, 0.995])
    parser.add_argument("--net-floor-bps", type=float, default=50.0)
    parser.add_argument("--out-dir", type=Path, required=True)
    args = parser.parse_args()
    if args.out_dir.exists():
        raise FileExistsError(f"immutable extreme-fallback output exists: {args.out_dir}")
    floors = sorted(set(float(value) for value in args.cdf_floors))
    if not floors or any(not 0.0 < value < 1.0 for value in floors):
        raise ValueError("CDF floors must lie strictly between zero and one")
    columns = [*LINEAGE, "causal_21d_side_expected_net_bps", "ev_mapping_vintage_mode"]
    exact = pd.read_parquet(args.exact, columns=columns).rename(columns={
        "causal_21d_side_expected_net_bps": "exact_expected_bps",
        "ev_mapping_vintage_mode": "exact_mode",
    })
    seeded = pd.read_parquet(args.seeded, columns=columns).rename(columns={
        "causal_21d_side_expected_net_bps": "seeded_expected_bps",
        "ev_mapping_vintage_mode": "seeded_mode",
    })
    if exact.candidate_id.duplicated().any() or seeded.candidate_id.duplicated().any():
        raise ValueError("fallback requires unique candidate identities")
    compare = [column for column in LINEAGE if column != "candidate_id"]
    work = exact.merge(
        seeded.loc[:, ["candidate_id", *compare, "seeded_expected_bps", "seeded_mode"]],
        on="candidate_id", how="inner", suffixes=("", "__seeded"), validate="one_to_one",
    )
    if len(work) != len(exact) or len(work) != len(seeded):
        raise AssertionError("fallback requires identical candidate populations")
    for column in compare:
        left, right = work[column], work[f"{column}__seeded"]
        same = np.isclose(left.to_numpy(float), right.to_numpy(float), equal_nan=True) if pd.api.types.is_numeric_dtype(left) else left.astype(str).eq(right.astype(str)).to_numpy()
        if not bool(np.all(same)):
            raise AssertionError(f"fallback inputs disagree on {column}")
        work = work.drop(columns=f"{column}__seeded")
    if set(work.exact_mode.dropna().astype(str)) != {EXACT_MODE}:
        raise ValueError("primary map is not the exact-producer reserve bridge")
    if set(work.seeded_mode.dropna().astype(str)) != {SEEDED_MODE}:
        raise ValueError("fallback map is not the same-model reserve-seeded map")
    for column in ("exact_expected_bps", "seeded_expected_bps", "final_score"):
        if not np.isfinite(pd.to_numeric(work[column], errors="coerce")).all():
            raise ValueError(f"fallback input has non-finite {column}")

    exact_admitted = work.exact_expected_bps.ge(float(args.net_floor_bps))
    seed_admitted = work.seeded_expected_bps.ge(float(args.net_floor_bps))
    selection = work.loc[:, ["candidate_id", "__decision_ts__"]].copy()
    metrics: list[dict[str, object]] = []
    for floor in floors:
        name = f"E{int(round(args.net_floor_bps)):03d}_exact_seed_fallback_cdf{int(round(floor * 1000)):03d}"
        fallback = ~exact_admitted & seed_admitted & work.final_score.ge(floor)
        selected = exact_admitted | fallback
        expected = work.exact_expected_bps.where(exact_admitted, work.seeded_expected_bps)
        selection[f"{name}__admitted"] = selected.to_numpy(bool)
        selection[f"{name}__expected_net_bps"] = expected.to_numpy(float)
        selection[f"{name}__seeded_fallback"] = fallback.to_numpy(bool)
        metrics.extend(_summary(work, selected=selected, expected=expected, arm=name))
    args.out_dir.mkdir(parents=True)
    selection.to_parquet(args.out_dir / "threshold_selection.parquet", index=False, compression="zstd")
    pd.DataFrame(metrics).to_parquet(args.out_dir / "threshold_metrics.parquet", index=False)
    manifest = {
        "schema": "strict_r3_reserve_seeded_extreme_fallback_v1",
        "exact": str(args.exact), "exact_sha256": _sha(args.exact),
        "seeded": str(args.seeded), "seeded_sha256": _sha(args.seeded),
        "net_floor_bps": float(args.net_floor_bps), "cdf_floors": floors,
        "contract": (
            "exact-producer reserve expected-net map is always primary; only an exact-map rejection may use the "
            "same-model reserve-seeded causal map, only at a same-producer prior-42 CDF extreme; no raw-score "
            "cross-vintage pooling, retraining, score change, outcome change or held-period fitting"
        ),
    }
    (args.out_dir / "run_manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(json.dumps({"event": "complete", "out_dir": str(args.out_dir), "rows": len(work), "arms": len(floors)}))


if __name__ == "__main__":
    main()
