#!/usr/bin/env python3
"""Compare direct P8U price-memory state to a sealed persisted feature row.

This uses the feature transaction generated by the canonical P8U runtime as
the oracle.  It intentionally does *not* regenerate that reference with the
broad graph: an independently materialised source panel can itself be
incomplete for a field, which would test source availability rather than the
direct recurrence.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import joblib
import numpy as np
import pandas as pd

from extreme_price_movements.inference.p8u_single_timestamp_graph import (
    P8UPriceMemoryCausalState,
)


FEATURE = "prior_volatility"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(8 * 1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-state", required=True)
    parser.add_argument("--reference-features", required=True)
    parser.add_argument("--signal-ts", required=True)
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--atol", type=float, default=2e-6)
    parser.add_argument("--rtol", type=float, default=2e-5)
    return parser.parse_args()


def main() -> None:
    args = _args()
    source_path = Path(args.source_state).resolve()
    reference_path = Path(args.reference_features).resolve()
    out_dir = Path(args.out_dir).resolve()
    if any(ROOT not in path.parents for path in (source_path, reference_path, out_dir)):
        raise ValueError("P8U audit paths must remain below repository root")
    if out_dir.exists():
        raise FileExistsError(f"immutable direct-state audit exists: {out_dir}")
    signal_ts = pd.Timestamp(args.signal_ts)
    signal_ts = signal_ts.tz_localize("UTC") if signal_ts.tzinfo is None else signal_ts.tz_convert("UTC")
    source = joblib.load(source_path)
    if not isinstance(source, dict) or not isinstance(source.get("panel"), dict):
        raise ValueError("source state lacks target-free panel")
    symbols = tuple(map(str, source.get("symbols") or source.get("universe_symbols") or ()))
    panel = {
        name: value.loc[:signal_ts]
        if isinstance(value, pd.DataFrame)
        else value
        for name, value in source["panel"].items()
    }
    close = panel.get("close")
    if not isinstance(close, pd.DataFrame) or len(symbols) != 160 or close.index[-1] != signal_ts:
        raise ValueError("source panel cannot form the exact requested signal row")
    reference = pd.read_parquet(reference_path, columns=["candidate_id", "__decision_ts__", FEATURE])
    if reference.empty:
        raise ValueError("sealed reference contains no candidates")
    decision = pd.to_datetime(reference["__decision_ts__"], utc=True, errors="raise")
    if decision.nunique() != 1 or decision.iloc[0] != signal_ts + pd.Timedelta(hours=1):
        raise ValueError("reference decision timestamp does not follow the declared signal row")
    reference["symbol"] = reference["candidate_id"].astype(str).str.split("|").str[0]
    if reference["symbol"].duplicated().any() or not reference["symbol"].isin(symbols).all():
        raise ValueError("sealed reference candidate identities do not map uniquely to source symbols")
    started = time.perf_counter()
    state = P8UPriceMemoryCausalState(symbols=symbols, transform_keys=(FEATURE,))
    emitted = state.bootstrap(panel)[f"feature__{FEATURE}"][-1]
    direct = pd.Series(emitted, index=pd.Index(symbols, name="symbol"), name="direct")
    audit = reference[["candidate_id", "symbol", FEATURE]].join(direct, on="symbol")
    left = audit[FEATURE].to_numpy(np.float32)
    right = audit["direct"].to_numpy(np.float32)
    finite = np.isfinite(left) & np.isfinite(right)
    mismatch = np.isfinite(left) ^ np.isfinite(right)
    delta = np.abs(left[finite].astype(np.float64) - right[finite].astype(np.float64))
    passed = not mismatch.any() and bool(np.isclose(left[finite], right[finite], atol=args.atol, rtol=args.rtol).all())
    audit["abs_delta"] = np.where(finite, np.abs(left - right), np.nan).astype(np.float32)
    out_dir.mkdir(parents=True)
    audit.to_parquet(out_dir / "candidate_parity.parquet", compression="zstd", index=False)
    summary = {
        "schema": "strict_r3_p8u_direct_price_memory_reference_parity_v1",
        "status": "pass" if passed else "fail",
        "signal_timestamp": signal_ts.isoformat(),
        "reference_decision_timestamp": decision.iloc[0].isoformat(),
        "source_state": str(source_path),
        "source_state_sha256": _sha256(source_path),
        "reference_features": str(reference_path),
        "reference_features_sha256": _sha256(reference_path),
        "source_symbols": len(symbols),
        "reference_candidates": int(len(reference)),
        "finite_pairs": int(finite.sum()),
        "missing_mismatch": int(mismatch.sum()),
        "max_abs_delta": float(delta.max()) if len(delta) else 0.0,
        "atol": args.atol,
        "rtol": args.rtol,
        "runtime_seconds": time.perf_counter() - started,
        "outcome_columns_consumed": [],
        "batch_oracle_role": "none; sealed persisted canonical transaction",
        "direct_node_calls_broad_feature_graph": False,
    }
    (out_dir / "summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
    print(json.dumps(summary, indent=2, sort_keys=True))
    if not passed:
        raise AssertionError("direct price-memory state differs from sealed reference")


if __name__ == "__main__":
    main()
