#!/usr/bin/env python3
"""Materialize pre-2026 candidate history with one frozen production contract.

This runner intentionally does not retrain any component.  It rebuilds base and
raw-meta predictions from the canonical static feature store using the current
frozen base/meta/AE-GMM bundle, then persists compact side x archetype-aware
candidate ledgers.  The output is retrospective model scoring, not OOF/OOS
validation evidence.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from dataclasses import asdict, dataclass
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
SCORER = ROOT / "scripts" / "backfill_complete_july_meta_predictions.py"
DEFAULT_ARTIFACT = (
    ROOT
    / "data_perp/artifacts/"
    "s59_s52_base66_residualstate_meta_v9tail95_mlp_hierev_ev70_geometry_20260717_v2"
)
DEFAULT_BASE_REPORT = (
    ROOT
    / "data_perp/reports/"
    "s59_h5_benchmark66_matchedaegmm_refit_wf30_20260716_v1"
)
DEFAULT_LABELS = (
    ROOT
    / "data_perp/artifacts/"
    "20260713_s59_h5_fullthroughjul10_trailing_cost100bps_labels/labels"
)
DEFAULT_FEATURE_ROOT = ROOT / "data_perp/features/20260711_070000"
DEFAULT_OUTPUT = ROOT / "data_perp/reports/frozen_meta_contract_history_20260720_v1"


@dataclass(frozen=True)
class MonthResult:
    month: str
    start: str
    end_exclusive: str
    output: str
    status: str
    rows: int | None = None


def _utc_months(start: pd.Timestamp, end: pd.Timestamp) -> list[pd.Timestamp]:
    first = start.normalize().replace(day=1)
    last = (end - pd.Timedelta(nanoseconds=1)).normalize().replace(day=1)
    return list(
        pd.date_range(
            start=first,
            end=last,
            freq="MS",
            tz="UTC",
        )
    )


def _load_existing_rows(
    month_dir: Path,
    *,
    model_artifact_root: Path,
) -> int | None:
    manifest_path = month_dir / "manifest.json"
    output_path = month_dir / "candidates.parquet"
    if not manifest_path.exists() or not output_path.exists():
        return None
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if manifest.get("schema") != "frozen_meta_compact_candidate_backcast_v1":
        return None
    if manifest.get("evidence_scope") != "frozen_backcast_diagnostic":
        return None
    provenance = dict(manifest.get("model_provenance") or {})
    expected = (model_artifact_root / "models" / "trained_state.pkl").resolve()
    actual = Path(
        str((provenance.get("base_model") or {}).get("resolved_path", ""))
    )
    if actual != expected:
        return None
    return int(manifest.get("rows", -1))


def _write_manifest(
    path: Path,
    *,
    args: argparse.Namespace,
    results: list[MonthResult],
) -> None:
    payload = {
        "schema": "frozen_meta_contract_history_v1",
        "evidence_scope": "frozen_backcast_diagnostic",
        "statement": (
            "Rows are retrospective predictions generated by the current frozen "
            "base/meta/AE-GMM contract. They are suitable for historical state "
            "discovery and diagnostics, not OOF/OOS performance claims."
        ),
        "score_stage": (
            "frozen_base_plus_raw_side_meta_before_residual_v9_mlp_and_policy"
        ),
        "label_usage": (
            "Labels provide the historical eligible-symbol universe and causal "
            "barrier context only; realized outcome columns never enter scoring."
        ),
        "feature_root": str(args.feature_root),
        "labels_dir": str(args.labels_dir),
        "model_artifact_root": str(args.model_artifact_root),
        "ae_gmm_state": str(args.ae_gmm_state),
        "context_warmup_hours": int(args.context_warmup_hours),
        "months": [asdict(result) for result in results],
        "completed_rows": int(sum(result.rows or 0 for result in results)),
    }
    temp = path.with_suffix(".tmp")
    temp.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    temp.replace(path)


def _read_prior_results(path: Path) -> dict[str, MonthResult]:
    """Retain completed months when incrementally extending a history root."""

    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    if payload.get("schema") != "frozen_meta_contract_history_v1":
        return {}
    results: dict[str, MonthResult] = {}
    for item in payload.get("months", []):
        try:
            result = MonthResult(**item)
        except TypeError:
            continue
        results[result.month] = result
    return results


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--start", default="2025-01-01T00:00:00Z")
    parser.add_argument("--end-exclusive", default="2026-01-01T00:00:00Z")
    parser.add_argument("--feature-root", type=Path, default=DEFAULT_FEATURE_ROOT)
    parser.add_argument("--labels-dir", type=Path, default=DEFAULT_LABELS)
    parser.add_argument("--model-artifact-root", type=Path, default=DEFAULT_ARTIFACT)
    parser.add_argument(
        "--base-reference",
        type=Path,
        default=DEFAULT_BASE_REPORT / "best_oos_scored_ledger.parquet",
    )
    parser.add_argument(
        "--meta-handoff-dir",
        type=Path,
        default=DEFAULT_BASE_REPORT / "meta_handoff_top30_allsafe_newaegmm_20260717",
    )
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--context-warmup-hours", type=int, default=336)
    parser.add_argument("--max-months", type=int, default=0)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--force", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    start = pd.Timestamp(args.start)
    end = pd.Timestamp(args.end_exclusive)
    if start.tzinfo is None or end.tzinfo is None:
        raise ValueError("Historical scoring boundaries must be explicit UTC timestamps")
    start = start.tz_convert("UTC")
    end = end.tz_convert("UTC")
    if end <= start:
        raise ValueError("--end-exclusive must be after --start")
    if int(args.context_warmup_hours) < 0:
        raise ValueError("--context-warmup-hours must be non-negative")

    ae_gmm_state = args.model_artifact_root / "ae_gmm_state/ae_gmm_state.pkl"
    args.ae_gmm_state = ae_gmm_state
    policy_params = args.model_artifact_root / "policy_params"
    source_manifest = args.meta_handoff_dir / "manifest.json"
    required = [
        SCORER,
        args.feature_root,
        args.labels_dir,
        args.model_artifact_root / "models/trained_state.pkl",
        args.model_artifact_root / "models/model_state_meta.pkl",
        ae_gmm_state,
        args.base_reference,
        args.meta_handoff_dir / "train_meta_regime_handoff.parquet",
        source_manifest,
        policy_params / "v9_tail95_predecessor_bundle.joblib",
        args.labels_dir / "side_archetype_label_manifest.json",
    ]
    missing = [str(path) for path in required if not path.exists()]
    if missing:
        raise FileNotFoundError("Required frozen-history inputs are missing:\n" + "\n".join(missing))

    months = _utc_months(start, end)
    if int(args.max_months) > 0:
        months = months[: int(args.max_months)]
    args.output_root.mkdir(parents=True, exist_ok=True)
    manifest_path = args.output_root / "history_manifest.json"
    results_by_month = _read_prior_results(manifest_path)

    def persist() -> None:
        _write_manifest(
            manifest_path,
            args=args,
            results=[results_by_month[key] for key in sorted(results_by_month)],
        )

    for month_start in months:
        month_end = month_start + pd.offsets.MonthBegin(1)
        month_key = month_start.strftime("%Y-%m")
        month_dir = args.output_root / "monthly" / month_key
        existing_rows = (
            None
            if args.force
            else _load_existing_rows(
                month_dir,
                model_artifact_root=args.model_artifact_root,
            )
        )
        if existing_rows is not None:
            result = MonthResult(
                month=month_key,
                start=month_start.isoformat(),
                end_exclusive=month_end.isoformat(),
                output=str(month_dir / "candidates.parquet"),
                status="skipped_existing",
                rows=existing_rows,
            )
            results_by_month[month_key] = result
            persist()
            print(f"[{month_key}] existing compact ledger: rows={existing_rows}")
            continue

        command = [
            sys.executable,
            str(SCORER),
            "--feature-root",
            str(args.feature_root),
            "--labels-dir",
            str(args.labels_dir),
            "--base-reference",
            str(args.base_reference),
            "--model-artifact-root",
            str(args.model_artifact_root),
            "--ae-gmm-state",
            str(ae_gmm_state),
            "--meta-handoff-dir",
            str(args.meta_handoff_dir),
            "--residual-bundle",
            str(policy_params / "v9_tail95_predecessor_bundle.joblib"),
            "--residual-train-reference",
            str(args.meta_handoff_dir / "train_meta_regime_handoff.parquet"),
            "--native-run-id",
            args.model_artifact_root.name,
            "--policy-manifest",
            str(args.labels_dir / "side_archetype_label_manifest.json"),
            "--source-manifest",
            str(source_manifest),
            "--output-dir",
            str(month_dir),
            "--output-filename",
            "candidates.parquet",
            "--start",
            month_start.isoformat(),
            "--end-exclusive",
            month_end.isoformat(),
            "--context-warmup-hours",
            str(int(args.context_warmup_hours)),
            "--evidence-scope",
            "frozen_backcast_diagnostic",
            "--rescore-observed",
            "--stop-after-meta",
            "--compact-meta-output",
        ]
        print(f"[{month_key}] {' '.join(command)}")
        if args.dry_run:
            result = MonthResult(
                month=month_key,
                start=month_start.isoformat(),
                end_exclusive=month_end.isoformat(),
                output=str(month_dir / "candidates.parquet"),
                status="planned",
            )
            results_by_month[month_key] = result
            persist()
            continue

        subprocess.run(command, cwd=ROOT, check=True)
        rows = _load_existing_rows(
            month_dir,
            model_artifact_root=args.model_artifact_root,
        )
        if rows is None:
            raise RuntimeError(f"[{month_key}] scorer completed without a compact ledger")
        result = MonthResult(
            month=month_key,
            start=month_start.isoformat(),
            end_exclusive=month_end.isoformat(),
            output=str(month_dir / "candidates.parquet"),
            status="completed",
            rows=rows,
        )
        results_by_month[month_key] = result
        persist()
        print(f"[{month_key}] complete: rows={rows}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
