#!/usr/bin/env python3
"""Compare champion, local-tail, residual-state, and nested state+tail ranks."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

from scripts.run_meta_residual_extreme_local_champion_overlay import (
    _adjust_rank,
    _autocorrelation_report,
    _breakdown,
    _composite,
    _fit_references,
    _metric_row,
)
from scripts.run_meta_residual_extreme_local_tail_refinement import _load_frames

KEYS = ["__ts__", "__symbol__", "side_name", "archetype_policy_key"]


def run(args: argparse.Namespace) -> dict[str, object]:
    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)
    train, valid = _load_frames(args.state_artifact, args.rank_cache, args.parent_eval)
    catalog = pd.read_csv(args.local_feature_catalog)
    references = _fit_references(train, catalog, int(args.top_feature_count))
    train_adverse = _composite(train, references, "adverse")
    valid_adverse = _composite(valid, references, "adverse")
    train_positive = _composite(train, references, "positive")
    valid_positive = _composite(valid, references, "positive")

    arm = pd.read_parquet(args.state_arm_predictions)
    arm["__ts__"] = pd.to_datetime(arm["__ts__"], utc=True, errors="coerce")
    available_keys = [name for name in KEYS if name in arm and name in valid]
    if len(available_keys) != len(KEYS):
        raise ValueError(f"State arm is missing comparison keys: {available_keys}")
    state_scores = arm[available_keys + ["score_alternative"]].drop_duplicates(
        available_keys, keep="last"
    )
    valid = valid.merge(
        state_scores,
        on=available_keys,
        how="inner",
        validate="one_to_one",
    )
    if len(valid) != len(arm):
        raise ValueError(
            f"State/tail row mismatch: valid={len(valid)} state_arm={len(arm)}"
        )
    state_rank = (
        pd.to_numeric(valid["score_alternative"], errors="coerce")
        .groupby(valid["__ts__"], observed=True)
        .rank(pct=True)
        .to_numpy(dtype=np.float32)
    )
    parent_rank = pd.to_numeric(valid["historical_rank"], errors="coerce").to_numpy(
        dtype=np.float32
    )
    # References and alpha are frozen from train. The train composites are
    # materialized here to prove parity and prevent accidental OOS refitting.
    if len(train_adverse) != len(train) or len(train_positive) != len(train):
        raise RuntimeError("Train-only local composite materialization failed")
    tail_rank = _adjust_rank(
        parent_rank,
        valid_adverse,
        valid_positive,
        threshold=float(args.tail_threshold),
        alpha_down=float(args.alpha_down),
        alpha_up=float(args.alpha_up),
    )
    nested_rank = _adjust_rank(
        state_rank,
        valid_adverse,
        valid_positive,
        threshold=float(args.tail_threshold),
        alpha_down=float(args.alpha_down),
        alpha_up=float(args.alpha_up),
    )
    selectors = {
        "champion_reference": parent_rank >= 0.90,
        "champion_local_tail_95": tail_rank >= 0.90,
        "residual_state_rank": state_rank >= 0.90,
        "residual_state_rank_local_tail_95": nested_rank >= 0.90,
    }
    summaries = [
        _metric_row(valid, mask, selector) for selector, mask in selectors.items()
    ]
    breakdowns = [
        _breakdown(valid, mask, selector) for selector, mask in selectors.items()
    ]
    autocorrelation, autocorrelation_detail = _autocorrelation_report(valid, selectors)
    pd.DataFrame(summaries).to_csv(output / "summary.csv", index=False)
    pd.concat(breakdowns, ignore_index=True).to_csv(
        output / "breakdowns.csv", index=False
    )
    autocorrelation.to_csv(output / "autocorrelation_daily.csv", index=False)
    autocorrelation_detail.to_csv(output / "autocorrelation_summary.csv", index=False)
    scored = valid[KEYS].copy()
    scored["parent_rank"] = parent_rank
    scored["state_rank"] = state_rank
    scored["tail_rank"] = tail_rank
    scored["nested_rank"] = nested_rank
    for selector, mask in selectors.items():
        scored[f"selected__{selector}"] = mask
    scored.to_parquet(output / "rank_comparison.parquet", index=False, compression="zstd")
    manifest = {
        "schema": "nested_residual_state_tail_revision_v1",
        "state_arm_predictions": str(args.state_arm_predictions),
        "tail_threshold": float(args.tail_threshold),
        "alpha_down": float(args.alpha_down),
        "alpha_up": float(args.alpha_up),
        "top_feature_count": int(args.top_feature_count),
        "rows": int(len(valid)),
        "train_reference_rows": int(len(train)),
        "leakage_contract": (
            "Local feature references and tail alpha are train-frozen; state ranks are "
            "generated by the fixed meta revision and all metrics use April-June rows only."
        ),
    }
    (output / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8"
    )
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--state-artifact", type=Path, required=True)
    parser.add_argument("--rank-cache", type=Path, required=True)
    parser.add_argument("--parent-eval", type=Path, required=True)
    parser.add_argument("--local-feature-catalog", type=Path, required=True)
    parser.add_argument("--state-arm-predictions", type=Path, required=True)
    parser.add_argument("--tail-threshold", type=float, default=0.95)
    parser.add_argument("--alpha-down", type=float, default=0.02)
    parser.add_argument("--alpha-up", type=float, default=0.0)
    parser.add_argument("--top-feature-count", type=int, default=1)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(run(args), sort_keys=True), flush=True)


if __name__ == "__main__":
    main()
