class HighLevelAuthManager:
    def __init__(self, *args, **kwargs): ...

class HighLevelMarketManager:
    def __init__(self, *args, **kwargs): ...

class HighLevelOrderManager:
    def __init__(self, *args, **kwargs): ...

class HighLevelRiskManager:
    def __init__(self, *args, **kwargs): ...

class HighLevelBalanceManager:
    def __init__(self, *args, **kwargs): ...

class HighLevelRateLimitManager:
    def __init__(self, *args, **kwargs): ...
